In [24]:
import pandas as pd

# arizona

## reverse mortgage

In [25]:
#read csv

arizona_all_2021 = pd.read_csv('./all_mortgage_data/arizona_all_2021_originated.csv', dtype={
    'county_code': str,
    'census_tract': str
})

# filter to reverse mortgage

rm_arizona_all_2021 = arizona_all_2021[(arizona_all_2021['reverse_mortgage'] == 1)]


# export to csv

rm_arizona_all_2021.to_csv('./reverse_mortgage_data/south_carolina/rm_arizona_all_2021.csv', index=False)

/var/folders/br/8x3cfw457y1gzxfpj7108n100000gn/T/ipykernel_38180/19418862.py:3: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  arizona_all_2021 = pd.read_csv('./all_mortgage_data/arizona_all_2021_originated.csv', dtype={

In [26]:
rm_arizona_all_2021.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4291 entries, 8619 to 457029
Data columns (total 99 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   activity_year                             4291 non-null   int64
 1   lei                                       4291 non-null   object
 2   derived_msa-md                            4291 non-null   int64
 3   state_code                                4291 non-null   object
 4   county_code                               4291 non-null   object
 5   census_tract                              4291 non-null   object
 6   conforming_loan_limit                     4291 non-null   object
 7   derived_loan_product_type                 4291 non-null   object
 8   derived_dwelling_category                 4291 non-null   object
 9   derived_ethnicity                         4291 non-null   object
 10  derived_race                              4291 non-null   object
 11  derived_sex                               4291 non-null   object
 12  action_taken                              4291 non-null   int64
 13  purchaser_type                            4291 non-null   int64
 14  preapproval                               4291 non-null   int64
 15  loan_type                                 4291 non-null   int64
 16  loan_purpose                              4291 non-null   int64
 17  lien_status                               4291 non-null   int64
 18  reverse_mortgage                          4291 non-null   int64
 19  open-end_line_of_credit                   4291 non-null   int64
 20  business_or_commercial_purpose            4291 non-null   int64
 21  loan_amount                               4291 non-null   float64
 22  loan_to_value_ratio                       336 non-null    object
 23  interest_rate                             4111 non-null   object
 24  rate_spread                               0 non-null      object
 25  hoepa_status                              4291 non-null   int64
 26  total_loan_costs                          0 non-null      object
 27  total_points_and_fees                     0 non-null      object
 28  origination_charges                       0 non-null      object
 29  discount_points                           0 non-null      object
 30  lender_credits                            0 non-null      object
 31  loan_term                                 0 non-null      object
 32  prepayment_penalty_term                   0 non-null      object
 33  intro_rate_period                         2328 non-null   object
 34  negative_amortization                     4291 non-null   int64
 35  interest_only_payment                     4291 non-null   int64
 36  balloon_payment                           4291 non-null   int64
 37  other_nonamortizing_features              4291 non-null   int64
 38  property_value                            4112 non-null   object
 39  construction_method                       4291 non-null   int64
 40  occupancy_type                            4291 non-null   int64
 41  manufactured_home_secured_property_type   4291 non-null   int64
 42  manufactured_home_land_property_interest  4291 non-null   int64
 43  total_units                               4291 non-null   object
 44  multifamily_affordable_units              0 non-null      object
 45  income                                    4256 non-null   float64
 46  debt_to_income_ratio                      326 non-null    object
 47  applicant_credit_score_type               4291 non-null   int64
 48  co-applicant_credit_score_type            4291 non-null   int64
 49  applicant_ethnicity-1                     4291 non-null   float64
 50  applicant_ethnicity-2                     85 non-null     float64
 51  applicant_ethnicity-3                     1 non-null      float64
 52  applicant_ethnicity-4                     0 non-null      float64
 53  applicant_ethnicity-5                     0 non-null      float64
 54  co-applicant_ethnicity-1                  4291 non-null   float64
 55  co-applicant_ethnicity-2                  32 non-null     float64
 56  co-applicant_ethnicity-3                  1 non-null      float64
 57  co-applicant_ethnicity-4                  0 non-null      float64
 58  co-applicant_ethnicity-5                  0 non-null      float64
 59  applicant_ethnicity_observed              4291 non-null   int64
 60  co-applicant_ethnicity_observed           4291 non-null   int64
 61  applicant_race-1                          4291 non-null   float64
 62  applicant_race-2                          21 non-null     float64
 63  applicant_race-3                          1 non-null      float64
 64  applicant_race-4                          0 non-null      float64
 65  applicant_race-5                          0 non-null      float64
 66  co-applicant_race-1                       4291 non-null   float64
 67  co-applicant_race-2                       15 non-null     float64
 68  co-applicant_race-3                       2 non-null      float64
 69  co-applicant_race-4                       1 non-null      float64
 70  co-applicant_race-5                       0 non-null      float64
 71  applicant_race_observed                   4291 non-null   int64
 72  co-applicant_race_observed                4291 non-null   int64
 73  applicant_sex                             4291 non-null   int64
 74  co-applicant_sex                          4291 non-null   int64
 75  applicant_sex_observed                    4291 non-null   int64
 76  co-applicant_sex_observed                 4291 non-null   int64
 77  applicant_age                             4291 non-null   object
 78  co-applicant_age                          4291 non-null   object
 79  applicant_age_above_62                    4112 non-null   object
 80  co-applicant_age_above_62                 1965 non-null   object
 81  submission_of_application                 4291 non-null   int64
 82  initially_payable_to_institution          4291 non-null   int64
 83  aus-1                                     4291 non-null   int64
 84  aus-2                                     0 non-null      float64
 85  aus-3                                     0 non-null      float64
 86  aus-4                                     0 non-null      float64
 87  aus-5                                     0 non-null      float64
 88  denial_reason-1                           4291 non-null   int64
 89  denial_reason-2                           0 non-null      float64
 90  denial_reason-3                           0 non-null      float64
 91  denial_reason-4                           0 non-null      float64
 92  tract_population                          4291 non-null   int64
 93  tract_minority_population_percent         4291 non-null   float64
 94  ffiec_msa_md_median_family_income         4291 non-null   int64
 95  tract_to_msa_income_percentage            4291 non-null   int64
 96  tract_owner_occupied_units                4291 non-null   int64
 97  tract_one_to_four_family_homes            4291 non-null   int64
 98  tract_median_age_of_housing_units         4291 non-null   int64
dtypes: float64(30), int64(40), object(29)
memory usage: 3.3+ MB

## census

In [27]:
# read census csv

acs2021 = pd.read_csv('./census_data/acs_2021_arizona.csv')

# drop the second header row

acs2021 = acs2021.drop([0])

# subset to population data

acs_2021_race = acs2021[['GEO_ID', 'NAME', 'DP05_0001E', 'DP05_0071E', 'DP05_0078E']]

# rename columns

acs_2021_race.columns = ['geo_id', 'tract_name', 'population', 'hispanic_pp', 'black_pp']

# split geo_id column

tract_code = acs_2021_race['geo_id'].str.split(pat='US', expand=True)

# insert the census_tract column

acs_2021_race.insert(loc = 1, column='census_tract', value=tract_code[1])

# correctly type the data

acs_2021_race = acs_2021_race.astype({
    'population': int,
    'hispanic_pp': int,
    'black_pp': int
})

# calcualate hispanic & black population

acs_2021_race['hispanic_pp_pct'] = acs_2021_race['hispanic_pp'] / acs_2021_race['population'] * 100
acs_2021_race['black_pp_pct'] = acs_2021_race['black_pp'] / acs_2021_race['population'] * 100

/var/folders/br/8x3cfw457y1gzxfpj7108n100000gn/T/ipykernel_38180/3909219827.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,114,115,116,117,118,119,120,121,122,123,124,125,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,361,454,457,470,473,486,489,606,609,634,637,702,705) have mixed types. Specify dtype option on import or set low_memory=False.
  acs2021 = pd.read_csv('./census_data/acs_2021_arizona.csv')

In [28]:
acs_2021_race

,geo_id,census_tract,tract_name,population,hispanic_pp,black_pp,hispanic_pp_pct,black_pp_pct
1,1400000US04001942600,04001942600,"Census Tract 9426, Apache County, Arizona",1737,47,0,2.705815,0.000000
2,1400000US04001942700,04001942700,"Census Tract 9427, Apache County, Arizona",5511,26,9,0.471784,0.163310
3,1400000US04001944000,04001944000,"Census Tract 9440, Apache County, Arizona",5966,127,30,2.128729,0.502849
4,1400000US04001944100,04001944100,"Census Tract 9441, Apache County, Arizona",5968,94,141,1.575067,2.362601
5,1400000US04001944201,04001944201,"Census Tract 9442.01, Apache County, Arizona",4185,49,11,1.170848,0.262843
...,...,...,...,...,...,...,...,...
1761,1400000US04027012100,04027012100,"Census Tract 121, Yuma County, Arizona",825,439,1,53.212121,0.121212
1762,1400000US04027980003,04027980003,"Census Tract 9800.03, Yuma County, Arizona",0,0,0,NaN,NaN
1763,1400000US04027980004,04027980004,"Census Tract 9800.04, Yuma County, Arizona",0,0,0,NaN,NaN
1764,1400000US04027980005,04027980005,"Census Tract 9800.05, Yuma County, Arizona",87,66,0,75.862069,0.000000
1765,1400000US04027980006,04027980006,"Census Tract 9800.06, Yuma County, Arizona",3981,823,433,20.673198,10.876664

In [29]:
# export census table to csv

acs_2021_race.to_csv('./census_data/arizona_census_2021.csv', index=False)

## merge

In [30]:
# group by census tract to see mortgage count

arizona_tract_count_2021 = rm_arizona_all_2021.groupby('census_tract').agg({
    'lei':'count',
    'tract_population': 'max',
    'tract_minority_population_percent': 'min'
    }).sort_values(by='lei', ascending=False).reset_index()

# rename columns 

arizona_tract_count_2021.columns = ['census_tract', 'rm_no', 'tract_population', 'minority_pct']

# calculate mortgage count per 1000 people

arizona_tract_count_2021['rm_no_per1000'] = arizona_tract_count_2021['rm_no'] / arizona_tract_count_2021['tract_population'] * 1000 

# sort by count per 1000 people 

arizona_tract_count_2021 = arizona_tract_count_2021.sort_values(by='rm_no_per1000', ascending=False).reset_index(drop=True)

In [31]:
# merge the census tract info and reverse mortgage info

arizona_rm_census = pd.merge(
    arizona_tract_count_2021,
    acs_2021_race,
    how='left',
    on='census_tract',
    validate='1:1'
)

In [32]:
arizona_rm_census.head(20)

,census_tract,rm_no,tract_population,minority_pct,rm_no_per1000,geo_id,tract_name,population,hispanic_pp,black_pp,hispanic_pp_pct,black_pp_pct
0,04013980600,2,176,44.32,11.363636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04013817600,13,1240,54.11,10.483871,1400000US04013817600,"Census Tract 8176, Maricopa County, Arizona",4445.0,837.0,102.0,18.830146,2.294713
2,04013040516,32,3998,9.33,8.004002,1400000US04013040516,"Census Tract 405.16, Maricopa County, Arizona",8088.0,1301.0,50.0,16.085559,0.618200
3,04013040523,21,2777,7.71,7.562117,1400000US04013040523,"Census Tract 405.23, Maricopa County, Arizona",3122.0,55.0,113.0,1.761691,3.619475
4,04013040526,15,2043,7.34,7.342144,1400000US04013040526,"Census Tract 405.26, Maricopa County, Arizona",2228.0,44.0,9.0,1.974865,0.403950
5,04013040514,20,2867,3.98,6.975933,1400000US04013040514,"Census Tract 405.14, Maricopa County, Arizona",2947.0,65.0,15.0,2.205633,0.508992
6,04013817400,18,2818,3.48,6.387509,1400000US04013817400,"Census Tract 8174, Maricopa County, Arizona",2802.0,19.0,44.0,0.678087,1.570307
7,04013040524,9,1466,6.48,6.139154,1400000US04013040524,"Census Tract 405.24, Maricopa County, Arizona",1660.0,96.0,9.0,5.783133,0.542169
8,04025001402,16,2735,10.05,5.850091,1400000US04025001402,"Census Tract 14.02, Yavapai County, Arizona",3736.0,319.0,0.0,8.538544,0.000000
9,04013071702,16,3031,8.02,5.278786,1400000US04013071702,"Census Tract 717.02, Maricopa County, Arizona",3399.0,218.0,44.0,6.413651,1.294498
10,04013817500,14,2708,2.10,5.169867,1400000US04013817500,"Census Tract 8175, Maricopa County, Arizona",2779.0,75.0,38.0,2.698813,1.367398
11,04013817300,27,5300,4.13,5.094340,1400000US04013817300,"Census Tract 8173, Maricopa County, Arizona",5269.0,178.0,19.0,3.378250,0.360600
12,04013071802,18,3540,8.08,5.084746,1400000US04013071802,"Census Tract 718.02, Maricopa County, Arizona",3195.0,153.0,79.0,4.788732,2.472613
13,04025000607,31,6152,17.70,5.039012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,04013061018,23,4639,6.51,4.957965,1400000US04013061018,"Census Tract 610.18, Maricopa County, Arizona",5020.0,140.0,58.0,2.788845,1.155378
15,04013040506,26,5334,0.64,4.874391,1400000US04013040506,"Census Tract 405.06, Maricopa County, Arizona",5469.0,50.0,31.0,0.914244,0.566831
16,04013813700,12,2502,6.75,4.796163,1400000US04013813700,"Census Tract 8137, Maricopa County, Arizona",2448.0,27.0,8.0,1.102941,0.326797
17,04013071504,16,3549,2.76,4.508312,1400000US04013071504,"Census Tract 715.04, Maricopa County, Arizona",3497.0,0.0,38.0,0.000000,1.086646
18,04013071506,18,4075,9.87,4.417178,1400000US04013071506,"Census Tract 715.06, Maricopa County, Arizona",3956.0,124.0,77.0,3.134479,1.946411
19,04013816300,16,3641,12.25,4.394397,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
no_geoid = arizona_rm_census[arizona_rm_census['geo_id'].isna()]
no_geoid

,census_tract,rm_no,tract_population,minority_pct,rm_no_per1000,geo_id,tract_name,population,hispanic_pp,black_pp,hispanic_pp_pct,black_pp_pct
0,04013980600,2,176,44.32,11.363636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,04025000607,31,6152,17.70,5.039012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,04013816300,16,3641,12.25,4.394397,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,04015952800,26,5970,15.81,4.355109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,04025001200,26,6289,6.71,4.134203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1041,04003001800,1,8918,30.42,0.112133,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1042,04023966104,1,9531,84.61,0.104921,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1043,04013112509,1,9727,89.59,0.102807,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1044,04019004107,1,10247,37.38,0.097590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1045,04003000500,1,10469,51.25,0.095520,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
# export to csv 

sc_rm_census.to_csv('./reverse_mortgage_data/sc_tract_count_2021_0711.csv', index=False)