In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

## read reverse mortgage data

In [2]:
san_diego_rm_all = pd.read_csv('./reverse_mortgage_data/san_diego_rm_all.csv', dtype={
    'county_code': str,
    'census_tract': str
})
san_diego_rm_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8741 entries, 0 to 8740
Data columns (total 99 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   activity_year                             8741 non-null   int64
 1   lei                                       8741 non-null   object
 2   derived_msa-md                            8741 non-null   int64
 3   state_code                                8741 non-null   object
 4   county_code                               8741 non-null   object
 5   census_tract                              8741 non-null   object
 6   conforming_loan_limit                     8741 non-null   object
 7   derived_loan_product_type                 8741 non-null   object
 8   derived_dwelling_category                 8741 non-null   object
 9   derived_ethnicity                         8741 non-null   object
 10  derived_race                              8741 non-null   object
 11  derived_sex                               8741 non-null   object
 12  action_taken                              8741 non-null   int64
 13  purchaser_type                            8741 non-null   int64
 14  preapproval                               8741 non-null   int64
 15  loan_type                                 8741 non-null   int64
 16  loan_purpose                              8741 non-null   int64
 17  lien_status                               8741 non-null   int64
 18  reverse_mortgage                          8741 non-null   int64
 19  open-end_line_of_credit                   8741 non-null   int64
 20  business_or_commercial_purpose            8741 non-null   int64
 21  loan_amount                               8741 non-null   float64
 22  loan_to_value_ratio                       185 non-null    float64
 23  interest_rate                             6255 non-null   float64
 24  rate_spread                               0 non-null      float64
 25  hoepa_status                              8741 non-null   int64
 26  total_loan_costs                          0 non-null      float64
 27  total_points_and_fees                     0 non-null      float64
 28  origination_charges                       0 non-null      float64
 29  discount_points                           0 non-null      float64
 30  lender_credits                            0 non-null      float64
 31  loan_term                                 0 non-null      float64
 32  prepayment_penalty_term                   0 non-null      float64
 33  intro_rate_period                         4605 non-null   float64
 34  negative_amortization                     8741 non-null   int64
 35  interest_only_payment                     8741 non-null   int64
 36  balloon_payment                           8741 non-null   int64
 37  other_nonamortizing_features              8741 non-null   int64
 38  property_value                            6963 non-null   float64
 39  construction_method                       8741 non-null   int64
 40  occupancy_type                            8741 non-null   int64
 41  manufactured_home_secured_property_type   8741 non-null   int64
 42  manufactured_home_land_property_interest  8741 non-null   int64
 43  total_units                               8741 non-null   int64
 44  multifamily_affordable_units              0 non-null      float64
 45  income                                    7394 non-null   float64
 46  debt_to_income_ratio                      133 non-null    object
 47  applicant_credit_score_type               8741 non-null   int64
 48  co-applicant_credit_score_type            8741 non-null   int64
 49  applicant_ethnicity-1                     8741 non-null   float64
 50  applicant_ethnicity-2                     196 non-null    float64
 51  applicant_ethnicity-3                     3 non-null      float64
 52  applicant_ethnicity-4                     0 non-null      float64
 53  applicant_ethnicity-5                     0 non-null      float64
 54  co-applicant_ethnicity-1                  8741 non-null   float64
 55  co-applicant_ethnicity-2                  86 non-null     float64
 56  co-applicant_ethnicity-3                  1 non-null      float64
 57  co-applicant_ethnicity-4                  0 non-null      float64
 58  co-applicant_ethnicity-5                  0 non-null      float64
 59  applicant_ethnicity_observed              8741 non-null   int64
 60  co-applicant_ethnicity_observed           8741 non-null   int64
 61  applicant_race-1                          8740 non-null   float64
 62  applicant_race-2                          142 non-null    float64
 63  applicant_race-3                          16 non-null     float64
 64  applicant_race-4                          2 non-null      float64
 65  applicant_race-5                          0 non-null      float64
 66  co-applicant_race-1                       8741 non-null   float64
 67  co-applicant_race-2                       57 non-null     float64
 68  co-applicant_race-3                       6 non-null      float64
 69  co-applicant_race-4                       0 non-null      float64
 70  co-applicant_race-5                       0 non-null      float64
 71  applicant_race_observed                   8741 non-null   int64
 72  co-applicant_race_observed                8741 non-null   int64
 73  applicant_sex                             8741 non-null   int64
 74  co-applicant_sex                          8741 non-null   int64
 75  applicant_sex_observed                    8741 non-null   int64
 76  co-applicant_sex_observed                 8741 non-null   int64
 77  applicant_age                             8741 non-null   object
 78  co-applicant_age                          8741 non-null   object
 79  applicant_age_above_62                    6705 non-null   object
 80  co-applicant_age_above_62                 2588 non-null   object
 81  submission_of_application                 8741 non-null   int64
 82  initially_payable_to_institution          8741 non-null   int64
 83  aus-1                                     8741 non-null   int64
 84  aus-2                                     0 non-null      float64
 85  aus-3                                     0 non-null      float64
 86  aus-4                                     0 non-null      float64
 87  aus-5                                     0 non-null      float64
 88  denial_reason-1                           8741 non-null   int64
 89  denial_reason-2                           65 non-null     float64
 90  denial_reason-3                           5 non-null      float64
 91  denial_reason-4                           1 non-null      float64
 92  tract_population                          8741 non-null   int64
 93  tract_minority_population_percent         8741 non-null   float64
 94  ffiec_msa_md_median_family_income         8741 non-null   int64
 95  tract_to_msa_income_percentage            8741 non-null   int64
 96  tract_owner_occupied_units                8741 non-null   int64
 97  tract_one_to_four_family_homes            8741 non-null   int64
 98  tract_median_age_of_housing_units         8741 non-null   int64
dtypes: float64(43), int64(41), object(15)
memory usage: 6.6+ MB

## read census data and filter to county

In [3]:
census_all = pd.read_csv('./census_data/ACS2019_filtered0623.csv', dtype={
    'census_tract': str,
    'county_code': str,
    'census_tract_np': str,
    'census_tract_period': str
})
census_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Columns: 208 entries, census_tract to Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female
dtypes: float64(3), int64(105), object(100)
memory usage: 7.1+ MB

In [4]:
census_san_diego = census_all[census_all['county_code'] == '06073'].copy()

In [5]:
census_san_diego.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 628 entries, 3877 to 4504
Columns: 208 entries, census_tract to Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female
dtypes: float64(3), int64(105), object(100)
memory usage: 1.0+ MB

## merge lender list

In [6]:
# read lender list

lender_list_2018 = pd.read_csv('./raw_data/lei_agency_name_2018.csv')

In [7]:
lender_list_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5735 entries, 0 to 5734
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   lei                  5735 non-null   object
 1   activity_year        5735 non-null   int64
 2   calendar_quarter     5735 non-null   int64
 3   tax_id               5735 non-null   object
 4   agency_code          5735 non-null   int64
 5   respondent_name      5735 non-null   object
 6   respondent_state     5735 non-null   object
 7   respondent_city      5735 non-null   object
 8   respondent_zip_code  5735 non-null   object
 9   lar_count            5735 non-null   int64
dtypes: int64(4), object(6)
memory usage: 448.2+ KB

In [8]:
# merge by lei

san_diego_rm_all

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open-end_line_of_credit,business_or_commercial_purpose,loan_amount,loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co-applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity-2,applicant_ethnicity-3,applicant_ethnicity-4,applicant_ethnicity-5,co-applicant_ethnicity-1,co-applicant_ethnicity-2,co-applicant_ethnicity-3,co-applicant_ethnicity-4,co-applicant_ethnicity-5,applicant_ethnicity_observed,co-applicant_ethnicity_observed,applicant_race-1,applicant_race-2,applicant_race-3,applicant_race-4,applicant_race-5,co-applicant_race-1,co-applicant_race-2,co-applicant_race-3,co-applicant_race-4,co-applicant_race-5,applicant_race_observed,co-applicant_race_observed,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus-1,aus-2,aus-3,aus-4,aus-5,denial_reason-1,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073015301,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Female,5,0,2,2,31,1,1,2,2,285000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,1,1,3,5,1,NaN,36.0,NaN,9,9,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,2,5,3,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3126,43.12,81800,65,413,705,57
1,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073019808,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Female,4,0,2,2,31,1,1,1,2,355000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,48.0,NaN,9,9,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,2,5,3,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4853,29.43,81800,113,1705,1923,27
2,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073000300,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Female,2,0,2,2,31,1,1,1,2,325000.0,NaN,4.598,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,575000.0,1,1,3,5,1,NaN,25.0,NaN,9,10,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,2,5,3,4,65-74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4875,26.11,81800,109,775,914,41
3,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073008355,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,4,0,2,2,31,1,1,1,2,345000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,0.0,NaN,9,9,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,3,5,3,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3857,80.22,81800,134,692,989,36
4,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073010001,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,1,6,2,2,31,1,1,1,2,315000.0,NaN,4.481,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,445000.0,1,1,3,5,1,NaN,9.0,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3724,87.00,81800,94,880,991,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8736,2021,B4TYDEB6GKMZO031MB27,41740,CA,06073,06073003001,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,395000.0,NaN,2.910,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4428,95.37,95100,83,833,1273,54
8737,2021,B4TYDEB6GKMZO031MB27,41740,CA,06073,06073003204,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,345000.0,NaN,6.520,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3633,70.36,95100,131,709,1033,48
8738,2021,B4TYDEB6GKMZO031MB27,41740,CA,06073,06073019203,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,315000.0,NaN,3.125,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,2623,30.92,95100,115,697,964,36
8739,2021,B4TYDEB6GKMZO031MB27,41740,CA,06073,06073008507,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,455000.0,NaN,2.515,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,8424,52.22,95100,94,1527,1791,46
8740,2021,B4TYDEB6GKMZO031MB27,41740,CA,06073,06073013203,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,265000.0,NaN,2.280,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,7018,93.97,95100,33,412,803,49

In [9]:
lender_list_2018

,lei,activity_year,calendar_quarter,tax_id,agency_code,respondent_name,respondent_state,respondent_city,respondent_zip_code,lar_count
0,213800QUAI2VH5YM6310,2018,4,05-0402708,7,"Embrace Home Loans, Inc.",RI,Middletown,02842,38810
1,5493001SXWZ4OFP8Z903,2018,4,74-2853239,7,DHI Mortgage Company Limited,TX,Austin,78750,45691
2,549300YHR41F57LS0R28,2018,4,39-0273630,3,Farmers and Merchants Union Bank,WI,Columbus,53925,131
3,549300SX6THT96LFD245,2018,4,26-1866970,3,Oakworth Capital Bank,AL,Birmingham,35209,29
4,2549000UUHZDEKIZ2Z84,2018,4,34-0144365,1,The Citizens National Bank,OH,Woodsfield,43793,97
...,...,...,...,...,...,...,...,...,...,...
5730,Z867SNMO7WGY8TTGQG78,2018,4,55-0744997,3,SUMMIT COMMUNITY BANK,WV,MOOREFIELD,26836,1035
5731,ZF85QS7OXKPBG52R7N18,2018,4,39-1941673,9,Associated Bank NA,WI,Green Bay,54301,20022
5732,ZXMJHJK466PBZTM5F379,2018,4,59-3244348,9,Raymond James Bank National Association,FL,SAINT PETERSBURG,33716,2067
5733,ZXZDWBXF4U47HEP2EO46,2018,4,33-0244449,2,Silvergate Bank,CA,La Jolla,92037,298
5734,SS1TRMSN6BRNMOREEV51,2018,4,38-2734984,9,Flagstar Bank,MI,Troy,48098,149977

In [10]:
san_diego_rm_full = pd.merge(
    san_diego_rm_all,
    lender_list_2018,
    on='lei',
    how='left',
    validate='m:1'
)

In [11]:
san_diego_rm_full.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8741 entries, 0 to 8740
Data columns (total 108 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           8741 non-null   int64
 1    lei                                       8741 non-null   object
 2    derived_msa-md                            8741 non-null   int64
 3    state_code                                8741 non-null   object
 4    county_code                               8741 non-null   object
 5    census_tract                              8741 non-null   object
 6    conforming_loan_limit                     8741 non-null   object
 7    derived_loan_product_type                 8741 non-null   object
 8    derived_dwelling_category                 8741 non-null   object
 9    derived_ethnicity                         8741 non-null   object
 10   derived_race                              8741 non-null   object
 11   derived_sex                               8741 non-null   object
 12   action_taken                              8741 non-null   int64
 13   purchaser_type                            8741 non-null   int64
 14   preapproval                               8741 non-null   int64
 15   loan_type                                 8741 non-null   int64
 16   loan_purpose                              8741 non-null   int64
 17   lien_status                               8741 non-null   int64
 18   reverse_mortgage                          8741 non-null   int64
 19   open-end_line_of_credit                   8741 non-null   int64
 20   business_or_commercial_purpose            8741 non-null   int64
 21   loan_amount                               8741 non-null   float64
 22   loan_to_value_ratio                       185 non-null    float64
 23   interest_rate                             6255 non-null   float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              8741 non-null   int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         4605 non-null   float64
 34   negative_amortization                     8741 non-null   int64
 35   interest_only_payment                     8741 non-null   int64
 36   balloon_payment                           8741 non-null   int64
 37   other_nonamortizing_features              8741 non-null   int64
 38   property_value                            6963 non-null   float64
 39   construction_method                       8741 non-null   int64
 40   occupancy_type                            8741 non-null   int64
 41   manufactured_home_secured_property_type   8741 non-null   int64
 42   manufactured_home_land_property_interest  8741 non-null   int64
 43   total_units                               8741 non-null   int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    7394 non-null   float64
 46   debt_to_income_ratio                      133 non-null    object
 47   applicant_credit_score_type               8741 non-null   int64
 48   co-applicant_credit_score_type            8741 non-null   int64
 49   applicant_ethnicity-1                     8741 non-null   float64
 50   applicant_ethnicity-2                     196 non-null    float64
 51   applicant_ethnicity-3                     3 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  8741 non-null   float64
 55   co-applicant_ethnicity-2                  86 non-null     float64
 56   co-applicant_ethnicity-3                  1 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              8741 non-null   int64
 60   co-applicant_ethnicity_observed           8741 non-null   int64
 61   applicant_race-1                          8740 non-null   float64
 62   applicant_race-2                          142 non-null    float64
 63   applicant_race-3                          16 non-null     float64
 64   applicant_race-4                          2 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       8741 non-null   float64
 67   co-applicant_race-2                       57 non-null     float64
 68   co-applicant_race-3                       6 non-null      float64
 69   co-applicant_race-4                       0 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   8741 non-null   int64
 72   co-applicant_race_observed                8741 non-null   int64
 73   applicant_sex                             8741 non-null   int64
 74   co-applicant_sex                          8741 non-null   int64
 75   applicant_sex_observed                    8741 non-null   int64
 76   co-applicant_sex_observed                 8741 non-null   int64
 77   applicant_age                             8741 non-null   object
 78   co-applicant_age                          8741 non-null   object
 79   applicant_age_above_62                    6705 non-null   object
 80   co-applicant_age_above_62                 2588 non-null   object
 81   submission_of_application                 8741 non-null   int64
 82   initially_payable_to_institution          8741 non-null   int64
 83   aus-1                                     8741 non-null   int64
 84   aus-2                                     0 non-null      float64
 85   aus-3                                     0 non-null      float64
 86   aus-4                                     0 non-null      float64
 87   aus-5                                     0 non-null      float64
 88   denial_reason-1                           8741 non-null   int64
 89   denial_reason-2                           65 non-null     float64
 90   denial_reason-3                           5 non-null      float64
 91   denial_reason-4                           1 non-null      float64
 92   tract_population                          8741 non-null   int64
 93   tract_minority_population_percent         8741 non-null   float64
 94   ffiec_msa_md_median_family_income         8741 non-null   int64
 95   tract_to_msa_income_percentage            8741 non-null   int64
 96   tract_owner_occupied_units                8741 non-null   int64
 97   tract_one_to_four_family_homes            8741 non-null   int64
 98   tract_median_age_of_housing_units         8741 non-null   int64
 99   activity_year_y                           8741 non-null   int64
 100  calendar_quarter                          8741 non-null   int64
 101  tax_id                                    8741 non-null   object
 102  agency_code                               8741 non-null   int64
 103  respondent_name                           8741 non-null   object
 104  respondent_state                          8741 non-null   object
 105  respondent_city                           8741 non-null   object
 106  respondent_zip_code                       8741 non-null   object
 107  lar_count                                 8741 non-null   int64
dtypes: float64(43), int64(45), object(20)
memory usage: 7.3+ MB

In [12]:
san_diego_rm_name = san_diego_rm_full.drop(columns= ['activity_year_y', 'calendar_quarter', 'lar_count']).copy()

In [13]:
san_diego_rm_name.head()

,activity_year_x,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open-end_line_of_credit,business_or_commercial_purpose,loan_amount,loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co-applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity-2,applicant_ethnicity-3,applicant_ethnicity-4,applicant_ethnicity-5,co-applicant_ethnicity-1,co-applicant_ethnicity-2,co-applicant_ethnicity-3,co-applicant_ethnicity-4,co-applicant_ethnicity-5,applicant_ethnicity_observed,co-applicant_ethnicity_observed,applicant_race-1,applicant_race-2,applicant_race-3,applicant_race-4,applicant_race-5,co-applicant_race-1,co-applicant_race-2,co-applicant_race-3,co-applicant_race-4,co-applicant_race-5,applicant_race_observed,co-applicant_race_observed,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus-1,aus-2,aus-3,aus-4,aus-5,denial_reason-1,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units,tax_id,agency_code,respondent_name,respondent_state,respondent_city,respondent_zip_code
0,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073015301,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Female,5,0,2,2,31,1,1,2,2,285000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,1,1,3,5,1,NaN,36.0,NaN,9,9,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,2,5,3,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3126,43.12,81800,65,413,705,57,11-3469077,7,Nationwide Equities Corporation,NJ,Mahwah,07495
1,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073019808,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Female,4,0,2,2,31,1,1,1,2,355000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,48.0,NaN,9,9,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,2,5,3,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4853,29.43,81800,113,1705,1923,27,11-3469077,7,Nationwide Equities Corporation,NJ,Mahwah,07495
2,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073000300,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Female,2,0,2,2,31,1,1,1,2,325000.0,NaN,4.598,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,575000.0,1,1,3,5,1,NaN,25.0,NaN,9,10,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,2,5,3,4,65-74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4875,26.11,81800,109,775,914,41,11-3469077,7,Nationwide Equities Corporation,NJ,Mahwah,07495
3,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073008355,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,4,0,2,2,31,1,1,1,2,345000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,0.0,NaN,9,9,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,3,5,3,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3857,80.22,81800,134,692,989,36,11-3469077,7,Nationwide Equities Corporation,NJ,Mahwah,07495
4,2018,549300WH9FMXOC63ZV77,41740,CA,06073,06073010001,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,1,6,2,2,31,1,1,1,2,315000.0,NaN,4.481,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,445000.0,1,1,3,5,1,NaN,9.0,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3724,87.00,81800,94,880,991,39,11-3469077,7,Nationwide Equities Corporation,NJ,Mahwah,07495

In [14]:
san_diego_rm_name.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8741 entries, 0 to 8740
Data columns (total 105 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           8741 non-null   int64
 1    lei                                       8741 non-null   object
 2    derived_msa-md                            8741 non-null   int64
 3    state_code                                8741 non-null   object
 4    county_code                               8741 non-null   object
 5    census_tract                              8741 non-null   object
 6    conforming_loan_limit                     8741 non-null   object
 7    derived_loan_product_type                 8741 non-null   object
 8    derived_dwelling_category                 8741 non-null   object
 9    derived_ethnicity                         8741 non-null   object
 10   derived_race                              8741 non-null   object
 11   derived_sex                               8741 non-null   object
 12   action_taken                              8741 non-null   int64
 13   purchaser_type                            8741 non-null   int64
 14   preapproval                               8741 non-null   int64
 15   loan_type                                 8741 non-null   int64
 16   loan_purpose                              8741 non-null   int64
 17   lien_status                               8741 non-null   int64
 18   reverse_mortgage                          8741 non-null   int64
 19   open-end_line_of_credit                   8741 non-null   int64
 20   business_or_commercial_purpose            8741 non-null   int64
 21   loan_amount                               8741 non-null   float64
 22   loan_to_value_ratio                       185 non-null    float64
 23   interest_rate                             6255 non-null   float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              8741 non-null   int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         4605 non-null   float64
 34   negative_amortization                     8741 non-null   int64
 35   interest_only_payment                     8741 non-null   int64
 36   balloon_payment                           8741 non-null   int64
 37   other_nonamortizing_features              8741 non-null   int64
 38   property_value                            6963 non-null   float64
 39   construction_method                       8741 non-null   int64
 40   occupancy_type                            8741 non-null   int64
 41   manufactured_home_secured_property_type   8741 non-null   int64
 42   manufactured_home_land_property_interest  8741 non-null   int64
 43   total_units                               8741 non-null   int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    7394 non-null   float64
 46   debt_to_income_ratio                      133 non-null    object
 47   applicant_credit_score_type               8741 non-null   int64
 48   co-applicant_credit_score_type            8741 non-null   int64
 49   applicant_ethnicity-1                     8741 non-null   float64
 50   applicant_ethnicity-2                     196 non-null    float64
 51   applicant_ethnicity-3                     3 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  8741 non-null   float64
 55   co-applicant_ethnicity-2                  86 non-null     float64
 56   co-applicant_ethnicity-3                  1 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              8741 non-null   int64
 60   co-applicant_ethnicity_observed           8741 non-null   int64
 61   applicant_race-1                          8740 non-null   float64
 62   applicant_race-2                          142 non-null    float64
 63   applicant_race-3                          16 non-null     float64
 64   applicant_race-4                          2 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       8741 non-null   float64
 67   co-applicant_race-2                       57 non-null     float64
 68   co-applicant_race-3                       6 non-null      float64
 69   co-applicant_race-4                       0 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   8741 non-null   int64
 72   co-applicant_race_observed                8741 non-null   int64
 73   applicant_sex                             8741 non-null   int64
 74   co-applicant_sex                          8741 non-null   int64
 75   applicant_sex_observed                    8741 non-null   int64
 76   co-applicant_sex_observed                 8741 non-null   int64
 77   applicant_age                             8741 non-null   object
 78   co-applicant_age                          8741 non-null   object
 79   applicant_age_above_62                    6705 non-null   object
 80   co-applicant_age_above_62                 2588 non-null   object
 81   submission_of_application                 8741 non-null   int64
 82   initially_payable_to_institution          8741 non-null   int64
 83   aus-1                                     8741 non-null   int64
 84   aus-2                                     0 non-null      float64
 85   aus-3                                     0 non-null      float64
 86   aus-4                                     0 non-null      float64
 87   aus-5                                     0 non-null      float64
 88   denial_reason-1                           8741 non-null   int64
 89   denial_reason-2                           65 non-null     float64
 90   denial_reason-3                           5 non-null      float64
 91   denial_reason-4                           1 non-null      float64
 92   tract_population                          8741 non-null   int64
 93   tract_minority_population_percent         8741 non-null   float64
 94   ffiec_msa_md_median_family_income         8741 non-null   int64
 95   tract_to_msa_income_percentage            8741 non-null   int64
 96   tract_owner_occupied_units                8741 non-null   int64
 97   tract_one_to_four_family_homes            8741 non-null   int64
 98   tract_median_age_of_housing_units         8741 non-null   int64
 99   tax_id                                    8741 non-null   object
 100  agency_code                               8741 non-null   int64
 101  respondent_name                           8741 non-null   object
 102  respondent_state                          8741 non-null   object
 103  respondent_city                           8741 non-null   object
 104  respondent_zip_code                       8741 non-null   object
dtypes: float64(43), int64(42), object(20)
memory usage: 7.1+ MB

## group by census tracts

In [15]:
# filter by action_taken = 1

san_diego_rm_originated = san_diego_rm_name[san_diego_rm_name['action_taken'] == 1]

In [16]:
san_diego_rm_originated.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5541 entries, 4 to 8731
Data columns (total 105 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           5541 non-null   int64
 1    lei                                       5541 non-null   object
 2    derived_msa-md                            5541 non-null   int64
 3    state_code                                5541 non-null   object
 4    county_code                               5541 non-null   object
 5    census_tract                              5541 non-null   object
 6    conforming_loan_limit                     5541 non-null   object
 7    derived_loan_product_type                 5541 non-null   object
 8    derived_dwelling_category                 5541 non-null   object
 9    derived_ethnicity                         5541 non-null   object
 10   derived_race                              5541 non-null   object
 11   derived_sex                               5541 non-null   object
 12   action_taken                              5541 non-null   int64
 13   purchaser_type                            5541 non-null   int64
 14   preapproval                               5541 non-null   int64
 15   loan_type                                 5541 non-null   int64
 16   loan_purpose                              5541 non-null   int64
 17   lien_status                               5541 non-null   int64
 18   reverse_mortgage                          5541 non-null   int64
 19   open-end_line_of_credit                   5541 non-null   int64
 20   business_or_commercial_purpose            5541 non-null   int64
 21   loan_amount                               5541 non-null   float64
 22   loan_to_value_ratio                       155 non-null    float64
 23   interest_rate                             4755 non-null   float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              5541 non-null   int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         2640 non-null   float64
 34   negative_amortization                     5541 non-null   int64
 35   interest_only_payment                     5541 non-null   int64
 36   balloon_payment                           5541 non-null   int64
 37   other_nonamortizing_features              5541 non-null   int64
 38   property_value                            4796 non-null   float64
 39   construction_method                       5541 non-null   int64
 40   occupancy_type                            5541 non-null   int64
 41   manufactured_home_secured_property_type   5541 non-null   int64
 42   manufactured_home_land_property_interest  5541 non-null   int64
 43   total_units                               5541 non-null   int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    5502 non-null   float64
 46   debt_to_income_ratio                      105 non-null    object
 47   applicant_credit_score_type               5541 non-null   int64
 48   co-applicant_credit_score_type            5541 non-null   int64
 49   applicant_ethnicity-1                     5541 non-null   float64
 50   applicant_ethnicity-2                     131 non-null    float64
 51   applicant_ethnicity-3                     3 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  5541 non-null   float64
 55   co-applicant_ethnicity-2                  58 non-null     float64
 56   co-applicant_ethnicity-3                  0 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              5541 non-null   int64
 60   co-applicant_ethnicity_observed           5541 non-null   int64
 61   applicant_race-1                          5540 non-null   float64
 62   applicant_race-2                          97 non-null     float64
 63   applicant_race-3                          11 non-null     float64
 64   applicant_race-4                          2 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       5541 non-null   float64
 67   co-applicant_race-2                       38 non-null     float64
 68   co-applicant_race-3                       3 non-null      float64
 69   co-applicant_race-4                       0 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   5541 non-null   int64
 72   co-applicant_race_observed                5541 non-null   int64
 73   applicant_sex                             5541 non-null   int64
 74   co-applicant_sex                          5541 non-null   int64
 75   applicant_sex_observed                    5541 non-null   int64
 76   co-applicant_sex_observed                 5541 non-null   int64
 77   applicant_age                             5541 non-null   object
 78   co-applicant_age                          5541 non-null   object
 79   applicant_age_above_62                    4784 non-null   object
 80   co-applicant_age_above_62                 1878 non-null   object
 81   submission_of_application                 5541 non-null   int64
 82   initially_payable_to_institution          5541 non-null   int64
 83   aus-1                                     5541 non-null   int64
 84   aus-2                                     0 non-null      float64
 85   aus-3                                     0 non-null      float64
 86   aus-4                                     0 non-null      float64
 87   aus-5                                     0 non-null      float64
 88   denial_reason-1                           5541 non-null   int64
 89   denial_reason-2                           0 non-null      float64
 90   denial_reason-3                           0 non-null      float64
 91   denial_reason-4                           0 non-null      float64
 92   tract_population                          5541 non-null   int64
 93   tract_minority_population_percent         5541 non-null   float64
 94   ffiec_msa_md_median_family_income         5541 non-null   int64
 95   tract_to_msa_income_percentage            5541 non-null   int64
 96   tract_owner_occupied_units                5541 non-null   int64
 97   tract_one_to_four_family_homes            5541 non-null   int64
 98   tract_median_age_of_housing_units         5541 non-null   int64
 99   tax_id                                    5541 non-null   object
 100  agency_code                               5541 non-null   int64
 101  respondent_name                           5541 non-null   object
 102  respondent_state                          5541 non-null   object
 103  respondent_city                           5541 non-null   object
 104  respondent_zip_code                       5541 non-null   object
dtypes: float64(43), int64(42), object(20)
memory usage: 4.5+ MB

In [17]:
# group by census_tract

san_diego_census_counts = san_diego_rm_originated.groupby(['census_tract']).count()

In [18]:
san_diego_census_counts = san_diego_census_counts[['lei']].copy()

In [19]:
san_diego_census_counts = san_diego_census_counts.reset_index()

In [20]:
san_diego_census_counts = san_diego_census_counts.sort_values(by=['lei'], ascending=False).copy()
san_diego_census_counts.rename(columns={'lei': 'rm_no'}, inplace=True)

In [21]:
san_diego_census_counts = san_diego_census_counts.reset_index(drop=True)

In [22]:
san_diego_census_counts

    census_tract  rm_no
0    06073017019     56
1    06073019808     55
2    06073018802     46
3    06073018512     45
4    06073019806     40
..           ...    ...
568  06073016202      1
569  06073006500      1
570  06073010012      1
571  06073019903      1
572  06073020209      1

[573 rows x 2 columns]

## merge with census data

In [23]:
census_san_diego

,census_tract,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_population,62yr_pp_pct,median_age,hispanic_population,non_hispanic_population,non_hispanic_white_population,non_hispanic_black_population,non_hispanic_asian_population,other_races_population,hispanic_pp_pct,non_hispanic_pp_pct,non_hispanic_white_pp_pct,non_hispanic_black_pp_pct,non_hispanic_asian_pp_pct,other_races_pp_pct,Unnamed: 22,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Unnamed: 27,asian_1_population,black_1_population,Unnamed: 30,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!SEX AND AGE!!Total population!!Median age (years),Estimate!!SEX AND AGE!!Total population!!Under 18 years,Estimate!!SEX AND AGE!!Total population!!16 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over,Estimate!!SEX AND AGE!!Total population!!21 years and over,Estimate!!SEX AND AGE!!Total population!!62 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races.1,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,Percent!!SEX AND AGE!!Total population!!20 to 24 years,Percent!!SEX AND AGE!!Total population!!25 to 34 years,Percent!!SEX AND AGE!!Total population!!35 to 44 years,Percent!!SEX AND AGE!!Total population!!45 to 54 years,Percent!!SEX AND AGE!!Total population!!55 to 59 years,Percent!!SEX AND AGE!!Total population!!60 to 64 years,Percent!!SEX AND AGE!!Total population!!65 to 74 years,Percent!!SEX AND AGE!!Total population!!75 to 84 years,Percent!!SEX AND AGE!!Total population!!85 years and over,Percent!!SEX AND AGE!!Total population!!Median age (years),Percent!!SEX AND AGE!!Total population!!Under 18 years,Percent!!SEX AND AGE!!Total population!!16 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over,Percent!!SEX AND AGE!!Total population!!21 years and over,Percent!!SEX AND AGE!!Total population!!62 years and over,Percent!!SEX AND AGE!!Total population!!65 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over.1,Percent!!SEX AND AGE!!Total population!!18 years and over!!Male,Percent!!SEX AND AGE!!Total population!!18 years and over!!Female,Percent!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!65 years and over.1,Percent!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent!!SEX AND AGE!!Total population!!65 years and over!!Female,Percent!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent!!RACE!!Total population,Percent!!RACE!!Total population!!One race,Percent!!RACE!!Total population!!Two or more races,Percent!!RACE!!Total population!!One race.1,Percent!!RACE!!Total population!!One race!!White,Percent!!RACE!!Total population!!One race!!Black or African American,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Percent!!RACE!!Total population!!One race!!Asian,Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian,Percent!!RACE!!Total population!!One race!!Asian!!Chinese,Percent!!RACE!!Total population!!One race!!Asian!!Filipino,Percent!!RACE!!Total population!!One race!!Asian!!Japanese,Percent!!RACE!!Total population!!One race!!Asian!!Korean,Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese,Percent!!RACE!!Total population!!One race!!Asian!!Other Asian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Some other race,Percent!!RACE!!Total population!!Two or more races.1,Percent!!RACE!!Total population!!Two or more races!!White and Black or African American,Percent!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Percent!!RACE!!Total population!!Two or more races!!White and Asian,Percent!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population,Percent!!Race alone or in combination with one or more other races!!Total population!!White,Percent!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Percent!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population!!Asian,Percent!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Percent!!Race alone or in combination with one or more other races!!Total population!!Some other race,Percent!!HISPANIC OR LATINO AND RACE!!Total population,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
3877,06073000100,06073,San Diego County,CA,100,1,3093,1195,38.6%,54.2,489,2604,2389,0,112,103,15.8%,84.2%,77.2%,0.0%,3.6%,3.3%,NaN,0,0,0,103,NaN,121,0,NaN,1420,1673,84.9,179,164,92,127,68,188,408,390,195,250,614,294,124,54.2,543,2622,2550,2521,1195,1032,2550,1128,1422,79.3,1032,438,594,73.7,3093,2982,111,2982,2808,0,0,0,0,0,0,121,0,55,17,31,9,9,0,14,0,0,0,14,39,111,0,16,81,0,3093,2919,0,30,216,14,39,3093,489,278,9,19,183,2604,2389,0,0,112,0,0,103,0,103,1383,2447,1099,1348,3093,45.9,54.1,(X),5.8,5.3,3,4.1,2.2,6.1,13.2,12.6,6.3,8.1,19.9,9.5,4,(X),17.6,84.8,82.4,81.5,38.6,33.4,2550,44.2,55.8,(X),1032,42.4,57.6,(X),3093,96.4,3.6,96.4,90.8,0,0,0,0,0,0,3.9,0,1.8,0.5,1,0.3,0.3,0,0.5,0,0,0,0.5,1.3,3.6,0,0.5,2.6,0,3093,94.4,0,1,7,0.5,1.3,3093,15.8,9,0.3,0.6,5.9,84.2,77.2,0,0,3.6,0,0,3.3,0,3.3,(X),2447,44.9,55.1
3878,06073000201,06073,San Diego County,CA,201,2.01,1891,649,34.3%,49.4,140,1751,1569,10,75,97,7.4%,92.6%,83.0%,0.5%,4.0%,5.1%,NaN,11,0,0,86,NaN,75,10,NaN,784,1107,70.8,77,70,62,15,61,319,238,256,116,96,301,138,142,49.4,224,1673,1667,1656,649,581,1667,645,1022,63.1,581,195,386,50.5,1891,1790,101,1790,1659,10,11,0,0,0,0,75,0,48,0,0,0,0,27,0,0,0,0,0,35,101,18,27,41,0,1891,1760,43,38,116,0,50,1891,140,95,0,11,34,1751,1569,10,11,75,0,0,86,0,86,1147,1648,645,1003,1891,41.5,58.5,(X),4.1,3.7,3.3,0.8,3.2,16.9,12.6,13.5,6.1,5.1,15.9,7.3,7.5,(X),11.8,88.5,88.2,87.6,34.3,30.7,1667,38.7,61.3,(X),581,33.6,66.4,(X),1891,94.7,5.3,94.7,87.7,0.5,0.6,0,0,0,0,4,0,2.5,0,0,0,0,1.4,0,0,0,0,0,1.9,5.3,1,1.4,2.2,0,1891,93.1,2.3,2,6.1,0,2.6,1891,7.4,5,0,0.6,1.8,92.6,83,0.5,0.6,4,0,0,4.5,0,4.5,(X),1648,39.1,60.9
3879,06073000202,06073,San Diego County,CA,202,2.02,4542,880,19.4%,41.2,616,3926,3390,4,379,153,13.6%,86.4%,74.6%,0.1%,8.3%,3.4%,NaN,0,3,0,150,NaN,379,4,NaN,1997,2545,78.5,97,108,169,458,55,981,858,704,203,226,409,214,60,41.2,648,4115,3894,3710,880,683,3894,1728,2166,79.8,683,264,419,63,4542,4349,193,4349,3895,4,0,0,0,0,0,379,94,101,175,0,0,0,9,3,0,3,0,0,68,193,27,0,99,0,4542,4056,31,0,529,54,84,4542,616,372,36,36,172,3926,3390,4,0,379,3,0,150,0,150,2472,3517,1579,1938,4542,44,56,(X),2.1,2.4,3.7,10.1,1.2,21.6,18.9,15.5,4.5,5,9,4.7,1.3,(X),14.3,90.6,85.7,81.7,19.4,15,3894,44.4,55.6,(X),683,38.7,61.3,(X),4542,95.8,4.2,95.8,85.8,0.1,0,0,0,0,0,8.3,2.1,2.2,3.9,0,0,0,0.2,0.1,0,0.1,0,0,1.5,4.2,0.6,0,2.2,0,4542,89.3,0.7,0,11.6,1.2,1.8,4542,13.6,8.2,0.8,0.8,3.8,86.4,74.6,0.1,0,8.3,0.1,0,3.3,0,3.3,(X),3517,44.9,55.1
3880,06073000300,06073,San Diego County,CA,300,3,5239,1374,26.2%,43.8,871,4368,3820,266,146,136,16.6%,83.4%,72.9%,5.1%,2.8%,2.6%,NaN,0,7,0,129,NaN,168,322,NaN,2703,2536,106.6,200,16,0,30,479,1315,750,564,362,368,608,311,236,43.8,216,5023,5023,4963,1374,1155,5023,2622,2401,109.2,1155,614,541,113.5,5239,5044,195,5044,4466,322,0,0,0,0,0,168,58,41,49,0,0,0,20,7,0,0,7,0,81,195,67,0,55,0,5239,4635,389,7,274,26,128,5239,871,757,43,0,71,4368,3820,266,0,146,7,0,129,0,129,3209,4914,2592,2322,5239,51.6,48.4,(X),3.8,0.3,0,0.6,9.1,25.1,14.3,10.8,6.9,7,11.6,5.9,4.5,(X),4.1,95.9,95.9,94.7,26.2,22,5023,52.2,47.8,(X),1155,53.2,46.8,(X),5239,96.3,3.7,96.3,85.2,6.1,0,0,0,0,0,3.2,1.1,0.8,0.9,0,0,0,0.4,0.1,0,0,0.1,0,1.5,3.7,1.3,0,1,0,5239,88.5,7.4,0.1,5.2,0.5,2.4,5239,16.6,14.4,0.8,0,1.4,83.4,72.9,5.1,0,2.8,0.1,0,2.5,0,2.5,(X),4914,52.7,47.3
3881,06073000400,06073,San Diego County,CA,400,4,3801,373,9.8%,34.4,884,2917,2148,228,430,111,23.3%,76.7%,56.5%,6.0%,11.3%,2.9%,NaN,0,0,18,93,NaN,430,228,NaN,2057,1744,117.9,116,28,43,263,267,1234,804,507,130,45,242,72,50,34.4,321,3552,3480,3296,373,364,3480,1893,1587,119.3,364,158,206,76.7,3801,3664,137,3664,2805,228,12,0,0,0,0,430,0,116,90,4,129,12,79,0,0,0,0,0,189,137,0,48,32,28,3801,2914,285,106,462,11,189,3801,884,701,11,0,172,2917,2148,228,0,430,0,18,93,0,93,2433,3198,1729,1469,3801,54.1,45.9,(X),3.1,0.7,1.1,6.9,7,32.5,21.2,13.3,3.4,1.2,6.4,1.9,1.3,(X),8.4,93.4,91.6,86.7,9.8,9.6,3480,54.4,45.6,(X),364,43.4,56.6,(X),3801,96.4,3.6,96.4,73.8,6,0.3,0,0,0,0,11.3,0,3.1,2.4,0.1,3.4,0.3,2.1,0,0,0,0,0,5,3.6,0,1.3,0.8,0.7,3801,76.7,7.5,2.8,12.2,0.3,5,3801,23.3,18.4,0.3,0,4.5,76.7,56.5,6,0,11.3,0,0.5,2.4,0,2.4,(X),3198,54.1,45.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [24]:
san_diego_census_rm = pd.merge(
    san_diego_census_counts,
    census_san_diego,
    on='census_tract',
    how='left',
    validate='1:1'
)

In [25]:
san_diego_census_rm.sample(10)

,census_tract,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_population,62yr_pp_pct,median_age,hispanic_population,non_hispanic_population,non_hispanic_white_population,non_hispanic_black_population,non_hispanic_asian_population,other_races_population,hispanic_pp_pct,non_hispanic_pp_pct,non_hispanic_white_pp_pct,non_hispanic_black_pp_pct,non_hispanic_asian_pp_pct,other_races_pp_pct,Unnamed: 22,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Unnamed: 27,asian_1_population,black_1_population,Unnamed: 30,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!SEX AND AGE!!Total population!!Median age (years),Estimate!!SEX AND AGE!!Total population!!Under 18 years,Estimate!!SEX AND AGE!!Total population!!16 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over,Estimate!!SEX AND AGE!!Total population!!21 years and over,Estimate!!SEX AND AGE!!Total population!!62 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races.1,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,Percent!!SEX AND AGE!!Total population!!20 to 24 years,Percent!!SEX AND AGE!!Total population!!25 to 34 years,Percent!!SEX AND AGE!!Total population!!35 to 44 years,Percent!!SEX AND AGE!!Total population!!45 to 54 years,Percent!!SEX AND AGE!!Total population!!55 to 59 years,Percent!!SEX AND AGE!!Total population!!60 to 64 years,Percent!!SEX AND AGE!!Total population!!65 to 74 years,Percent!!SEX AND AGE!!Total population!!75 to 84 years,Percent!!SEX AND AGE!!Total population!!85 years and over,Percent!!SEX AND AGE!!Total population!!Median age (years),Percent!!SEX AND AGE!!Total population!!Under 18 years,Percent!!SEX AND AGE!!Total population!!16 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over,Percent!!SEX AND AGE!!Total population!!21 years and over,Percent!!SEX AND AGE!!Total population!!62 years and over,Percent!!SEX AND AGE!!Total population!!65 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over.1,Percent!!SEX AND AGE!!Total population!!18 years and over!!Male,Percent!!SEX AND AGE!!Total population!!18 years and over!!Female,Percent!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!65 years and over.1,Percent!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent!!SEX AND AGE!!Total population!!65 years and over!!Female,Percent!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent!!RACE!!Total population,Percent!!RACE!!Total population!!One race,Percent!!RACE!!Total population!!Two or more races,Percent!!RACE!!Total population!!One race.1,Percent!!RACE!!Total population!!One race!!White,Percent!!RACE!!Total population!!One race!!Black or African American,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Percent!!RACE!!Total population!!One race!!Asian,Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian,Percent!!RACE!!Total population!!One race!!Asian!!Chinese,Percent!!RACE!!Total population!!One race!!Asian!!Filipino,Percent!!RACE!!Total population!!One race!!Asian!!Japanese,Percent!!RACE!!Total population!!One race!!Asian!!Korean,Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese,Percent!!RACE!!Total population!!One race!!Asian!!Other Asian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Some other race,Percent!!RACE!!Total population!!Two or more races.1,Percent!!RACE!!Total population!!Two or more races!!White and Black or African American,Percent!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Percent!!RACE!!Total population!!Two or more races!!White and Asian,Percent!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population,Percent!!Race alone or in combination with one or more other races!!Total population!!White,Percent!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Percent!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population!!Asian,Percent!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Percent!!Race alone or in combination with one or more other races!!Total population!!Some other race,Percent!!HISPANIC OR LATINO AND RACE!!Total population,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
563,06073013802,1,06073,San Diego County,CA,13802,138.02,3523,329,9.3%,30.1,1958,1565,750,588,81,146,55.6%,44.4%,21.3%,16.7%,2.3%,4.1%,NaN,8,0,0,138,NaN,85,593,NaN,1675,1848,90.6,364,370,260,268,137,599,443,461,169,256,94,51,51,30.1,1149,2436,2374,2194,329,196,2374,1037,1337,77.6,196,66,130,50.8,3523,3281,242,3281,1965,593,12,8,0,0,0,85,4,0,46,7,12,16,0,0,0,0,0,0,626,242,152,0,6,0,3523,2189,755,12,104,0,705,3523,1958,1838,12,4,104,1565,750,588,8,81,0,0,138,0,138,1004,2003,854,1149,3523,47.5,52.5,(X),10.3,10.5,7.4,7.6,3.9,17,12.6,13.1,4.8,7.3,2.7,1.4,1.4,(X),32.6,69.1,67.4,62.3,9.3,5.6,2374,43.7,56.3,(X),196,33.7,66.3,(X),3523,93.1,6.9,93.1,55.8,16.8,0.3,0.2,0,0,0,2.4,0.1,0,1.3,0.2,0.3,0.5,0,0,0,0,0,0,17.8,6.9,4.3,0,0.2,0,3523,62.1,21.4,0.3,3,0,20,3523,55.6,52.2,0.3,0.1,3,44.4,21.3,16.7,0.2,2.3,0,0,3.9,0,3.9,(X),2003,42.6,57.4
221,06073013416,10,06073,San Diego County,CA,13416,134.16,4261,807,18.9%,35.6,1995,2266,1205,412,531,118,46.8%,53.2%,28.3%,9.7%,12.5%,2.8%,NaN,0,0,0,118,NaN,572,412,NaN,2091,2170,96.4,154,303,391,225,285,696,599,488,192,260,412,194,62,35.6,992,3359,3269,3111,807,668,3269,1588,1681,94.5,668,262,406,64.5,4261,4064,197,4064,2802,412,11,0,0,0,0,572,0,45,405,54,0,33,35,0,0,0,0,0,267,197,26,22,94,0,4261,2972,438,33,693,0,322,4261,1995,1801,10,11,173,2266,1205,412,0,531,0,0,118,0,118,1305,2961,1408,1553,4261,49.1,50.9,(X),3.6,7.1,9.2,5.3,6.7,16.3,14.1,11.5,4.5,6.1,9.7,4.6,1.5,(X),23.3,78.8,76.7,73,18.9,15.7,3269,48.6,51.4,(X),668,39.2,60.8,(X),4261,95.4,4.6,95.4,65.8,9.7,0.3,0,0,0,0,13.4,0,1.1,9.5,1.3,0,0.8,0.8,0,0,0,0,0,6.3,4.6,0.6,0.5,2.2,0,4261,69.7,10.3,0.8,16.3,0,7.6,4261,46.8,42.3,0.2,0.3,4.1,53.2,28.3,9.7,0,12.5,0,0,2.8,0,2.8,(X),2961,47.6,52.4
114,06073017810,15,06073,San Diego County,CA,17810,178.1,4578,1291,28.2%,49.4,308,4270,3908,64,190,108,6.7%,93.3%,85.4%,1.4%,4.2%,2.4%,NaN,0,0,0,108,NaN,190,64,NaN,2131,2447,87.1,218,214,232,194,143,524,620,632,331,407,469,411,183,49.4,817,3850,3761,3702,1291,1063,3761,1759,2002,87.9,1063,488,575,84.9,4578,4456,122,4456,4199,64,0,0,0,0,0,190,145,21,0,22,0,2,0,0,0,0,0,0,3,122,68,0,40,0,4578,4307,132,0,244,0,17,4578,308,217,0,21,70,4270,3908,64,0,190,0,0,108,0,108,2192,3598,1670,1928,4578,46.5,53.5,(X),4.8,4.7,5.1,4.2,3.1,11.4,13.5,13.8,7.2,8.9,10.2,9,4,(X),17.8,84.1,82.2,80.9,28.2,23.2,3761,46.8,53.2,(X),1063,45.9,54.1,(X),4578,97.3,2.7,97.3,91.7,1.4,0,0,0,0,0,4.2,3.2,0.5,0,0.5,0,0,0,0,0,0,0,0,0.1,2.7,1.5,0,0.9,0,4578,94.1,2.9,0,5.3,0,0.4,4578,6.7,4.7,0,0.5,1.5,93.3,85.4,1.4,0,4.2,0,0,2.4,0,2.4,(X),3598,46.4,53.6
251,06073021302,8,06073,San Diego County,CA,21302,213.02,7616,1004,13.2%,37.1,2918,4698,3180,839,407,272,38.3%,61.7%,41.8%,11.0%,5.3%,3.6%,NaN,41,188,0,43,NaN,407,862,NaN,5544,2072,267.6,305,307,182,689,554,1530,1091,1214,527,442,560,180,35,37.1,1242,6707,6374,6041,1004,775,6374,4704,1670,281.7,775,419,356,117.7,7616,7541,75,7541,5864,862,41,10,0,0,0,407,9,0,180,86,3,85,44,188,15,29,0,144,179,75,0,8,26,5,7616,5933,867,55,433,192,211,7616,2918,2717,31,31,139,4698,3180,839,41,407,188,0,43,0,43,1536,6023,4453,1570,7616,72.8,27.2,(X),4,4,2.4,9,7.3,20.1,14.3,15.9,6.9,5.8,7.4,2.4,0.5,(X),16.3,88.1,83.7,79.3,13.2,10.2,6374,73.8,26.2,(X),775,54.1,45.9,(X),7616,99,1,99,77,11.3,0.5,0.1,0,0,0,5.3,0.1,0,2.4,1.1,0,1.1,0.6,2.5,0.2,0.4,0,1.9,2.4,1,0,0.1,0.3,0.1,7616,77.9,11.4,0.7,5.7,2.5,2.8,7616,38.3,35.7,0.4,0.4,1.8,61.7,41.8,11,0.5,5.3,2.5,0,0.6,0,0.6,(X),6023,73.9,26.1
486,06073016302,3,06073,San Diego County,CA,16302,163.02,5865,643,11.0%,33,1878,3987,3029,207,315,436,32.0%,68.0%,51.6%,3.5%,5.4%,7.4%,NaN,7,57,125,247,NaN,315,250,NaN,2984,2881,103.6,460,462,437,533,280,950,937,821,251,190,375,112,57,33,1756,4306,4109,3962,643,544,4109,2008,2101,95.6,544,227,317,71.6,5865,5532,333,5532,3692,250,7,0,0,0,0,315,64,24,120,0,0,98,9,57,0,0,0,57,1211,333,117,42,56,0,5865,4005,367,76,429,81,1278,5865,1878,1721,62,0,95,3987,3029,207,7,315,57,125,247,0,247,1732,2919,1443,1476,5865,50.9,49.1,(X),7.8,7.9,7.5,9.1,4.8,16.2,16,14,4.3,3.2,6.4,1.9,1,(X),29.9,73.4,70.1,67.6,11,9.3,4109,48.9,51.1,(X),544,41.7,58.3,(X),5865,94.3,5.7,94.3,62.9,4.3,0.1,0,0,0,0,5.4,1.1,0.4,2,0,0,1.7,0.2,1,0,0,0,1,20.6,5.7,2,0.7,1,0,5865,68.3,6.3,1.3,7.3,1.4,21.8,5865,32,29.3,1.1,0,1.6,68,51.6,3.5,0.1,5.4,1,2.1,4.2,0,4.2,(X),2919,49.4,50.6
540,06073008354,1,06073,San Diego County,CA,8354,83.54,10247,1117,10.9%,32.2,877,9370,3163,503,4846,858,8.6%,91.4%,30.9%,4.9%,47.3%,8.4%,NaN,0,168,0,690,NaN,4870,503,NaN,4837,5410,89.4,981,651,361,353,958,2456,1552,1240,432,432,417,319,95,32.2,2180,8205,8067,7820,1117,831,8067,3716,4351,85.4,831,321,510,62.9,10247,9292,955,9292,3553,503,0,0,0,0,0,4870,1374,642,1471,82,148,945,208,168,24,144,0,0,198,955,223,27,174,0,10247,4271,924,27,5423,478,410,10247,877,824,0,1,52,9370,3163,503,0,4846,168,0,690,0,690,3409,6582,3078,3504,10247,47.2,52.8,(X),9.6,6.4,3.5,3.4,9.3,24,15.1,12.1,4.2,4.2,4.1,3.1,0.9,(X),21.3,80.1,78.7,76.3,10.9,8.1,8067,46.1,53.9,(X),831,38.6,61.4,(X),10247,90.7,9.3,90.7,34.7,4.9,0,0,0,0,0,47.5,13.4,6.3,14.4,0.8,1.4,9.2,2,1.6,0.2,1.4,0,0,1.9,9.3,2.2,0.3,1.7,0,10247,41.7,9,0.3,52.9,4.7,4,10247,8.6,8,0,0,0.5,91.4,30.9,4.9,0,47.3,1.6,0,6.7,0,6.7,(X),6582,46.8,53.2

In [26]:
san_diego_census_rm.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 573 entries, 0 to 572
Data columns (total 209 columns):
 #    Column                                                                                                                                                            Dtype
---   ------                                                                                                                                                            -----
 0    census_tract                                                                                                                                                      object
 1    rm_no                                                                                                                                                             int64
 2    county_code                                                                                                                                                       object
 3    county                                                                                                                                                            object
 4    state_code                                                                                                                                                        object
 5    census_tract_np                                                                                                                                                   object
 6    census_tract_period                                                                                                                                               object
 7    total_population                                                                                                                                                  int64
 8    62yr_population                                                                                                                                                   int64
 9    62yr_pp_pct                                                                                                                                                       object
 10   median_age                                                                                                                                                        object
 11   hispanic_population                                                                                                                                               int64
 12   non_hispanic_population                                                                                                                                           int64
 13   non_hispanic_white_population                                                                                                                                     int64
 14   non_hispanic_black_population                                                                                                                                     int64
 15   non_hispanic_asian_population                                                                                                                                     int64
 16   other_races_population                                                                                                                                            int64
 17   hispanic_pp_pct                                                                                                                                                   object
 18   non_hispanic_pp_pct                                                                                                                                               object
 19   non_hispanic_white_pp_pct                                                                                                                                         object
 20   non_hispanic_black_pp_pct                                                                                                                                         object
 21   non_hispanic_asian_pp_pct                                                                                                                                         object
 22   other_races_pp_pct                                                                                                                                                object
 23   Unnamed: 22                                                                                                                                                       float64
 24   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone                                          int64
 25   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone                                 int64
 26   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone                                                            int64
 27   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races                                                                int64
 28   Unnamed: 27                                                                                                                                                       float64
 29   asian_1_population                                                                                                                                                int64
 30   black_1_population                                                                                                                                                int64
 31   Unnamed: 30                                                                                                                                                       float64
 32   Estimate!!SEX AND AGE!!Total population!!Male                                                                                                                     int64
 33   Estimate!!SEX AND AGE!!Total population!!Female                                                                                                                   int64
 34   Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)                                                                                        object
 35   Estimate!!SEX AND AGE!!Total population!!Under 5 years                                                                                                            int64
 36   Estimate!!SEX AND AGE!!Total population!!5 to 9 years                                                                                                             int64
 37   Estimate!!SEX AND AGE!!Total population!!10 to 14 years                                                                                                           int64
 38   Estimate!!SEX AND AGE!!Total population!!15 to 19 years                                                                                                           int64
 39   Estimate!!SEX AND AGE!!Total population!!20 to 24 years                                                                                                           int64
 40   Estimate!!SEX AND AGE!!Total population!!25 to 34 years                                                                                                           int64
 41   Estimate!!SEX AND AGE!!Total population!!35 to 44 years                                                                                                           int64
 42   Estimate!!SEX AND AGE!!Total population!!45 to 54 years                                                                                                           int64
 43   Estimate!!SEX AND AGE!!Total population!!55 to 59 years                                                                                                           int64
 44   Estimate!!SEX AND AGE!!Total population!!60 to 64 years                                                                                                           int64
 45   Estimate!!SEX AND AGE!!Total population!!65 to 74 years                                                                                                           int64
 46   Estimate!!SEX AND AGE!!Total population!!75 to 84 years                                                                                                           int64
 47   Estimate!!SEX AND AGE!!Total population!!85 years and over                                                                                                        int64
 48   Estimate!!SEX AND AGE!!Total population!!Median age (years)                                                                                                       object
 49   Estimate!!SEX AND AGE!!Total population!!Under 18 years                                                                                                           int64
 50   Estimate!!SEX AND AGE!!Total population!!16 years and over                                                                                                        int64
 51   Estimate!!SEX AND AGE!!Total population!!18 years and over                                                                                                        int64
 52   Estimate!!SEX AND AGE!!Total population!!21 years and over                                                                                                        int64
 53   Estimate!!SEX AND AGE!!Total population!!62 years and over                                                                                                        int64
 54   Estimate!!SEX AND AGE!!Total population!!65 years and over                                                                                                        int64
 55   Estimate!!SEX AND AGE!!Total population!!18 years and over.1                                                                                                      int64
 56   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male                                                                                                  int64
 57   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female                                                                                                int64
 58   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)                                                                     object
 59   Estimate!!SEX AND AGE!!Total population!!65 years and over.1                                                                                                      int64
 60   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male                                                                                                  int64
 61   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female                                                                                                int64
 62   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)                                                                     object
 63   Estimate!!RACE!!Total population                                                                                                                                  int64
 64   Estimate!!RACE!!Total population!!One race                                                                                                                        int64
 65   Estimate!!RACE!!Total population!!Two or more races                                                                                                               int64
 66   Estimate!!RACE!!Total population!!One race.1                                                                                                                      int64
 67   Estimate!!RACE!!Total population!!One race!!White                                                                                                                 int64
 68   Estimate!!RACE!!Total population!!One race!!Black or African American                                                                                             int64
 69   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native                                                                                     int64
 70   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping                                                           int64
 71   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping                                                           int64
 72   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping                                                             int64
 73   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping                                                              int64
 74   Estimate!!RACE!!Total population!!One race!!Asian                                                                                                                 int64
 75   Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian                                                                                                   int64
 76   Estimate!!RACE!!Total population!!One race!!Asian!!Chinese                                                                                                        int64
 77   Estimate!!RACE!!Total population!!One race!!Asian!!Filipino                                                                                                       int64
 78   Estimate!!RACE!!Total population!!One race!!Asian!!Japanese                                                                                                       int64
 79   Estimate!!RACE!!Total population!!One race!!Asian!!Korean                                                                                                         int64
 80   Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese                                                                                                     int64
 81   Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian                                                                                                    int64
 82   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander                                                                            int64
 83   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian                                                           int64
 84   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro                                                     int64
 85   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan                                                                    int64
 86   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander                                                    int64
 87   Estimate!!RACE!!Total population!!One race!!Some other race                                                                                                       int64
 88   Estimate!!RACE!!Total population!!Two or more races.1                                                                                                             int64
 89   Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American                                                                          int64
 90   Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native                                                                  int64
 91   Estimate!!RACE!!Total population!!Two or more races!!White and Asian                                                                                              int64
 92   Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native                                              int64
 93   Estimate!!Race alone or in combination with one or more other races!!Total population                                                                             int64
 94   Estimate!!Race alone or in combination with one or more other races!!Total population!!White                                                                      int64
 95   Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American                                                  int64
 96   Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native                                          int64
 97   Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian                                                                      int64
 98   Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander                                 int64
 99   Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race                                                            int64
 100  Estimate!!HISPANIC OR LATINO AND RACE!!Total population                                                                                                           int64
 101  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)                                                                         int64
 102  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican                                                                int64
 103  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican                                                           int64
 104  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban                                                                  int64
 105  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino                                               int64
 106  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino                                                                                   int64
 107  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone                                                                      int64
 108  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone                                                  int64
 109  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1                                        int64
 110  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone                                                                      int64
 111  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1                               int64

In [27]:
# subset to the columns that I need

san_diego_census_rm = san_diego_census_rm[['census_tract', 'rm_no', 'county_code', 'county', 'state_code', 'census_tract_np', 'census_tract_period', 'total_population', '62yr_pp_pct', 'median_age', 'hispanic_pp_pct', 'non_hispanic_black_pp_pct']].copy()

In [28]:
san_diego_census_rm

,census_tract,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_pp_pct,median_age,hispanic_pp_pct,non_hispanic_black_pp_pct
0,06073017019,56,06073,San Diego County,CA,17019,170.19,6673,51.4%,62.8,10.1%,2.1%
1,06073019808,55,06073,San Diego County,CA,19808,198.08,4354,55.8%,66.3,5.6%,0.0%
2,06073018802,46,06073,San Diego County,CA,18802,188.02,8320,37.4%,53.5,14.4%,1.1%
3,06073018512,45,06073,San Diego County,CA,18512,185.12,3960,51.8%,63.3,24.8%,6.8%
4,06073019806,40,06073,San Diego County,CA,19806,198.06,12647,17.6%,37.1,24.3%,2.2%
...,...,...,...,...,...,...,...,...,...,...,...,...
568,06073016202,1,06073,San Diego County,CA,16202,162.02,3868,6.2%,29.6,19.5%,13.4%
569,06073006500,1,06073,San Diego County,CA,6500,65,3359,32.5%,49.1,20.0%,13.2%
570,06073010012,1,06073,San Diego County,CA,10012,100.12,5199,9.3%,30.1,96.9%,0.4%
571,06073019903,1,06073,San Diego County,CA,19903,199.03,5035,18.0%,35.7,35.5%,4.1%
572,06073020209,1,06073,San Diego County,CA,20209,202.09,5224,22.4%,35.2,57.1%,1.9%

In [29]:
# calculate rm per 1000 people

san_diego_census_rm['_rm_per_1000'] = (
    san_diego_census_rm['rm_no'] / san_diego_census_rm['total_population'] * 1000
)

In [30]:
san_diego_census_rm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 573 entries, 0 to 572
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   census_tract               573 non-null    object
 1   rm_no                      573 non-null    int64
 2   county_code                573 non-null    object
 3   county                     573 non-null    object
 4   state_code                 573 non-null    object
 5   census_tract_np            573 non-null    object
 6   census_tract_period        573 non-null    object
 7   total_population           573 non-null    int64
 8   62yr_pp_pct                573 non-null    object
 9   median_age                 573 non-null    object
 10  hispanic_pp_pct            573 non-null    object
 11  non_hispanic_black_pp_pct  573 non-null    object
 12  _rm_per_1000               573 non-null    float64
dtypes: float64(1), int64(2), object(10)
memory usage: 62.7+ KB

In [31]:
# get the column names

cols = list(san_diego_census_rm.columns.values)
cols

['census_tract',
 'rm_no',
 'county_code',
 'county',
 'state_code',
 'census_tract_np',
 'census_tract_period',
 'total_population',
 '62yr_pp_pct',
 'median_age',
 'hispanic_pp_pct',
 'non_hispanic_black_pp_pct',
 '_rm_per_1000']

In [32]:
# reorder the columns

san_diego_census_rm = san_diego_census_rm[[
    'census_tract', 
    '_rm_per_1000',
    'rm_no',
    'county_code',
    'county',
    'state_code',
    'census_tract_np',
    'census_tract_period',
    'total_population',
    '62yr_pp_pct',
    'median_age',
    'hispanic_pp_pct',
    'non_hispanic_black_pp_pct',
 ]]

In [33]:
# sort by reverse mortgages originated per 1000 people

san_diego_census_rm = san_diego_census_rm.sort_values(by='_rm_per_1000', ascending=False)
san_diego_census_rm

,census_tract,_rm_per_1000,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_pp_pct,median_age,hispanic_pp_pct,non_hispanic_black_pp_pct
5,06073017014,15.276146,39,06073,San Diego County,CA,17014,170.14,2553,79.2%,72.9,8.4%,1.2%
1,06073019808,12.632062,55,06073,San Diego County,CA,19808,198.08,4354,55.8%,66.3,5.6%,0.0%
3,06073018512,11.363636,45,06073,San Diego County,CA,18512,185.12,3960,51.8%,63.3,24.8%,6.8%
33,06073017306,9.430094,23,06073,San Diego County,CA,17306,173.06,2439,32.6%,54.4,7.7%,0.0%
0,06073017019,8.392028,56,06073,San Diego County,CA,17019,170.19,6673,51.4%,62.8,10.1%,2.1%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,06073016504,0.145858,1,06073,San Diego County,CA,16504,165.04,6856,9.4%,31.9,31.3%,8.8%
535,06073008341,0.119789,1,06073,San Diego County,CA,8341,83.41,8348,12.0%,25.9,6.1%,1.1%
540,06073008354,0.097590,1,06073,San Diego County,CA,8354,83.54,10247,10.9%,32.2,8.6%,4.9%
566,06073008333,0.061113,1,06073,San Diego County,CA,8333,83.33,16363,8.0%,37.8,8.2%,0.7%
556,06073018700,0.025804,1,06073,San Diego County,CA,18700,187,38754,0.3%,21.6,28.6%,8.7%

## export to csv

In [34]:
san_diego_rm_name.to_csv('./reverse_mortgage_data/san_diego_rm_with_name.csv', index=False)
san_diego_census_rm.to_csv('./reverse_mortgage_data/san_diego_census_rm.csv', index=False)