In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

## read reverse mortgage data

In [2]:
imperial_rm_all = pd.read_csv('./reverse_mortgage_data/imperial_rm_all.csv', dtype={
    'county_code': str,
    'census_tract': str
})
imperial_rm_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 99 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   activity_year                             112 non-null    int64
 1   lei                                       112 non-null    object
 2   derived_msa-md                            112 non-null    int64
 3   state_code                                112 non-null    object
 4   county_code                               112 non-null    object
 5   census_tract                              112 non-null    object
 6   conforming_loan_limit                     112 non-null    object
 7   derived_loan_product_type                 112 non-null    object
 8   derived_dwelling_category                 112 non-null    object
 9   derived_ethnicity                         112 non-null    object
 10  derived_race                              112 non-null    object
 11  derived_sex                               112 non-null    object
 12  action_taken                              112 non-null    int64
 13  purchaser_type                            112 non-null    int64
 14  preapproval                               112 non-null    int64
 15  loan_type                                 112 non-null    int64
 16  loan_purpose                              112 non-null    int64
 17  lien_status                               112 non-null    int64
 18  reverse_mortgage                          112 non-null    int64
 19  open-end_line_of_credit                   112 non-null    int64
 20  business_or_commercial_purpose            112 non-null    int64
 21  loan_amount                               112 non-null    float64
 22  loan_to_value_ratio                       4 non-null      float64
 23  interest_rate                             47 non-null     float64
 24  rate_spread                               0 non-null      float64
 25  hoepa_status                              112 non-null    int64
 26  total_loan_costs                          0 non-null      float64
 27  total_points_and_fees                     0 non-null      float64
 28  origination_charges                       0 non-null      float64
 29  discount_points                           0 non-null      float64
 30  lender_credits                            0 non-null      float64
 31  loan_term                                 0 non-null      float64
 32  prepayment_penalty_term                   0 non-null      float64
 33  intro_rate_period                         38 non-null     float64
 34  negative_amortization                     112 non-null    int64
 35  interest_only_payment                     112 non-null    int64
 36  balloon_payment                           112 non-null    int64
 37  other_nonamortizing_features              112 non-null    int64
 38  property_value                            64 non-null     float64
 39  construction_method                       112 non-null    int64
 40  occupancy_type                            112 non-null    int64
 41  manufactured_home_secured_property_type   112 non-null    int64
 42  manufactured_home_land_property_interest  112 non-null    int64
 43  total_units                               112 non-null    int64
 44  multifamily_affordable_units              0 non-null      float64
 45  income                                    95 non-null     float64
 46  debt_to_income_ratio                      2 non-null      object
 47  applicant_credit_score_type               112 non-null    int64
 48  co-applicant_credit_score_type            112 non-null    int64
 49  applicant_ethnicity-1                     112 non-null    float64
 50  applicant_ethnicity-2                     14 non-null     float64
 51  applicant_ethnicity-3                     0 non-null      float64
 52  applicant_ethnicity-4                     0 non-null      float64
 53  applicant_ethnicity-5                     0 non-null      float64
 54  co-applicant_ethnicity-1                  112 non-null    float64
 55  co-applicant_ethnicity-2                  7 non-null      float64
 56  co-applicant_ethnicity-3                  0 non-null      float64
 57  co-applicant_ethnicity-4                  0 non-null      float64
 58  co-applicant_ethnicity-5                  0 non-null      float64
 59  applicant_ethnicity_observed              112 non-null    int64
 60  co-applicant_ethnicity_observed           112 non-null    int64
 61  applicant_race-1                          112 non-null    float64
 62  applicant_race-2                          0 non-null      float64
 63  applicant_race-3                          0 non-null      float64
 64  applicant_race-4                          0 non-null      float64
 65  applicant_race-5                          0 non-null      float64
 66  co-applicant_race-1                       112 non-null    float64
 67  co-applicant_race-2                       0 non-null      float64
 68  co-applicant_race-3                       0 non-null      float64
 69  co-applicant_race-4                       0 non-null      float64
 70  co-applicant_race-5                       0 non-null      float64
 71  applicant_race_observed                   112 non-null    int64
 72  co-applicant_race_observed                112 non-null    int64
 73  applicant_sex                             112 non-null    int64
 74  co-applicant_sex                          112 non-null    int64
 75  applicant_sex_observed                    112 non-null    int64
 76  co-applicant_sex_observed                 112 non-null    int64
 77  applicant_age                             112 non-null    object
 78  co-applicant_age                          112 non-null    object
 79  applicant_age_above_62                    59 non-null     object
 80  co-applicant_age_above_62                 24 non-null     object
 81  submission_of_application                 112 non-null    int64
 82  initially_payable_to_institution          112 non-null    int64
 83  aus-1                                     112 non-null    int64
 84  aus-2                                     0 non-null      float64
 85  aus-3                                     0 non-null      float64
 86  aus-4                                     0 non-null      float64
 87  aus-5                                     0 non-null      float64
 88  denial_reason-1                           112 non-null    int64
 89  denial_reason-2                           0 non-null      float64
 90  denial_reason-3                           0 non-null      float64
 91  denial_reason-4                           0 non-null      float64
 92  tract_population                          112 non-null    int64
 93  tract_minority_population_percent         112 non-null    float64
 94  ffiec_msa_md_median_family_income         112 non-null    int64
 95  tract_to_msa_income_percentage            112 non-null    int64
 96  tract_owner_occupied_units                112 non-null    int64
 97  tract_one_to_four_family_homes            112 non-null    int64
 98  tract_median_age_of_housing_units         112 non-null    int64
dtypes: float64(43), int64(41), object(15)
memory usage: 86.8+ KB

## read census data and filter to county

In [3]:
census_all = pd.read_csv('./census_data/ACS2019_filtered0623.csv', dtype={
    'census_tract': str,
    'county_code': str,
    'census_tract_np': str,
    'census_tract_period': str
})
census_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Columns: 208 entries, census_tract to Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female
dtypes: float64(3), int64(105), object(100)
memory usage: 7.1+ MB

In [4]:
census_imperial = census_all[census_all['county_code'] == '06025'].copy()

In [5]:
census_imperial.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31 entries, 361 to 391
Columns: 208 entries, census_tract to Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female
dtypes: float64(3), int64(105), object(100)
memory usage: 50.6+ KB

## merge lender list

In [6]:
# read lender list

lender_list_2018 = pd.read_csv('./raw_data/lei_agency_name_2018.csv')

In [7]:
lender_list_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5735 entries, 0 to 5734
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   lei                  5735 non-null   object
 1   activity_year        5735 non-null   int64
 2   calendar_quarter     5735 non-null   int64
 3   tax_id               5735 non-null   object
 4   agency_code          5735 non-null   int64
 5   respondent_name      5735 non-null   object
 6   respondent_state     5735 non-null   object
 7   respondent_city      5735 non-null   object
 8   respondent_zip_code  5735 non-null   object
 9   lar_count            5735 non-null   int64
dtypes: int64(4), object(6)
memory usage: 448.2+ KB

In [8]:
# merge by lei

imperial_rm_all

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open-end_line_of_credit,business_or_commercial_purpose,loan_amount,loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co-applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity-2,applicant_ethnicity-3,applicant_ethnicity-4,applicant_ethnicity-5,co-applicant_ethnicity-1,co-applicant_ethnicity-2,co-applicant_ethnicity-3,co-applicant_ethnicity-4,co-applicant_ethnicity-5,applicant_ethnicity_observed,co-applicant_ethnicity_observed,applicant_race-1,applicant_race-2,applicant_race-3,applicant_race-4,applicant_race-5,co-applicant_race-1,co-applicant_race-2,co-applicant_race-3,co-applicant_race-4,co-applicant_race-5,applicant_race_observed,co-applicant_race_observed,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus-1,aus-2,aus-3,aus-4,aus-5,denial_reason-1,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010400,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,White,Joint,2,0,2,2,31,1,1,1,2,95000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,195000.0,1,1,3,5,1,NaN,26.0,NaN,9,9,1.0,11.0,NaN,NaN,NaN,1.0,11.0,NaN,NaN,NaN,2,2,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,2,1,2,2,2,>74,65-74,Yes,Yes,2,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,7641,93.51,48200,63,890,1815,33
1,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010102,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,31,1,1,1,2,85000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,95000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4631,91.75,48200,65,657,1598,34
2,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010700,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,1,1,1,1,2,145000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,175000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4729,96.87,48200,67,626,1222,35
3,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025011500,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,31,1,1,1,2,165000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,185000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,6491,96.29,48200,62,601,1613,47
4,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010700,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,31,1,1,1,2,185000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,205000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4729,96.87,48200,67,626,1222,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2021,549300S5YL3OH0IVCS62,20940,CA,06025,06025011000,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,4,1,1,1,2,95000.0,NaN,2.305,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,2,2,2,225000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,12677,80.15,56200,175,2613,3960,18
108,2021,549300OPCWU6E72WUT29,20940,CA,06025,06025011000,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,1,71,2,2,4,1,1,1,2,155000.0,NaN,2.305,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,225000.0,1,1,3,5,1,NaN,18.0,NaN,9,10,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,3,5,2,4,>74,9999,Yes,NaN,2,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,12677,80.15,56200,175,2613,3960,18
109,2021,PAOOWF3GUFM46FBSP561,20940,CA,06025,06025011000,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,8,2,2,31,1,1,1,2,145000.0,NaN,2.170,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,2,2,2,235000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,12677,80.15,56200,175,2613,3960,18
110,2021,PAOOWF3GUFM46FBSP561,20940,CA,06025,06025011000,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,8,2,2,31,1,1,2,2,155000.0,NaN,3.430,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,305000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,12677,80.15,56200,175,2613,3960,18
111,2021,PAOOWF3GUFM46FBSP561,20940,CA,06025,06025012302,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,Race Not Available,Female,1,8,2,2,31,1,1,1,2,115000.0,NaN,3.100,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,2,2,2,195000.0,1,1,3,5,1,NaN,11.0,NaN,9,9,1.0,11.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,>74,9999,Yes,NaN,2,2,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,6037,70.58,56200,73,1144,2807,21

In [9]:
lender_list_2018

,lei,activity_year,calendar_quarter,tax_id,agency_code,respondent_name,respondent_state,respondent_city,respondent_zip_code,lar_count
0,213800QUAI2VH5YM6310,2018,4,05-0402708,7,"Embrace Home Loans, Inc.",RI,Middletown,02842,38810
1,5493001SXWZ4OFP8Z903,2018,4,74-2853239,7,DHI Mortgage Company Limited,TX,Austin,78750,45691
2,549300YHR41F57LS0R28,2018,4,39-0273630,3,Farmers and Merchants Union Bank,WI,Columbus,53925,131
3,549300SX6THT96LFD245,2018,4,26-1866970,3,Oakworth Capital Bank,AL,Birmingham,35209,29
4,2549000UUHZDEKIZ2Z84,2018,4,34-0144365,1,The Citizens National Bank,OH,Woodsfield,43793,97
...,...,...,...,...,...,...,...,...,...,...
5730,Z867SNMO7WGY8TTGQG78,2018,4,55-0744997,3,SUMMIT COMMUNITY BANK,WV,MOOREFIELD,26836,1035
5731,ZF85QS7OXKPBG52R7N18,2018,4,39-1941673,9,Associated Bank NA,WI,Green Bay,54301,20022
5732,ZXMJHJK466PBZTM5F379,2018,4,59-3244348,9,Raymond James Bank National Association,FL,SAINT PETERSBURG,33716,2067
5733,ZXZDWBXF4U47HEP2EO46,2018,4,33-0244449,2,Silvergate Bank,CA,La Jolla,92037,298
5734,SS1TRMSN6BRNMOREEV51,2018,4,38-2734984,9,Flagstar Bank,MI,Troy,48098,149977

In [10]:
imperial_rm_full = pd.merge(
    imperial_rm_all,
    lender_list_2018,
    on='lei',
    how='left',
    validate='m:1'
)

In [11]:
imperial_rm_full.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112 entries, 0 to 111
Data columns (total 108 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           112 non-null    int64
 1    lei                                       112 non-null    object
 2    derived_msa-md                            112 non-null    int64
 3    state_code                                112 non-null    object
 4    county_code                               112 non-null    object
 5    census_tract                              112 non-null    object
 6    conforming_loan_limit                     112 non-null    object
 7    derived_loan_product_type                 112 non-null    object
 8    derived_dwelling_category                 112 non-null    object
 9    derived_ethnicity                         112 non-null    object
 10   derived_race                              112 non-null    object
 11   derived_sex                               112 non-null    object
 12   action_taken                              112 non-null    int64
 13   purchaser_type                            112 non-null    int64
 14   preapproval                               112 non-null    int64
 15   loan_type                                 112 non-null    int64
 16   loan_purpose                              112 non-null    int64
 17   lien_status                               112 non-null    int64
 18   reverse_mortgage                          112 non-null    int64
 19   open-end_line_of_credit                   112 non-null    int64
 20   business_or_commercial_purpose            112 non-null    int64
 21   loan_amount                               112 non-null    float64
 22   loan_to_value_ratio                       4 non-null      float64
 23   interest_rate                             47 non-null     float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              112 non-null    int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         38 non-null     float64
 34   negative_amortization                     112 non-null    int64
 35   interest_only_payment                     112 non-null    int64
 36   balloon_payment                           112 non-null    int64
 37   other_nonamortizing_features              112 non-null    int64
 38   property_value                            64 non-null     float64
 39   construction_method                       112 non-null    int64
 40   occupancy_type                            112 non-null    int64
 41   manufactured_home_secured_property_type   112 non-null    int64
 42   manufactured_home_land_property_interest  112 non-null    int64
 43   total_units                               112 non-null    int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    95 non-null     float64
 46   debt_to_income_ratio                      2 non-null      object
 47   applicant_credit_score_type               112 non-null    int64
 48   co-applicant_credit_score_type            112 non-null    int64
 49   applicant_ethnicity-1                     112 non-null    float64
 50   applicant_ethnicity-2                     14 non-null     float64
 51   applicant_ethnicity-3                     0 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  112 non-null    float64
 55   co-applicant_ethnicity-2                  7 non-null      float64
 56   co-applicant_ethnicity-3                  0 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              112 non-null    int64
 60   co-applicant_ethnicity_observed           112 non-null    int64
 61   applicant_race-1                          112 non-null    float64
 62   applicant_race-2                          0 non-null      float64
 63   applicant_race-3                          0 non-null      float64
 64   applicant_race-4                          0 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       112 non-null    float64
 67   co-applicant_race-2                       0 non-null      float64
 68   co-applicant_race-3                       0 non-null      float64
 69   co-applicant_race-4                       0 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   112 non-null    int64
 72   co-applicant_race_observed                112 non-null    int64
 73   applicant_sex                             112 non-null    int64
 74   co-applicant_sex                          112 non-null    int64
 75   applicant_sex_observed                    112 non-null    int64
 76   co-applicant_sex_observed                 112 non-null    int64
 77   applicant_age                             112 non-null    object
 78   co-applicant_age                          112 non-null    object
 79   applicant_age_above_62                    59 non-null     object
 80   co-applicant_age_above_62                 24 non-null     object
 81   submission_of_application                 112 non-null    int64
 82   initially_payable_to_institution          112 non-null    int64
 83   aus-1                                     112 non-null    int64
 84   aus-2                                     0 non-null      float64
 85   aus-3                                     0 non-null      float64
 86   aus-4                                     0 non-null      float64
 87   aus-5                                     0 non-null      float64
 88   denial_reason-1                           112 non-null    int64
 89   denial_reason-2                           0 non-null      float64
 90   denial_reason-3                           0 non-null      float64
 91   denial_reason-4                           0 non-null      float64
 92   tract_population                          112 non-null    int64
 93   tract_minority_population_percent         112 non-null    float64
 94   ffiec_msa_md_median_family_income         112 non-null    int64
 95   tract_to_msa_income_percentage            112 non-null    int64
 96   tract_owner_occupied_units                112 non-null    int64
 97   tract_one_to_four_family_homes            112 non-null    int64
 98   tract_median_age_of_housing_units         112 non-null    int64
 99   activity_year_y                           112 non-null    int64
 100  calendar_quarter                          112 non-null    int64
 101  tax_id                                    112 non-null    object
 102  agency_code                               112 non-null    int64
 103  respondent_name                           112 non-null    object
 104  respondent_state                          112 non-null    object
 105  respondent_city                           112 non-null    object
 106  respondent_zip_code                       112 non-null    object
 107  lar_count                                 112 non-null    int64
dtypes: float64(43), int64(45), object(20)
memory usage: 95.4+ KB

In [12]:
imperial_rm_name = imperial_rm_full.drop(columns= ['activity_year_y', 'calendar_quarter', 'lar_count']).copy()

In [13]:
imperial_rm_name.head()

,activity_year_x,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open-end_line_of_credit,business_or_commercial_purpose,loan_amount,loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co-applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity-2,applicant_ethnicity-3,applicant_ethnicity-4,applicant_ethnicity-5,co-applicant_ethnicity-1,co-applicant_ethnicity-2,co-applicant_ethnicity-3,co-applicant_ethnicity-4,co-applicant_ethnicity-5,applicant_ethnicity_observed,co-applicant_ethnicity_observed,applicant_race-1,applicant_race-2,applicant_race-3,applicant_race-4,applicant_race-5,co-applicant_race-1,co-applicant_race-2,co-applicant_race-3,co-applicant_race-4,co-applicant_race-5,applicant_race_observed,co-applicant_race_observed,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus-1,aus-2,aus-3,aus-4,aus-5,denial_reason-1,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units,tax_id,agency_code,respondent_name,respondent_state,respondent_city,respondent_zip_code
0,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010400,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,White,Joint,2,0,2,2,31,1,1,1,2,95000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,195000.0,1,1,3,5,1,NaN,26.0,NaN,9,9,1.0,11.0,NaN,NaN,NaN,1.0,11.0,NaN,NaN,NaN,2,2,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,2,1,2,2,2,>74,65-74,Yes,Yes,2,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,7641,93.51,48200,63,890,1815,33,80-0860209,7,Reverse Mortgage Funding LLC,NJ,Bloomfield,07003
1,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010102,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,31,1,1,1,2,85000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,95000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4631,91.75,48200,65,657,1598,34,80-0860209,7,Reverse Mortgage Funding LLC,NJ,Bloomfield,07003
2,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010700,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,1,1,1,1,2,145000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,175000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4729,96.87,48200,67,626,1222,35,80-0860209,7,Reverse Mortgage Funding LLC,NJ,Bloomfield,07003
3,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025011500,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,31,1,1,1,2,165000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,185000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,6491,96.29,48200,62,601,1613,47,80-0860209,7,Reverse Mortgage Funding LLC,NJ,Bloomfield,07003
4,2018,5493001FXF3J5C0QWQ87,20940,CA,06025,06025010700,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,2,2,2,31,1,1,1,2,185000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2,2,2,2,205000.0,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4729,96.87,48200,67,626,1222,35,80-0860209,7,Reverse Mortgage Funding LLC,NJ,Bloomfield,07003

In [14]:
imperial_rm_name.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112 entries, 0 to 111
Data columns (total 105 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           112 non-null    int64
 1    lei                                       112 non-null    object
 2    derived_msa-md                            112 non-null    int64
 3    state_code                                112 non-null    object
 4    county_code                               112 non-null    object
 5    census_tract                              112 non-null    object
 6    conforming_loan_limit                     112 non-null    object
 7    derived_loan_product_type                 112 non-null    object
 8    derived_dwelling_category                 112 non-null    object
 9    derived_ethnicity                         112 non-null    object
 10   derived_race                              112 non-null    object
 11   derived_sex                               112 non-null    object
 12   action_taken                              112 non-null    int64
 13   purchaser_type                            112 non-null    int64
 14   preapproval                               112 non-null    int64
 15   loan_type                                 112 non-null    int64
 16   loan_purpose                              112 non-null    int64
 17   lien_status                               112 non-null    int64
 18   reverse_mortgage                          112 non-null    int64
 19   open-end_line_of_credit                   112 non-null    int64
 20   business_or_commercial_purpose            112 non-null    int64
 21   loan_amount                               112 non-null    float64
 22   loan_to_value_ratio                       4 non-null      float64
 23   interest_rate                             47 non-null     float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              112 non-null    int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         38 non-null     float64
 34   negative_amortization                     112 non-null    int64
 35   interest_only_payment                     112 non-null    int64
 36   balloon_payment                           112 non-null    int64
 37   other_nonamortizing_features              112 non-null    int64
 38   property_value                            64 non-null     float64
 39   construction_method                       112 non-null    int64
 40   occupancy_type                            112 non-null    int64
 41   manufactured_home_secured_property_type   112 non-null    int64
 42   manufactured_home_land_property_interest  112 non-null    int64
 43   total_units                               112 non-null    int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    95 non-null     float64
 46   debt_to_income_ratio                      2 non-null      object
 47   applicant_credit_score_type               112 non-null    int64
 48   co-applicant_credit_score_type            112 non-null    int64
 49   applicant_ethnicity-1                     112 non-null    float64
 50   applicant_ethnicity-2                     14 non-null     float64
 51   applicant_ethnicity-3                     0 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  112 non-null    float64
 55   co-applicant_ethnicity-2                  7 non-null      float64
 56   co-applicant_ethnicity-3                  0 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              112 non-null    int64
 60   co-applicant_ethnicity_observed           112 non-null    int64
 61   applicant_race-1                          112 non-null    float64
 62   applicant_race-2                          0 non-null      float64
 63   applicant_race-3                          0 non-null      float64
 64   applicant_race-4                          0 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       112 non-null    float64
 67   co-applicant_race-2                       0 non-null      float64
 68   co-applicant_race-3                       0 non-null      float64
 69   co-applicant_race-4                       0 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   112 non-null    int64
 72   co-applicant_race_observed                112 non-null    int64
 73   applicant_sex                             112 non-null    int64
 74   co-applicant_sex                          112 non-null    int64
 75   applicant_sex_observed                    112 non-null    int64
 76   co-applicant_sex_observed                 112 non-null    int64
 77   applicant_age                             112 non-null    object
 78   co-applicant_age                          112 non-null    object
 79   applicant_age_above_62                    59 non-null     object
 80   co-applicant_age_above_62                 24 non-null     object
 81   submission_of_application                 112 non-null    int64
 82   initially_payable_to_institution          112 non-null    int64
 83   aus-1                                     112 non-null    int64
 84   aus-2                                     0 non-null      float64
 85   aus-3                                     0 non-null      float64
 86   aus-4                                     0 non-null      float64
 87   aus-5                                     0 non-null      float64
 88   denial_reason-1                           112 non-null    int64
 89   denial_reason-2                           0 non-null      float64
 90   denial_reason-3                           0 non-null      float64
 91   denial_reason-4                           0 non-null      float64
 92   tract_population                          112 non-null    int64
 93   tract_minority_population_percent         112 non-null    float64
 94   ffiec_msa_md_median_family_income         112 non-null    int64
 95   tract_to_msa_income_percentage            112 non-null    int64
 96   tract_owner_occupied_units                112 non-null    int64
 97   tract_one_to_four_family_homes            112 non-null    int64
 98   tract_median_age_of_housing_units         112 non-null    int64
 99   tax_id                                    112 non-null    object
 100  agency_code                               112 non-null    int64
 101  respondent_name                           112 non-null    object
 102  respondent_state                          112 non-null    object
 103  respondent_city                           112 non-null    object
 104  respondent_zip_code                       112 non-null    object
dtypes: float64(43), int64(42), object(20)
memory usage: 92.8+ KB

## group by census tracts

In [15]:
# filter by action_taken = 1

imperial_rm_originated = imperial_rm_name[imperial_rm_name['action_taken'] == 1]

In [16]:
imperial_rm_originated.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70 entries, 7 to 111
Data columns (total 105 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           70 non-null     int64
 1    lei                                       70 non-null     object
 2    derived_msa-md                            70 non-null     int64
 3    state_code                                70 non-null     object
 4    county_code                               70 non-null     object
 5    census_tract                              70 non-null     object
 6    conforming_loan_limit                     70 non-null     object
 7    derived_loan_product_type                 70 non-null     object
 8    derived_dwelling_category                 70 non-null     object
 9    derived_ethnicity                         70 non-null     object
 10   derived_race                              70 non-null     object
 11   derived_sex                               70 non-null     object
 12   action_taken                              70 non-null     int64
 13   purchaser_type                            70 non-null     int64
 14   preapproval                               70 non-null     int64
 15   loan_type                                 70 non-null     int64
 16   loan_purpose                              70 non-null     int64
 17   lien_status                               70 non-null     int64
 18   reverse_mortgage                          70 non-null     int64
 19   open-end_line_of_credit                   70 non-null     int64
 20   business_or_commercial_purpose            70 non-null     int64
 21   loan_amount                               70 non-null     float64
 22   loan_to_value_ratio                       3 non-null      float64
 23   interest_rate                             33 non-null     float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              70 non-null     int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         12 non-null     float64
 34   negative_amortization                     70 non-null     int64
 35   interest_only_payment                     70 non-null     int64
 36   balloon_payment                           70 non-null     int64
 37   other_nonamortizing_features              70 non-null     int64
 38   property_value                            33 non-null     float64
 39   construction_method                       70 non-null     int64
 40   occupancy_type                            70 non-null     int64
 41   manufactured_home_secured_property_type   70 non-null     int64
 42   manufactured_home_land_property_interest  70 non-null     int64
 43   total_units                               70 non-null     int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    70 non-null     float64
 46   debt_to_income_ratio                      1 non-null      object
 47   applicant_credit_score_type               70 non-null     int64
 48   co-applicant_credit_score_type            70 non-null     int64
 49   applicant_ethnicity-1                     70 non-null     float64
 50   applicant_ethnicity-2                     10 non-null     float64
 51   applicant_ethnicity-3                     0 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  70 non-null     float64
 55   co-applicant_ethnicity-2                  5 non-null      float64
 56   co-applicant_ethnicity-3                  0 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              70 non-null     int64
 60   co-applicant_ethnicity_observed           70 non-null     int64
 61   applicant_race-1                          70 non-null     float64
 62   applicant_race-2                          0 non-null      float64
 63   applicant_race-3                          0 non-null      float64
 64   applicant_race-4                          0 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       70 non-null     float64
 67   co-applicant_race-2                       0 non-null      float64
 68   co-applicant_race-3                       0 non-null      float64
 69   co-applicant_race-4                       0 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   70 non-null     int64
 72   co-applicant_race_observed                70 non-null     int64
 73   applicant_sex                             70 non-null     int64
 74   co-applicant_sex                          70 non-null     int64
 75   applicant_sex_observed                    70 non-null     int64
 76   co-applicant_sex_observed                 70 non-null     int64
 77   applicant_age                             70 non-null     object
 78   co-applicant_age                          70 non-null     object
 79   applicant_age_above_62                    33 non-null     object
 80   co-applicant_age_above_62                 13 non-null     object
 81   submission_of_application                 70 non-null     int64
 82   initially_payable_to_institution          70 non-null     int64
 83   aus-1                                     70 non-null     int64
 84   aus-2                                     0 non-null      float64
 85   aus-3                                     0 non-null      float64
 86   aus-4                                     0 non-null      float64
 87   aus-5                                     0 non-null      float64
 88   denial_reason-1                           70 non-null     int64
 89   denial_reason-2                           0 non-null      float64
 90   denial_reason-3                           0 non-null      float64
 91   denial_reason-4                           0 non-null      float64
 92   tract_population                          70 non-null     int64
 93   tract_minority_population_percent         70 non-null     float64
 94   ffiec_msa_md_median_family_income         70 non-null     int64
 95   tract_to_msa_income_percentage            70 non-null     int64
 96   tract_owner_occupied_units                70 non-null     int64
 97   tract_one_to_four_family_homes            70 non-null     int64
 98   tract_median_age_of_housing_units         70 non-null     int64
 99   tax_id                                    70 non-null     object
 100  agency_code                               70 non-null     int64
 101  respondent_name                           70 non-null     object
 102  respondent_state                          70 non-null     object
 103  respondent_city                           70 non-null     object
 104  respondent_zip_code                       70 non-null     object
dtypes: float64(43), int64(42), object(20)
memory usage: 58.0+ KB

In [17]:
# group by census_tract

imperial_census_counts = imperial_rm_originated.groupby(['census_tract']).count()

In [18]:
imperial_census_counts = imperial_census_counts[['lei']].copy()

In [19]:
imperial_census_counts = imperial_census_counts.reset_index()

In [20]:
imperial_census_counts = imperial_census_counts.sort_values(by=['lei'], ascending=False).copy()
imperial_census_counts.rename(columns={'lei': 'rm_no'}, inplace=True)

In [21]:
imperial_census_counts = imperial_census_counts.reset_index(drop=True)

In [22]:
imperial_census_counts

   census_tract  rm_no
0   06025011000     12
1   06025011201      8
2   06025011600      5
3   06025012200      5
4   06025011700      4
5   06025012302      4
6   06025010700      4
7   06025012002      4
8   06025011900      4
9   06025011803      4
10  06025010400      2
11  06025011300      2
12  06025010900      2
13  06025010600      2
14  06025010500      1
15  06025011400      1
16  06025011801      1
17  06025011802      1
18  06025011202      1
19  06025011100      1
20  06025012100      1
21  06025012400      1

## merge with census data

In [23]:
census_imperial

,census_tract,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_population,62yr_pp_pct,median_age,hispanic_population,non_hispanic_population,non_hispanic_white_population,non_hispanic_black_population,non_hispanic_asian_population,other_races_population,hispanic_pp_pct,non_hispanic_pp_pct,non_hispanic_white_pp_pct,non_hispanic_black_pp_pct,non_hispanic_asian_pp_pct,other_races_pp_pct,Unnamed: 22,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Unnamed: 27,asian_1_population,black_1_population,Unnamed: 30,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!SEX AND AGE!!Total population!!Median age (years),Estimate!!SEX AND AGE!!Total population!!Under 18 years,Estimate!!SEX AND AGE!!Total population!!16 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over,Estimate!!SEX AND AGE!!Total population!!21 years and over,Estimate!!SEX AND AGE!!Total population!!62 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races.1,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,Percent!!SEX AND AGE!!Total population!!20 to 24 years,Percent!!SEX AND AGE!!Total population!!25 to 34 years,Percent!!SEX AND AGE!!Total population!!35 to 44 years,Percent!!SEX AND AGE!!Total population!!45 to 54 years,Percent!!SEX AND AGE!!Total population!!55 to 59 years,Percent!!SEX AND AGE!!Total population!!60 to 64 years,Percent!!SEX AND AGE!!Total population!!65 to 74 years,Percent!!SEX AND AGE!!Total population!!75 to 84 years,Percent!!SEX AND AGE!!Total population!!85 years and over,Percent!!SEX AND AGE!!Total population!!Median age (years),Percent!!SEX AND AGE!!Total population!!Under 18 years,Percent!!SEX AND AGE!!Total population!!16 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over,Percent!!SEX AND AGE!!Total population!!21 years and over,Percent!!SEX AND AGE!!Total population!!62 years and over,Percent!!SEX AND AGE!!Total population!!65 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over.1,Percent!!SEX AND AGE!!Total population!!18 years and over!!Male,Percent!!SEX AND AGE!!Total population!!18 years and over!!Female,Percent!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!65 years and over.1,Percent!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent!!SEX AND AGE!!Total population!!65 years and over!!Female,Percent!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent!!RACE!!Total population,Percent!!RACE!!Total population!!One race,Percent!!RACE!!Total population!!Two or more races,Percent!!RACE!!Total population!!One race.1,Percent!!RACE!!Total population!!One race!!White,Percent!!RACE!!Total population!!One race!!Black or African American,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Percent!!RACE!!Total population!!One race!!Asian,Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian,Percent!!RACE!!Total population!!One race!!Asian!!Chinese,Percent!!RACE!!Total population!!One race!!Asian!!Filipino,Percent!!RACE!!Total population!!One race!!Asian!!Japanese,Percent!!RACE!!Total population!!One race!!Asian!!Korean,Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese,Percent!!RACE!!Total population!!One race!!Asian!!Other Asian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Some other race,Percent!!RACE!!Total population!!Two or more races.1,Percent!!RACE!!Total population!!Two or more races!!White and Black or African American,Percent!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Percent!!RACE!!Total population!!Two or more races!!White and Asian,Percent!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population,Percent!!Race alone or in combination with one or more other races!!Total population!!White,Percent!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Percent!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population!!Asian,Percent!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Percent!!Race alone or in combination with one or more other races!!Total population!!Some other race,Percent!!HISPANIC OR LATINO AND RACE!!Total population,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
361,06025010101,06025,Imperial County,CA,10101,101.01,4137,29,0.7%,33.6,2830,1307,232,871,51,153,68.4%,31.6%,5.6%,21.1%,1.2%,3.7%,NaN,46,9,0,98,NaN,69,925,NaN,4114,23,17887,0,0,0,22,563,1707,1213,506,88,31,0,7,0,33.6,0,4137,4137,4053,29,7,4137,4114,23,17887,7,5,2,250,4137,3900,237,3900,272,925,74,0,0,0,0,69,0,0,12,13,0,13,31,9,0,0,9,0,2551,237,16,46,0,41,4137,371,1034,206,85,28,2673,4137,2830,2276,103,20,431,1307,232,871,46,51,9,0,98,7,91,94,3680,3657,23,4137,99.4,0.6,(X),0,0,0,0.5,13.6,41.3,29.3,12.2,2.1,0.7,0,0.2,0,(X),0,100,100,98,0.7,0.2,4137,99.4,0.6,(X),7,71.4,28.6,(X),4137,94.3,5.7,94.3,6.6,22.4,1.8,0,0,0,0,1.7,0,0,0.3,0.3,0,0.3,0.7,0.2,0,0,0.2,0,61.7,5.7,0.4,1.1,0,1,4137,9,25,5,2.1,0.7,64.6,4137,68.4,55,2.5,0.5,10.4,31.6,5.6,21.1,1.1,1.2,0.2,0,2.4,0.2,2.2,(X),3680,99.4,0.6
362,06025010102,06025,Imperial County,CA,10102,101.02,4108,586,14.3%,25.8,3239,869,493,277,4,95,78.8%,21.2%,12.0%,6.7%,0.1%,2.3%,NaN,0,38,0,57,NaN,4,277,NaN,2113,1995,105.9,544,253,534,393,250,479,431,365,202,185,342,95,35,25.8,1603,2623,2505,2358,586,472,2505,1270,1235,102.8,472,214,258,82.9,4108,3974,134,3974,3276,277,0,0,0,0,0,4,2,0,2,0,0,0,0,38,0,0,0,38,379,134,0,35,0,0,4108,3410,277,62,31,65,451,4108,3239,3181,0,0,58,869,493,277,0,4,38,0,57,0,57,1658,2026,1030,996,4108,51.4,48.6,(X),13.2,6.2,13,9.6,6.1,11.7,10.5,8.9,4.9,4.5,8.3,2.3,0.9,(X),39,63.9,61,57.4,14.3,11.5,2505,50.7,49.3,(X),472,45.3,54.7,(X),4108,96.7,3.3,96.7,79.7,6.7,0,0,0,0,0,0.1,0,0,0,0,0,0,0,0.9,0,0,0,0.9,9.2,3.3,0,0.9,0,0,4108,83,6.7,1.5,0.8,1.6,11,4108,78.8,77.4,0,0,1.4,21.2,12,6.7,0,0.1,0.9,0,1.4,0,1.4,(X),2026,50.8,49.2
363,06025010200,06025,Imperial County,CA,10200,102,2728,446,16.3%,27.9,2181,547,388,61,10,88,79.9%,20.1%,14.2%,2.2%,0.4%,3.2%,NaN,35,0,0,53,NaN,10,61,NaN,1349,1379,97.8,251,309,246,195,205,353,206,334,119,141,231,81,57,27.9,919,1891,1809,1693,446,369,1809,899,910,98.8,369,189,180,105,2728,2576,152,2576,1126,61,42,10,0,0,0,10,0,0,10,0,0,0,0,0,0,0,0,0,1337,152,30,23,0,0,2728,1278,91,65,10,0,1436,2728,2181,2163,0,0,18,547,388,61,35,10,0,0,53,0,53,899,1491,751,740,2728,49.5,50.5,(X),9.2,11.3,9,7.1,7.5,12.9,7.6,12.2,4.4,5.2,8.5,3,2.1,(X),33.7,69.3,66.3,62.1,16.3,13.5,1809,49.7,50.3,(X),369,51.2,48.8,(X),2728,94.4,5.6,94.4,41.3,2.2,1.5,0.4,0,0,0,0.4,0,0,0.4,0,0,0,0,0,0,0,0,0,49,5.6,1.1,0.8,0,0,2728,46.8,3.3,2.4,0.4,0,52.6,2728,79.9,79.3,0,0,0.7,20.1,14.2,2.2,1.3,0.4,0,0,1.9,0,1.9,(X),1491,50.4,49.6
364,06025010300,06025,Imperial County,CA,10300,103,1046,192,18.4%,35.7,424,622,564,0,29,29,40.5%,59.5%,53.9%,0.0%,2.8%,2.8%,NaN,10,0,12,7,NaN,29,1,NaN,588,458,128.4,60,135,119,70,61,67,128,111,74,71,110,22,18,35.7,351,717,695,643,192,150,695,391,304,128.6,150,96,54,177.8,1046,1017,29,1017,793,1,10,0,0,0,0,29,0,0,29,0,0,0,0,0,0,0,0,0,184,29,0,7,0,0,1046,822,1,17,29,0,206,1046,424,418,0,0,6,622,564,0,10,29,0,12,7,0,7,363,620,354,266,1046,56.2,43.8,(X),5.7,12.9,11.4,6.7,5.8,6.4,12.2,10.6,7.1,6.8,10.5,2.1,1.7,(X),33.6,68.5,66.4,61.5,18.4,14.3,695,56.3,43.7,(X),150,64,36,(X),1046,97.2,2.8,97.2,75.8,0.1,1,0,0,0,0,2.8,0,0,2.8,0,0,0,0,0,0,0,0,0,17.6,2.8,0,0.7,0,0,1046,78.6,0.1,1.6,2.8,0,19.7,1046,40.5,40,0,0,0.6,59.5,53.9,0,1,2.8,0,1.1,0.7,0,0.7,(X),620,57.1,42.9
365,06025010400,06025,Imperial County,CA,10400,104,7303,952,13.0%,25.5,6974,329,235,5,51,38,95.5%,4.5%,3.2%,0.1%,0.7%,0.5%,NaN,0,38,0,0,NaN,51,5,NaN,3557,3746,95,731,883,629,661,586,1037,740,531,426,206,567,179,127,25.5,2668,5048,4635,4322,952,873,4635,2230,2405,92.7,873,346,527,65.7,7303,7279,24,7279,6526,5,11,0,0,0,0,51,0,9,0,42,0,0,0,38,0,0,0,38,648,24,0,22,0,0,7303,6548,5,35,51,38,650,7303,6974,6649,0,0,325,329,235,5,0,51,38,0,0,0,0,2177,3423,1672,1751,7303,48.7,51.3,(X),10,12.1,8.6,9.1,8,14.2,10.1,7.3,5.8,2.8,7.8,2.5,1.7,(X),36.5,69.1,63.5,59.2,13,12,4635,48.1,51.9,(X),873,39.6,60.4,(X),7303,99.7,0.3,99.7,89.4,0.1,0.2,0,0,0,0,0.7,0,0.1,0,0.6,0,0,0,0.5,0,0,0,0.5,8.9,0.3,0,0.3,0,0,7303,89.7,0.1,0.5,0.7,0.5,8.9,7303,95.5,91,0,0,4.5,4.5,3.2,0.1,0,0.7,0.5,0,0,0,0,(X),3423,48.8,51.2
366,06025010500,06025,Imperial County,CA,10500,105,7421,926,12.5%,31.7,5847,1574,1146,176,14,238,78.8%,21.2%,15.4%,2.4%,0.2%,3.2%,NaN,35,39,40,124,NaN,14,176,NaN,3729,3692,101,588,751,804,520,427,955,1048,872,341,420,278,323,94,31.7,2620,5015,4801,4644,926,695,4801,2561,2240,114.3,695,323,372,86.8,7421,6830,591,6830,5916,176,35,0,0,0,0,14,0,0,0,0,0,14,0,39,39,0,0,0,650,591,0,319,111,0,7421,6507,176,354,125,39,811,7421,5847,5786,0,0,61,1574,1146,176,35,14,39,40,124,0,124,2164,3770,2094,1676,7421,50.2,49.8,(X),7.9,10.1,10.8,7,5.8,12.9,14.1,11.8,4.6,5.7,3.7,4.4,1.3,(X),35.3,67.6,64.7,62.6,12.5,9.4,4801,53.3,46.7,(X),695,46.5,53.5,(X),7421,92,8,92,79.7,2.4,0.5,0,0,0,0,0.2,0,0,0,0,0,0.2,0,0.5,0.5,0,0,0,8.8,8,0,4.3,1.5,0,7421,87.7,2.4,4.8,1.7,0.5,10.9,7421,78.8,78,0,0,0.8,21.2,15.4,2.4,0.5,0.2,0.5,0.5,1.7,0,1.7,(X),3770,55.5,44.5

In [24]:
imperial_census_rm = pd.merge(
    imperial_census_counts,
    census_imperial,
    on='census_tract',
    how='left',
    validate='1:1'
)

In [25]:
imperial_census_rm.sample(10)

,census_tract,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_population,62yr_pp_pct,median_age,hispanic_population,non_hispanic_population,non_hispanic_white_population,non_hispanic_black_population,non_hispanic_asian_population,other_races_population,hispanic_pp_pct,non_hispanic_pp_pct,non_hispanic_white_pp_pct,non_hispanic_black_pp_pct,non_hispanic_asian_pp_pct,other_races_pp_pct,Unnamed: 22,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Unnamed: 27,asian_1_population,black_1_population,Unnamed: 30,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!SEX AND AGE!!Total population!!Median age (years),Estimate!!SEX AND AGE!!Total population!!Under 18 years,Estimate!!SEX AND AGE!!Total population!!16 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over,Estimate!!SEX AND AGE!!Total population!!21 years and over,Estimate!!SEX AND AGE!!Total population!!62 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races.1,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,Percent!!SEX AND AGE!!Total population!!20 to 24 years,Percent!!SEX AND AGE!!Total population!!25 to 34 years,Percent!!SEX AND AGE!!Total population!!35 to 44 years,Percent!!SEX AND AGE!!Total population!!45 to 54 years,Percent!!SEX AND AGE!!Total population!!55 to 59 years,Percent!!SEX AND AGE!!Total population!!60 to 64 years,Percent!!SEX AND AGE!!Total population!!65 to 74 years,Percent!!SEX AND AGE!!Total population!!75 to 84 years,Percent!!SEX AND AGE!!Total population!!85 years and over,Percent!!SEX AND AGE!!Total population!!Median age (years),Percent!!SEX AND AGE!!Total population!!Under 18 years,Percent!!SEX AND AGE!!Total population!!16 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over,Percent!!SEX AND AGE!!Total population!!21 years and over,Percent!!SEX AND AGE!!Total population!!62 years and over,Percent!!SEX AND AGE!!Total population!!65 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over.1,Percent!!SEX AND AGE!!Total population!!18 years and over!!Male,Percent!!SEX AND AGE!!Total population!!18 years and over!!Female,Percent!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!65 years and over.1,Percent!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent!!SEX AND AGE!!Total population!!65 years and over!!Female,Percent!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent!!RACE!!Total population,Percent!!RACE!!Total population!!One race,Percent!!RACE!!Total population!!Two or more races,Percent!!RACE!!Total population!!One race.1,Percent!!RACE!!Total population!!One race!!White,Percent!!RACE!!Total population!!One race!!Black or African American,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Percent!!RACE!!Total population!!One race!!Asian,Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian,Percent!!RACE!!Total population!!One race!!Asian!!Chinese,Percent!!RACE!!Total population!!One race!!Asian!!Filipino,Percent!!RACE!!Total population!!One race!!Asian!!Japanese,Percent!!RACE!!Total population!!One race!!Asian!!Korean,Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese,Percent!!RACE!!Total population!!One race!!Asian!!Other Asian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Some other race,Percent!!RACE!!Total population!!Two or more races.1,Percent!!RACE!!Total population!!Two or more races!!White and Black or African American,Percent!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Percent!!RACE!!Total population!!Two or more races!!White and Asian,Percent!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population,Percent!!Race alone or in combination with one or more other races!!Total population!!White,Percent!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Percent!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population!!Asian,Percent!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Percent!!Race alone or in combination with one or more other races!!Total population!!Some other race,Percent!!HISPANIC OR LATINO AND RACE!!Total population,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
4,06025011700,4,06025,Imperial County,CA,11700,117,5243,881,16.8%,34.3,4652,591,423,26,34,108,88.7%,11.3%,8.1%,0.5%,0.6%,2.1%,NaN,0,0,14,94,NaN,34,26,NaN,2636,2607,101.1,371,387,411,350,441,753,578,675,322,283,483,150,39,34.3,1415,3949,3828,3618,881,672,3828,1759,2069,85,672,251,421,59.6,5243,4730,513,4730,2342,26,0,0,0,0,0,34,8,0,1,0,0,0,25,30,0,30,0,0,2298,513,0,0,24,0,5243,2855,112,0,144,38,2693,5243,4652,4554,0,0,98,591,423,26,0,34,0,14,94,0,94,1502,3107,1457,1650,5243,50.3,49.7,(X),7.1,7.4,7.8,6.7,8.4,14.4,11,12.9,6.1,5.4,9.2,2.9,0.7,(X),27,75.3,73,69,16.8,12.8,3828,46,54,(X),672,37.4,62.6,(X),5243,90.2,9.8,90.2,44.7,0.5,0,0,0,0,0,0.6,0.2,0,0,0,0,0,0.5,0.6,0,0.6,0,0,43.8,9.8,0,0,0.5,0,5243,54.5,2.1,0,2.7,0.7,51.4,5243,88.7,86.9,0,0,1.9,11.3,8.1,0.5,0,0.6,0,0.3,1.8,0,1.8,(X),3107,46.9,53.1
0,06025011000,12,06025,Imperial County,CA,11000,110,14848,1777,12.0%,27.4,11231,3617,2937,225,346,109,75.6%,24.4%,19.8%,1.5%,2.3%,0.7%,NaN,53,0,33,23,NaN,346,225,NaN,6922,7926,87.3,2072,963,1123,1511,1054,1862,1426,2169,630,554,845,543,96,27.4,4994,10575,9854,8991,1777,1484,9854,4504,5350,84.2,1484,602,882,68.3,14848,14383,465,14383,11547,225,53,0,0,0,0,346,0,2,42,0,299,0,3,0,0,0,0,0,2212,465,111,116,0,0,14848,11986,336,169,389,0,2450,14848,11231,10463,64,0,704,3617,2937,225,53,346,0,33,23,0,23,4757,8730,4078,4652,14848,46.6,53.4,(X),14,6.5,7.6,10.2,7.1,12.5,9.6,14.6,4.2,3.7,5.7,3.7,0.6,(X),33.6,71.2,66.4,60.6,12,10,9854,45.7,54.3,(X),1484,40.6,59.4,(X),14848,96.9,3.1,96.9,77.8,1.5,0.4,0,0,0,0,2.3,0,0,0.3,0,2,0,0,0,0,0,0,0,14.9,3.1,0.7,0.8,0,0,14848,80.7,2.3,1.1,2.6,0,16.5,14848,75.6,70.5,0.4,0,4.7,24.4,19.8,1.5,0.4,2.3,0,0.2,0.2,0,0.2,(X),8730,46.7,53.3
14,06025010500,1,06025,Imperial County,CA,10500,105,7421,926,12.5%,31.7,5847,1574,1146,176,14,238,78.8%,21.2%,15.4%,2.4%,0.2%,3.2%,NaN,35,39,40,124,NaN,14,176,NaN,3729,3692,101,588,751,804,520,427,955,1048,872,341,420,278,323,94,31.7,2620,5015,4801,4644,926,695,4801,2561,2240,114.3,695,323,372,86.8,7421,6830,591,6830,5916,176,35,0,0,0,0,14,0,0,0,0,0,14,0,39,39,0,0,0,650,591,0,319,111,0,7421,6507,176,354,125,39,811,7421,5847,5786,0,0,61,1574,1146,176,35,14,39,40,124,0,124,2164,3770,2094,1676,7421,50.2,49.8,(X),7.9,10.1,10.8,7,5.8,12.9,14.1,11.8,4.6,5.7,3.7,4.4,1.3,(X),35.3,67.6,64.7,62.6,12.5,9.4,4801,53.3,46.7,(X),695,46.5,53.5,(X),7421,92,8,92,79.7,2.4,0.5,0,0,0,0,0.2,0,0,0,0,0,0.2,0,0.5,0.5,0,0,0,8.8,8,0,4.3,1.5,0,7421,87.7,2.4,4.8,1.7,0.5,10.9,7421,78.8,78,0,0,0.8,21.2,15.4,2.4,0.5,0.2,0.5,0.5,1.7,0,1.7,(X),3770,55.5,44.5
16,06025011801,1,06025,Imperial County,CA,11801,118.01,4423,819,18.5%,34.7,3224,1199,851,68,279,1,72.9%,27.1%,19.2%,1.5%,6.3%,0.0%,NaN,1,0,0,0,NaN,289,87,NaN,2076,2347,88.5,458,157,381,384,296,561,372,582,337,233,501,158,3,34.7,1240,3307,3183,2972,819,662,3183,1467,1716,85.5,662,318,344,92.4,4423,4123,300,4123,2497,87,1,0,0,0,0,289,48,69,80,14,78,0,0,0,0,0,0,0,1249,300,0,49,85,0,4423,2797,87,50,374,0,1415,4423,3224,3103,0,0,121,1199,851,68,1,279,0,0,0,0,0,1251,2966,1407,1559,4423,46.9,53.1,(X),10.4,3.5,8.6,8.7,6.7,12.7,8.4,13.2,7.6,5.3,11.3,3.6,0.1,(X),28,74.8,72,67.2,18.5,15,3183,46.1,53.9,(X),662,48,52,(X),4423,93.2,6.8,93.2,56.5,2,0,0,0,0,0,6.5,1.1,1.6,1.8,0.3,1.8,0,0,0,0,0,0,0,28.2,6.8,0,1.1,1.9,0,4423,63.2,2,1.1,8.5,0,32,4423,72.9,70.2,0,0,2.7,27.1,19.2,1.5,0,6.3,0,0,0,0,0,(X),2966,47.4,52.6
6,06025010700,4,06025,Imperial County,CA,10700,107,4409,550,12.5%,28.7,4159,250,154,85,0,11,94.3%,5.7%,3.5%,1.9%,0.0%,0.2%,NaN,0,0,0,11,NaN,0,129,NaN,1827,2582,70.8,484,534,325,433,216,712,574,312,177,238,257,105,42,28.7,1610,2992,2799,2576,550,404,2799,1175,1624,72.4,404,203,201,101,4409,4138,271,4138,3680,129,37,0,0,0,0,0,0,0,0,0,0,0,0,33,0,0,33,0,259,271,142,57,0,0,4409,3921,271,103,21,33,331,4409,4159,4025,10,0,124,250,154,85,0,0,0,0,11,0,11,1507,2267,980,1287,4409,41.4,58.6,(X),11,12.1,7.4,9.8,4.9,16.1,13,7.1,4,5.4,5.8,2.4,1,(X),36.5,67.9,63.5,58.4,12.5,9.2,2799,42,58,(X),404,50.2,49.8,(X),4409,93.9,6.1,93.9,83.5,2.9,0.8,0,0,0,0,0,0,0,0,0,0,0,0,0.7,0,0,0.7,0,5.9,6.1,3.2,1.3,0,0,4409,88.9,6.1,2.3,0.5,0.7,7.5,4409,94.3,91.3,0.2,0,2.8,5.7,3.5,1.9,0,0,0,0,0.2,0,0.2,(X),2267,43.2,56.8
5,06025012302,4,06025,Imperial County,CA,12302,123.02,6290,1451,23.1%,40.8,4278,2012,1665,227,17,103,68.0%,32.0%,26.5%,3.6%,0.3%,1.6%,NaN,0,24,0,79,NaN,17,227,NaN,3376,2914,115.9,507,287,430,382,319,695,831,865,391,503,622,407,51,40.8,1391,4969,4899,4643,1451,1080,4899,2460,2439,100.9,1080,562,518,108.5,6290,6179,111,6179,3725,227,23,0,0,0,0,17,0,0,0,0,0,0,17,24,0,0,0,24,2163,111,24,0,55,0,6290,3822,251,23,86,24,2195,6290,4278,4044,0,0,234,2012,1665,227,0,17,24,0,79,0,79,3132,3749,1888,1861,6290,53.7,46.3,(X),8.1,4.6,6.8,6.1,5.1,11,13.2,13.8,6.2,8,9.9,6.5,0.8,(X),22.1,79,77.9,73.8,23.1,17.2,4899,50.2,49.8,(X),1080,52,48,(X),6290,98.2,1.8,98.2,59.2,3.6,0.4,0,0,0,0,0.3,0,0,0,0,0,0,0.3,0.4,0,0,0,0.4,34.4,1.8,0.4,0,0.9,0,6290,60.8,4,0.4,1.4,0.4,34.9,6290,68,64.3,0,0,3.7,32,26.5,3.6,0,0.3,0.4,0,1.3,0,1.3,(X),3749,50.4,49.6

In [26]:
imperial_census_rm.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 21
Data columns (total 209 columns):
 #    Column                                                                                                                                                            Dtype
---   ------                                                                                                                                                            -----
 0    census_tract                                                                                                                                                      object
 1    rm_no                                                                                                                                                             int64
 2    county_code                                                                                                                                                       object
 3    county                                                                                                                                                            object
 4    state_code                                                                                                                                                        object
 5    census_tract_np                                                                                                                                                   object
 6    census_tract_period                                                                                                                                               object
 7    total_population                                                                                                                                                  int64
 8    62yr_population                                                                                                                                                   int64
 9    62yr_pp_pct                                                                                                                                                       object
 10   median_age                                                                                                                                                        object
 11   hispanic_population                                                                                                                                               int64
 12   non_hispanic_population                                                                                                                                           int64
 13   non_hispanic_white_population                                                                                                                                     int64
 14   non_hispanic_black_population                                                                                                                                     int64
 15   non_hispanic_asian_population                                                                                                                                     int64
 16   other_races_population                                                                                                                                            int64
 17   hispanic_pp_pct                                                                                                                                                   object
 18   non_hispanic_pp_pct                                                                                                                                               object
 19   non_hispanic_white_pp_pct                                                                                                                                         object
 20   non_hispanic_black_pp_pct                                                                                                                                         object
 21   non_hispanic_asian_pp_pct                                                                                                                                         object
 22   other_races_pp_pct                                                                                                                                                object
 23   Unnamed: 22                                                                                                                                                       float64
 24   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone                                          int64
 25   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone                                 int64
 26   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone                                                            int64
 27   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races                                                                int64
 28   Unnamed: 27                                                                                                                                                       float64
 29   asian_1_population                                                                                                                                                int64
 30   black_1_population                                                                                                                                                int64
 31   Unnamed: 30                                                                                                                                                       float64
 32   Estimate!!SEX AND AGE!!Total population!!Male                                                                                                                     int64
 33   Estimate!!SEX AND AGE!!Total population!!Female                                                                                                                   int64
 34   Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)                                                                                        object
 35   Estimate!!SEX AND AGE!!Total population!!Under 5 years                                                                                                            int64
 36   Estimate!!SEX AND AGE!!Total population!!5 to 9 years                                                                                                             int64
 37   Estimate!!SEX AND AGE!!Total population!!10 to 14 years                                                                                                           int64
 38   Estimate!!SEX AND AGE!!Total population!!15 to 19 years                                                                                                           int64
 39   Estimate!!SEX AND AGE!!Total population!!20 to 24 years                                                                                                           int64
 40   Estimate!!SEX AND AGE!!Total population!!25 to 34 years                                                                                                           int64
 41   Estimate!!SEX AND AGE!!Total population!!35 to 44 years                                                                                                           int64
 42   Estimate!!SEX AND AGE!!Total population!!45 to 54 years                                                                                                           int64
 43   Estimate!!SEX AND AGE!!Total population!!55 to 59 years                                                                                                           int64
 44   Estimate!!SEX AND AGE!!Total population!!60 to 64 years                                                                                                           int64
 45   Estimate!!SEX AND AGE!!Total population!!65 to 74 years                                                                                                           int64
 46   Estimate!!SEX AND AGE!!Total population!!75 to 84 years                                                                                                           int64
 47   Estimate!!SEX AND AGE!!Total population!!85 years and over                                                                                                        int64
 48   Estimate!!SEX AND AGE!!Total population!!Median age (years)                                                                                                       object
 49   Estimate!!SEX AND AGE!!Total population!!Under 18 years                                                                                                           int64
 50   Estimate!!SEX AND AGE!!Total population!!16 years and over                                                                                                        int64
 51   Estimate!!SEX AND AGE!!Total population!!18 years and over                                                                                                        int64
 52   Estimate!!SEX AND AGE!!Total population!!21 years and over                                                                                                        int64
 53   Estimate!!SEX AND AGE!!Total population!!62 years and over                                                                                                        int64
 54   Estimate!!SEX AND AGE!!Total population!!65 years and over                                                                                                        int64
 55   Estimate!!SEX AND AGE!!Total population!!18 years and over.1                                                                                                      int64
 56   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male                                                                                                  int64
 57   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female                                                                                                int64
 58   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)                                                                     object
 59   Estimate!!SEX AND AGE!!Total population!!65 years and over.1                                                                                                      int64
 60   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male                                                                                                  int64
 61   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female                                                                                                int64
 62   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)                                                                     object
 63   Estimate!!RACE!!Total population                                                                                                                                  int64
 64   Estimate!!RACE!!Total population!!One race                                                                                                                        int64
 65   Estimate!!RACE!!Total population!!Two or more races                                                                                                               int64
 66   Estimate!!RACE!!Total population!!One race.1                                                                                                                      int64
 67   Estimate!!RACE!!Total population!!One race!!White                                                                                                                 int64
 68   Estimate!!RACE!!Total population!!One race!!Black or African American                                                                                             int64
 69   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native                                                                                     int64
 70   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping                                                           int64
 71   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping                                                           int64
 72   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping                                                             int64
 73   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping                                                              int64
 74   Estimate!!RACE!!Total population!!One race!!Asian                                                                                                                 int64
 75   Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian                                                                                                   int64
 76   Estimate!!RACE!!Total population!!One race!!Asian!!Chinese                                                                                                        int64
 77   Estimate!!RACE!!Total population!!One race!!Asian!!Filipino                                                                                                       int64
 78   Estimate!!RACE!!Total population!!One race!!Asian!!Japanese                                                                                                       int64
 79   Estimate!!RACE!!Total population!!One race!!Asian!!Korean                                                                                                         int64
 80   Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese                                                                                                     int64
 81   Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian                                                                                                    int64
 82   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander                                                                            int64
 83   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian                                                           int64
 84   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro                                                     int64
 85   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan                                                                    int64
 86   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander                                                    int64
 87   Estimate!!RACE!!Total population!!One race!!Some other race                                                                                                       int64
 88   Estimate!!RACE!!Total population!!Two or more races.1                                                                                                             int64
 89   Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American                                                                          int64
 90   Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native                                                                  int64
 91   Estimate!!RACE!!Total population!!Two or more races!!White and Asian                                                                                              int64
 92   Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native                                              int64
 93   Estimate!!Race alone or in combination with one or more other races!!Total population                                                                             int64
 94   Estimate!!Race alone or in combination with one or more other races!!Total population!!White                                                                      int64
 95   Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American                                                  int64
 96   Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native                                          int64
 97   Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian                                                                      int64
 98   Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander                                 int64
 99   Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race                                                            int64
 100  Estimate!!HISPANIC OR LATINO AND RACE!!Total population                                                                                                           int64
 101  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)                                                                         int64
 102  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican                                                                int64
 103  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican                                                           int64
 104  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban                                                                  int64
 105  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino                                               int64
 106  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino                                                                                   int64
 107  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone                                                                      int64
 108  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone                                                  int64
 109  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1                                        int64
 110  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone                                                                      int64
 111  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1                               int64

In [27]:
# subset to the columns that I need

imperial_census_rm = imperial_census_rm[['census_tract', 'rm_no', 'county_code', 'county', 'state_code', 'census_tract_np', 'census_tract_period', 'total_population', '62yr_pp_pct', 'median_age', 'hispanic_pp_pct', 'non_hispanic_black_pp_pct']].copy()

In [28]:
imperial_census_rm

,census_tract,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_pp_pct,median_age,hispanic_pp_pct,non_hispanic_black_pp_pct
0,06025011000,12,06025,Imperial County,CA,11000,110,14848,12.0%,27.4,75.6%,1.5%
1,06025011201,8,06025,Imperial County,CA,11201,112.01,6221,13.0%,32,85.1%,2.4%
2,06025011600,5,06025,Imperial County,CA,11600,116,5728,20.3%,41.4,87.4%,4.2%
3,06025012200,5,06025,Imperial County,CA,12200,122,7237,20.2%,35,98.6%,0.0%
4,06025011700,4,06025,Imperial County,CA,11700,117,5243,16.8%,34.3,88.7%,0.5%
5,06025012302,4,06025,Imperial County,CA,12302,123.02,6290,23.1%,40.8,68.0%,3.6%
6,06025010700,4,06025,Imperial County,CA,10700,107,4409,12.5%,28.7,94.3%,1.9%
7,06025012002,4,06025,Imperial County,CA,12002,120.02,10765,12.7%,30.5,96.5%,0.0%
8,06025011900,4,06025,Imperial County,CA,11900,119,11456,14.5%,31.5,96.7%,0.6%
9,06025011803,4,06025,Imperial County,CA,11803,118.03,6106,13.9%,35.6,82.7%,0.0%
10,06025010400,2,06025,Imperial County,CA,10400,104,7303,13.0%,25.5,95.5%,0.1%
11,06025011300,2,06025,Imperial County,CA,11300,113,11695,13.1%,30.6,92.5%,0.3%
12,06025010900,2,06025,Imperial County,CA,10900,109,7497,16.2%,33.7,82.5%,0.6%
13,06025010600,2,06025,Imperial County,CA,10600,106,6910,21.8%,36.5,70.0%,0.7%
14,06025010500,1,06025,Imperial County,CA,10500,105,7421,12.5%,31.7,78.8%,2.4%
15,06025011400,1,06025,Imperial County,CA,11400,114,4570,17.2%,29.8,92.0%,2.7%
16,06025011801,1,06025,Imperial County,CA,11801,118.01,4423,18.5%,34.7,72.9%,1.5%
17,06025011802,1,06025,Imperial County,CA,11802,118.02,5336,17.3%,33.2,83.8%,0.0%
18,06025011202,1,06025,Imperial County,CA,11202,112.02,5626,17.6%,31.2,93.9%,0.5%
19,06025011100,1,06025,Imperial County,CA,11100,111,4219,15.5%,30.9,70.0%,2.7%
20,06025012100,1,06025,Imperial County,CA,12100,121,6779,22.3%,34.9,98.6%,0.0%
21,06025012400,1,06025,Imperial County,CA,12400,124,713,79.0%,70.5,7.3%,0.8%

In [29]:
# calculate rm per 1000 people

imperial_census_rm['_rm_per_1000'] = (
    imperial_census_rm['rm_no'] / imperial_census_rm['total_population'] * 1000
)

In [30]:
imperial_census_rm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 21
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   census_tract               22 non-null     object
 1   rm_no                      22 non-null     int64
 2   county_code                22 non-null     object
 3   county                     22 non-null     object
 4   state_code                 22 non-null     object
 5   census_tract_np            22 non-null     object
 6   census_tract_period        22 non-null     object
 7   total_population           22 non-null     int64
 8   62yr_pp_pct                22 non-null     object
 9   median_age                 22 non-null     object
 10  hispanic_pp_pct            22 non-null     object
 11  non_hispanic_black_pp_pct  22 non-null     object
 12  _rm_per_1000               22 non-null     float64
dtypes: float64(1), int64(2), object(10)
memory usage: 2.4+ KB

In [31]:
# get the column names

cols = list(imperial_census_rm.columns.values)
cols

['census_tract',
 'rm_no',
 'county_code',
 'county',
 'state_code',
 'census_tract_np',
 'census_tract_period',
 'total_population',
 '62yr_pp_pct',
 'median_age',
 'hispanic_pp_pct',
 'non_hispanic_black_pp_pct',
 '_rm_per_1000']

In [32]:
# reorder the columns

imperial_census_rm = imperial_census_rm[[
    'census_tract', 
    '_rm_per_1000',
    'rm_no',
    'county_code',
    'county',
    'state_code',
    'census_tract_np',
    'census_tract_period',
    'total_population',
    '62yr_pp_pct',
    'median_age',
    'hispanic_pp_pct',
    'non_hispanic_black_pp_pct',
 ]]

In [33]:
# sort by reverse mortgages originated per 1000 people

imperial_census_rm = imperial_census_rm.sort_values(by='_rm_per_1000', ascending=False)
imperial_census_rm

,census_tract,_rm_per_1000,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_pp_pct,median_age,hispanic_pp_pct,non_hispanic_black_pp_pct
21,06025012400,1.402525,1,06025,Imperial County,CA,12400,124,713,79.0%,70.5,7.3%,0.8%
1,06025011201,1.285967,8,06025,Imperial County,CA,11201,112.01,6221,13.0%,32,85.1%,2.4%
6,06025010700,0.907235,4,06025,Imperial County,CA,10700,107,4409,12.5%,28.7,94.3%,1.9%
2,06025011600,0.872905,5,06025,Imperial County,CA,11600,116,5728,20.3%,41.4,87.4%,4.2%
0,06025011000,0.808190,12,06025,Imperial County,CA,11000,110,14848,12.0%,27.4,75.6%,1.5%
4,06025011700,0.762922,4,06025,Imperial County,CA,11700,117,5243,16.8%,34.3,88.7%,0.5%
3,06025012200,0.690894,5,06025,Imperial County,CA,12200,122,7237,20.2%,35,98.6%,0.0%
9,06025011803,0.655093,4,06025,Imperial County,CA,11803,118.03,6106,13.9%,35.6,82.7%,0.0%
5,06025012302,0.635930,4,06025,Imperial County,CA,12302,123.02,6290,23.1%,40.8,68.0%,3.6%
7,06025012002,0.371575,4,06025,Imperial County,CA,12002,120.02,10765,12.7%,30.5,96.5%,0.0%
8,06025011900,0.349162,4,06025,Imperial County,CA,11900,119,11456,14.5%,31.5,96.7%,0.6%
13,06025010600,0.289436,2,06025,Imperial County,CA,10600,106,6910,21.8%,36.5,70.0%,0.7%
10,06025010400,0.273860,2,06025,Imperial County,CA,10400,104,7303,13.0%,25.5,95.5%,0.1%
12,06025010900,0.266773,2,06025,Imperial County,CA,10900,109,7497,16.2%,33.7,82.5%,0.6%
19,06025011100,0.237023,1,06025,Imperial County,CA,11100,111,4219,15.5%,30.9,70.0%,2.7%
16,06025011801,0.226091,1,06025,Imperial County,CA,11801,118.01,4423,18.5%,34.7,72.9%,1.5%
15,06025011400,0.218818,1,06025,Imperial County,CA,11400,114,4570,17.2%,29.8,92.0%,2.7%
17,06025011802,0.187406,1,06025,Imperial County,CA,11802,118.02,5336,17.3%,33.2,83.8%,0.0%
18,06025011202,0.177746,1,06025,Imperial County,CA,11202,112.02,5626,17.6%,31.2,93.9%,0.5%
11,06025011300,0.171013,2,06025,Imperial County,CA,11300,113,11695,13.1%,30.6,92.5%,0.3%
20,06025012100,0.147514,1,06025,Imperial County,CA,12100,121,6779,22.3%,34.9,98.6%,0.0%
14,06025010500,0.134753,1,06025,Imperial County,CA,10500,105,7421,12.5%,31.7,78.8%,2.4%

## export to csv

In [34]:
imperial_rm_name.to_csv('./reverse_mortgage_data/imperial_rm_with_name.csv', index=False)
imperial_census_rm.to_csv('./reverse_mortgage_data/imperial_census_rm.csv', index=False)