In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

## read reverse mortgage data

In [2]:
riverside_rm_all = pd.read_csv('./reverse_mortgage_data/riverside_rm_all.csv', dtype={
    'county_code': str,
    'census_tract': str
})
riverside_rm_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4027 entries, 0 to 4026
Data columns (total 99 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   activity_year                             4027 non-null   int64
 1   lei                                       4027 non-null   object
 2   derived_msa-md                            4027 non-null   int64
 3   state_code                                4027 non-null   object
 4   county_code                               4027 non-null   object
 5   census_tract                              4027 non-null   object
 6   conforming_loan_limit                     4027 non-null   object
 7   derived_loan_product_type                 4027 non-null   object
 8   derived_dwelling_category                 4027 non-null   object
 9   derived_ethnicity                         4027 non-null   object
 10  derived_race                              4027 non-null   object
 11  derived_sex                               4027 non-null   object
 12  action_taken                              4027 non-null   int64
 13  purchaser_type                            4027 non-null   int64
 14  preapproval                               4027 non-null   int64
 15  loan_type                                 4027 non-null   int64
 16  loan_purpose                              4027 non-null   int64
 17  lien_status                               4027 non-null   int64
 18  reverse_mortgage                          4027 non-null   int64
 19  open-end_line_of_credit                   4027 non-null   int64
 20  business_or_commercial_purpose            4027 non-null   int64
 21  loan_amount                               4027 non-null   float64
 22  loan_to_value_ratio                       143 non-null    float64
 23  interest_rate                             2880 non-null   float64
 24  rate_spread                               0 non-null      float64
 25  hoepa_status                              4027 non-null   int64
 26  total_loan_costs                          0 non-null      float64
 27  total_points_and_fees                     0 non-null      float64
 28  origination_charges                       0 non-null      float64
 29  discount_points                           0 non-null      float64
 30  lender_credits                            0 non-null      float64
 31  loan_term                                 0 non-null      float64
 32  prepayment_penalty_term                   0 non-null      float64
 33  intro_rate_period                         2268 non-null   float64
 34  negative_amortization                     4027 non-null   int64
 35  interest_only_payment                     4027 non-null   int64
 36  balloon_payment                           4027 non-null   int64
 37  other_nonamortizing_features              4027 non-null   int64
 38  property_value                            3301 non-null   float64
 39  construction_method                       4027 non-null   int64
 40  occupancy_type                            4027 non-null   int64
 41  manufactured_home_secured_property_type   4027 non-null   int64
 42  manufactured_home_land_property_interest  4027 non-null   int64
 43  total_units                               4027 non-null   int64
 44  multifamily_affordable_units              0 non-null      float64
 45  income                                    3266 non-null   float64
 46  debt_to_income_ratio                      107 non-null    object
 47  applicant_credit_score_type               4027 non-null   int64
 48  co-applicant_credit_score_type            4027 non-null   int64
 49  applicant_ethnicity-1                     4027 non-null   float64
 50  applicant_ethnicity-2                     237 non-null    float64
 51  applicant_ethnicity-3                     3 non-null      float64
 52  applicant_ethnicity-4                     0 non-null      float64
 53  applicant_ethnicity-5                     0 non-null      float64
 54  co-applicant_ethnicity-1                  4027 non-null   float64
 55  co-applicant_ethnicity-2                  108 non-null    float64
 56  co-applicant_ethnicity-3                  0 non-null      float64
 57  co-applicant_ethnicity-4                  0 non-null      float64
 58  co-applicant_ethnicity-5                  0 non-null      float64
 59  applicant_ethnicity_observed              4027 non-null   int64
 60  co-applicant_ethnicity_observed           4027 non-null   int64
 61  applicant_race-1                          4027 non-null   float64
 62  applicant_race-2                          74 non-null     float64
 63  applicant_race-3                          8 non-null      float64
 64  applicant_race-4                          1 non-null      float64
 65  applicant_race-5                          0 non-null      float64
 66  co-applicant_race-1                       4027 non-null   float64
 67  co-applicant_race-2                       33 non-null     float64
 68  co-applicant_race-3                       3 non-null      float64
 69  co-applicant_race-4                       1 non-null      float64
 70  co-applicant_race-5                       0 non-null      float64
 71  applicant_race_observed                   4027 non-null   int64
 72  co-applicant_race_observed                4027 non-null   int64
 73  applicant_sex                             4027 non-null   int64
 74  co-applicant_sex                          4027 non-null   int64
 75  applicant_sex_observed                    4027 non-null   int64
 76  co-applicant_sex_observed                 4027 non-null   int64
 77  applicant_age                             4027 non-null   object
 78  co-applicant_age                          4027 non-null   object
 79  applicant_age_above_62                    3282 non-null   object
 80  co-applicant_age_above_62                 1274 non-null   object
 81  submission_of_application                 4027 non-null   int64
 82  initially_payable_to_institution          4027 non-null   int64
 83  aus-1                                     4027 non-null   int64
 84  aus-2                                     1 non-null      float64
 85  aus-3                                     1 non-null      float64
 86  aus-4                                     1 non-null      float64
 87  aus-5                                     1 non-null      float64
 88  denial_reason-1                           4027 non-null   int64
 89  denial_reason-2                           37 non-null     float64
 90  denial_reason-3                           1 non-null      float64
 91  denial_reason-4                           0 non-null      float64
 92  tract_population                          4027 non-null   int64
 93  tract_minority_population_percent         4027 non-null   float64
 94  ffiec_msa_md_median_family_income         4027 non-null   int64
 95  tract_to_msa_income_percentage            4027 non-null   int64
 96  tract_owner_occupied_units                4027 non-null   int64
 97  tract_one_to_four_family_homes            4027 non-null   int64
 98  tract_median_age_of_housing_units         4027 non-null   int64
dtypes: float64(43), int64(41), object(15)
memory usage: 3.0+ MB

## read census data and filter to county

In [3]:
census_all = pd.read_csv('./census_data/ACS2019_filtered0623.csv', dtype={
    'census_tract': str,
    'county_code': str,
    'census_tract_np': str,
    'census_tract_period': str
})
census_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Columns: 208 entries, census_tract to Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female
dtypes: float64(3), int64(105), object(100)
memory usage: 7.1+ MB

In [5]:
census_riverside = census_all[census_all['county_code'] == '06071'].copy()

In [6]:
census_riverside.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 369 entries, 3508 to 3876
Columns: 208 entries, census_tract to Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female
dtypes: float64(3), int64(105), object(100)
memory usage: 602.5+ KB

## merge lender list

In [7]:
# read lender list

lender_list_2018 = pd.read_csv('./raw_data/lei_agency_name_2018.csv')

In [8]:
lender_list_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5735 entries, 0 to 5734
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   lei                  5735 non-null   object
 1   activity_year        5735 non-null   int64
 2   calendar_quarter     5735 non-null   int64
 3   tax_id               5735 non-null   object
 4   agency_code          5735 non-null   int64
 5   respondent_name      5735 non-null   object
 6   respondent_state     5735 non-null   object
 7   respondent_city      5735 non-null   object
 8   respondent_zip_code  5735 non-null   object
 9   lar_count            5735 non-null   int64
dtypes: int64(4), object(6)
memory usage: 448.2+ KB

In [9]:
# merge by lei

riverside_rm_all

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open-end_line_of_credit,business_or_commercial_purpose,loan_amount,loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co-applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity-2,applicant_ethnicity-3,applicant_ethnicity-4,applicant_ethnicity-5,co-applicant_ethnicity-1,co-applicant_ethnicity-2,co-applicant_ethnicity-3,co-applicant_ethnicity-4,co-applicant_ethnicity-5,applicant_ethnicity_observed,co-applicant_ethnicity_observed,applicant_race-1,applicant_race-2,applicant_race-3,applicant_race-4,applicant_race-5,co-applicant_race-1,co-applicant_race-2,co-applicant_race-3,co-applicant_race-4,co-applicant_race-5,applicant_race_observed,co-applicant_race_observed,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus-1,aus-2,aus-3,aus-4,aus-5,denial_reason-1,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071005300,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Joint,4,0,2,2,31,1,1,1,2,135000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,28.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,3,3,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,3,3,1,2,3,3,>74,>74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5539,82.31,65800,60,832,1524,63
1,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071011600,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,4,0,2,2,31,1,1,1,2,195000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,60.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,3,3,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,3,1,2,3,3,>74,>74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,8051,29.66,65800,114,1908,3496,26
2,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071008704,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,1,71,2,2,31,1,1,1,2,325000.0,NaN,4.885,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,605000.0,1,1,3,5,1,NaN,34.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,2,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,2,1,2,2,2,65-74,65-74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,8670,40.17,65800,96,2030,2892,38
3,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071011101,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Male,4,0,2,2,31,1,1,1,2,95000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,28.0,NaN,9,9,4.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,1,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3565,24.29,65800,121,965,2626,42
4,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071002107,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,1,71,2,2,31,1,1,1,2,255000.0,NaN,4.820,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,435000.0,1,1,3,5,1,NaN,18.0,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5205,62.88,65800,72,803,1242,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4022,2021,B4TYDEB6GKMZO031MB27,40140,CA,06071,06071002606,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,345000.0,NaN,3.948,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,7523,93.57,77500,106,1221,1551,25
4023,2021,B4TYDEB6GKMZO031MB27,40140,CA,06071,06071002304,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,355000.0,NaN,3.960,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,20089,76.21,77500,153,3679,4907,13
4024,2021,B4TYDEB6GKMZO031MB27,40140,CA,06071,06071001311,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,6,0,2,2,5,1,1,1,2,105000.0,NaN,3.066,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,2,2,2,NaN,1,1,3,5,1,NaN,NaN,NaN,9,9,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3,3,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,3,3,4,4,3,3,8888,8888,NaN,NaN,3,3,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3765,81.30,77500,135,664,943,17
4025,2021,2549004XJQQPBYQSMT39,40140,CA,06071,06071003302,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,1,71,2,2,31,1,1,2,2,405000.0,NaN,3.310,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,575000.0,1,1,3,5,1,NaN,NaN,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,6233,82.18,77500,68,943,1527,39
4026,2021,254900JH11ROOV921P96,40140,CA,06071,06071001308,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,White,Female,1,0,2,2,4,1,1,2,2,255000.0,51.1,2.375,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,505000.0,1,1,3,5,1,NaN,29.0,47,9,10,1.0,11.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,65-74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5018,93.74,77500,78,513,984,40

In [10]:
lender_list_2018

,lei,activity_year,calendar_quarter,tax_id,agency_code,respondent_name,respondent_state,respondent_city,respondent_zip_code,lar_count
0,213800QUAI2VH5YM6310,2018,4,05-0402708,7,"Embrace Home Loans, Inc.",RI,Middletown,02842,38810
1,5493001SXWZ4OFP8Z903,2018,4,74-2853239,7,DHI Mortgage Company Limited,TX,Austin,78750,45691
2,549300YHR41F57LS0R28,2018,4,39-0273630,3,Farmers and Merchants Union Bank,WI,Columbus,53925,131
3,549300SX6THT96LFD245,2018,4,26-1866970,3,Oakworth Capital Bank,AL,Birmingham,35209,29
4,2549000UUHZDEKIZ2Z84,2018,4,34-0144365,1,The Citizens National Bank,OH,Woodsfield,43793,97
...,...,...,...,...,...,...,...,...,...,...
5730,Z867SNMO7WGY8TTGQG78,2018,4,55-0744997,3,SUMMIT COMMUNITY BANK,WV,MOOREFIELD,26836,1035
5731,ZF85QS7OXKPBG52R7N18,2018,4,39-1941673,9,Associated Bank NA,WI,Green Bay,54301,20022
5732,ZXMJHJK466PBZTM5F379,2018,4,59-3244348,9,Raymond James Bank National Association,FL,SAINT PETERSBURG,33716,2067
5733,ZXZDWBXF4U47HEP2EO46,2018,4,33-0244449,2,Silvergate Bank,CA,La Jolla,92037,298
5734,SS1TRMSN6BRNMOREEV51,2018,4,38-2734984,9,Flagstar Bank,MI,Troy,48098,149977

In [11]:
riverside_rm_full = pd.merge(
    riverside_rm_all,
    lender_list_2018,
    on='lei',
    how='left',
    validate='m:1'
)

In [12]:
riverside_rm_full.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4027 entries, 0 to 4026
Data columns (total 108 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           4027 non-null   int64
 1    lei                                       4027 non-null   object
 2    derived_msa-md                            4027 non-null   int64
 3    state_code                                4027 non-null   object
 4    county_code                               4027 non-null   object
 5    census_tract                              4027 non-null   object
 6    conforming_loan_limit                     4027 non-null   object
 7    derived_loan_product_type                 4027 non-null   object
 8    derived_dwelling_category                 4027 non-null   object
 9    derived_ethnicity                         4027 non-null   object
 10   derived_race                              4027 non-null   object
 11   derived_sex                               4027 non-null   object
 12   action_taken                              4027 non-null   int64
 13   purchaser_type                            4027 non-null   int64
 14   preapproval                               4027 non-null   int64
 15   loan_type                                 4027 non-null   int64
 16   loan_purpose                              4027 non-null   int64
 17   lien_status                               4027 non-null   int64
 18   reverse_mortgage                          4027 non-null   int64
 19   open-end_line_of_credit                   4027 non-null   int64
 20   business_or_commercial_purpose            4027 non-null   int64
 21   loan_amount                               4027 non-null   float64
 22   loan_to_value_ratio                       143 non-null    float64
 23   interest_rate                             2880 non-null   float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              4027 non-null   int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         2268 non-null   float64
 34   negative_amortization                     4027 non-null   int64
 35   interest_only_payment                     4027 non-null   int64
 36   balloon_payment                           4027 non-null   int64
 37   other_nonamortizing_features              4027 non-null   int64
 38   property_value                            3301 non-null   float64
 39   construction_method                       4027 non-null   int64
 40   occupancy_type                            4027 non-null   int64
 41   manufactured_home_secured_property_type   4027 non-null   int64
 42   manufactured_home_land_property_interest  4027 non-null   int64
 43   total_units                               4027 non-null   int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    3266 non-null   float64
 46   debt_to_income_ratio                      107 non-null    object
 47   applicant_credit_score_type               4027 non-null   int64
 48   co-applicant_credit_score_type            4027 non-null   int64
 49   applicant_ethnicity-1                     4027 non-null   float64
 50   applicant_ethnicity-2                     237 non-null    float64
 51   applicant_ethnicity-3                     3 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  4027 non-null   float64
 55   co-applicant_ethnicity-2                  108 non-null    float64
 56   co-applicant_ethnicity-3                  0 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              4027 non-null   int64
 60   co-applicant_ethnicity_observed           4027 non-null   int64
 61   applicant_race-1                          4027 non-null   float64
 62   applicant_race-2                          74 non-null     float64
 63   applicant_race-3                          8 non-null      float64
 64   applicant_race-4                          1 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       4027 non-null   float64
 67   co-applicant_race-2                       33 non-null     float64
 68   co-applicant_race-3                       3 non-null      float64
 69   co-applicant_race-4                       1 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   4027 non-null   int64
 72   co-applicant_race_observed                4027 non-null   int64
 73   applicant_sex                             4027 non-null   int64
 74   co-applicant_sex                          4027 non-null   int64
 75   applicant_sex_observed                    4027 non-null   int64
 76   co-applicant_sex_observed                 4027 non-null   int64
 77   applicant_age                             4027 non-null   object
 78   co-applicant_age                          4027 non-null   object
 79   applicant_age_above_62                    3282 non-null   object
 80   co-applicant_age_above_62                 1274 non-null   object
 81   submission_of_application                 4027 non-null   int64
 82   initially_payable_to_institution          4027 non-null   int64
 83   aus-1                                     4027 non-null   int64
 84   aus-2                                     1 non-null      float64
 85   aus-3                                     1 non-null      float64
 86   aus-4                                     1 non-null      float64
 87   aus-5                                     1 non-null      float64
 88   denial_reason-1                           4027 non-null   int64
 89   denial_reason-2                           37 non-null     float64
 90   denial_reason-3                           1 non-null      float64
 91   denial_reason-4                           0 non-null      float64
 92   tract_population                          4027 non-null   int64
 93   tract_minority_population_percent         4027 non-null   float64
 94   ffiec_msa_md_median_family_income         4027 non-null   int64
 95   tract_to_msa_income_percentage            4027 non-null   int64
 96   tract_owner_occupied_units                4027 non-null   int64
 97   tract_one_to_four_family_homes            4027 non-null   int64
 98   tract_median_age_of_housing_units         4027 non-null   int64
 99   activity_year_y                           4026 non-null   float64
 100  calendar_quarter                          4026 non-null   float64
 101  tax_id                                    4026 non-null   object
 102  agency_code                               4026 non-null   float64
 103  respondent_name                           4026 non-null   object
 104  respondent_state                          4026 non-null   object
 105  respondent_city                           4026 non-null   object
 106  respondent_zip_code                       4026 non-null   object
 107  lar_count                                 4026 non-null   float64
dtypes: float64(47), int64(41), object(20)
memory usage: 3.3+ MB

In [13]:
riverside_rm_name = riverside_rm_full.drop(columns= ['activity_year_y', 'calendar_quarter', 'lar_count']).copy()

In [14]:
riverside_rm_name.head()

,activity_year_x,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open-end_line_of_credit,business_or_commercial_purpose,loan_amount,loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co-applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity-2,applicant_ethnicity-3,applicant_ethnicity-4,applicant_ethnicity-5,co-applicant_ethnicity-1,co-applicant_ethnicity-2,co-applicant_ethnicity-3,co-applicant_ethnicity-4,co-applicant_ethnicity-5,applicant_ethnicity_observed,co-applicant_ethnicity_observed,applicant_race-1,applicant_race-2,applicant_race-3,applicant_race-4,applicant_race-5,co-applicant_race-1,co-applicant_race-2,co-applicant_race-3,co-applicant_race-4,co-applicant_race-5,applicant_race_observed,co-applicant_race_observed,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus-1,aus-2,aus-3,aus-4,aus-5,denial_reason-1,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units,tax_id,agency_code,respondent_name,respondent_state,respondent_city,respondent_zip_code
0,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071005300,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Joint,4,0,2,2,31,1,1,1,2,135000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,28.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,3,3,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,3,3,1,2,3,3,>74,>74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5539,82.31,65800,60,832,1524,63,11-3469077,7.0,Nationwide Equities Corporation,NJ,Mahwah,07495
1,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071011600,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,4,0,2,2,31,1,1,1,2,195000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,60.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,3,3,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,3,1,2,3,3,>74,>74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,8051,29.66,65800,114,1908,3496,26,11-3469077,7.0,Nationwide Equities Corporation,NJ,Mahwah,07495
2,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071008704,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,1,71,2,2,31,1,1,1,2,325000.0,NaN,4.885,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,605000.0,1,1,3,5,1,NaN,34.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,2,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,2,1,2,2,2,65-74,65-74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,8670,40.17,65800,96,2030,2892,38,11-3469077,7.0,Nationwide Equities Corporation,NJ,Mahwah,07495
3,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071011101,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Male,4,0,2,2,31,1,1,1,2,95000.0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,NaN,1,1,3,5,1,NaN,28.0,NaN,9,9,4.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,1,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3565,24.29,65800,121,965,2626,42,11-3469077,7.0,Nationwide Equities Corporation,NJ,Mahwah,07495
4,2018,549300WH9FMXOC63ZV77,40140,CA,06071,06071002107,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,1,71,2,2,31,1,1,1,2,255000.0,NaN,4.820,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2,2,2,2,435000.0,1,1,3,5,1,NaN,18.0,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5205,62.88,65800,72,803,1242,34,11-3469077,7.0,Nationwide Equities Corporation,NJ,Mahwah,07495

In [15]:
riverside_rm_name.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4027 entries, 0 to 4026
Data columns (total 105 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           4027 non-null   int64
 1    lei                                       4027 non-null   object
 2    derived_msa-md                            4027 non-null   int64
 3    state_code                                4027 non-null   object
 4    county_code                               4027 non-null   object
 5    census_tract                              4027 non-null   object
 6    conforming_loan_limit                     4027 non-null   object
 7    derived_loan_product_type                 4027 non-null   object
 8    derived_dwelling_category                 4027 non-null   object
 9    derived_ethnicity                         4027 non-null   object
 10   derived_race                              4027 non-null   object
 11   derived_sex                               4027 non-null   object
 12   action_taken                              4027 non-null   int64
 13   purchaser_type                            4027 non-null   int64
 14   preapproval                               4027 non-null   int64
 15   loan_type                                 4027 non-null   int64
 16   loan_purpose                              4027 non-null   int64
 17   lien_status                               4027 non-null   int64
 18   reverse_mortgage                          4027 non-null   int64
 19   open-end_line_of_credit                   4027 non-null   int64
 20   business_or_commercial_purpose            4027 non-null   int64
 21   loan_amount                               4027 non-null   float64
 22   loan_to_value_ratio                       143 non-null    float64
 23   interest_rate                             2880 non-null   float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              4027 non-null   int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         2268 non-null   float64
 34   negative_amortization                     4027 non-null   int64
 35   interest_only_payment                     4027 non-null   int64
 36   balloon_payment                           4027 non-null   int64
 37   other_nonamortizing_features              4027 non-null   int64
 38   property_value                            3301 non-null   float64
 39   construction_method                       4027 non-null   int64
 40   occupancy_type                            4027 non-null   int64
 41   manufactured_home_secured_property_type   4027 non-null   int64
 42   manufactured_home_land_property_interest  4027 non-null   int64
 43   total_units                               4027 non-null   int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    3266 non-null   float64
 46   debt_to_income_ratio                      107 non-null    object
 47   applicant_credit_score_type               4027 non-null   int64
 48   co-applicant_credit_score_type            4027 non-null   int64
 49   applicant_ethnicity-1                     4027 non-null   float64
 50   applicant_ethnicity-2                     237 non-null    float64
 51   applicant_ethnicity-3                     3 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  4027 non-null   float64
 55   co-applicant_ethnicity-2                  108 non-null    float64
 56   co-applicant_ethnicity-3                  0 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              4027 non-null   int64
 60   co-applicant_ethnicity_observed           4027 non-null   int64
 61   applicant_race-1                          4027 non-null   float64
 62   applicant_race-2                          74 non-null     float64
 63   applicant_race-3                          8 non-null      float64
 64   applicant_race-4                          1 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       4027 non-null   float64
 67   co-applicant_race-2                       33 non-null     float64
 68   co-applicant_race-3                       3 non-null      float64
 69   co-applicant_race-4                       1 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   4027 non-null   int64
 72   co-applicant_race_observed                4027 non-null   int64
 73   applicant_sex                             4027 non-null   int64
 74   co-applicant_sex                          4027 non-null   int64
 75   applicant_sex_observed                    4027 non-null   int64
 76   co-applicant_sex_observed                 4027 non-null   int64
 77   applicant_age                             4027 non-null   object
 78   co-applicant_age                          4027 non-null   object
 79   applicant_age_above_62                    3282 non-null   object
 80   co-applicant_age_above_62                 1274 non-null   object
 81   submission_of_application                 4027 non-null   int64
 82   initially_payable_to_institution          4027 non-null   int64
 83   aus-1                                     4027 non-null   int64
 84   aus-2                                     1 non-null      float64
 85   aus-3                                     1 non-null      float64
 86   aus-4                                     1 non-null      float64
 87   aus-5                                     1 non-null      float64
 88   denial_reason-1                           4027 non-null   int64
 89   denial_reason-2                           37 non-null     float64
 90   denial_reason-3                           1 non-null      float64
 91   denial_reason-4                           0 non-null      float64
 92   tract_population                          4027 non-null   int64
 93   tract_minority_population_percent         4027 non-null   float64
 94   ffiec_msa_md_median_family_income         4027 non-null   int64
 95   tract_to_msa_income_percentage            4027 non-null   int64
 96   tract_owner_occupied_units                4027 non-null   int64
 97   tract_one_to_four_family_homes            4027 non-null   int64
 98   tract_median_age_of_housing_units         4027 non-null   int64
 99   tax_id                                    4026 non-null   object
 100  agency_code                               4026 non-null   float64
 101  respondent_name                           4026 non-null   object
 102  respondent_state                          4026 non-null   object
 103  respondent_city                           4026 non-null   object
 104  respondent_zip_code                       4026 non-null   object
dtypes: float64(44), int64(41), object(20)
memory usage: 3.3+ MB

## group by census tracts

In [16]:
# filter by action_taken = 1

riverside_rm_originated = riverside_rm_name[riverside_rm_name['action_taken'] == 1]

In [17]:
riverside_rm_originated.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2165 entries, 2 to 4026
Data columns (total 105 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    activity_year_x                           2165 non-null   int64
 1    lei                                       2165 non-null   object
 2    derived_msa-md                            2165 non-null   int64
 3    state_code                                2165 non-null   object
 4    county_code                               2165 non-null   object
 5    census_tract                              2165 non-null   object
 6    conforming_loan_limit                     2165 non-null   object
 7    derived_loan_product_type                 2165 non-null   object
 8    derived_dwelling_category                 2165 non-null   object
 9    derived_ethnicity                         2165 non-null   object
 10   derived_race                              2165 non-null   object
 11   derived_sex                               2165 non-null   object
 12   action_taken                              2165 non-null   int64
 13   purchaser_type                            2165 non-null   int64
 14   preapproval                               2165 non-null   int64
 15   loan_type                                 2165 non-null   int64
 16   loan_purpose                              2165 non-null   int64
 17   lien_status                               2165 non-null   int64
 18   reverse_mortgage                          2165 non-null   int64
 19   open-end_line_of_credit                   2165 non-null   int64
 20   business_or_commercial_purpose            2165 non-null   int64
 21   loan_amount                               2165 non-null   float64
 22   loan_to_value_ratio                       118 non-null    float64
 23   interest_rate                             2091 non-null   float64
 24   rate_spread                               0 non-null      float64
 25   hoepa_status                              2165 non-null   int64
 26   total_loan_costs                          0 non-null      float64
 27   total_points_and_fees                     0 non-null      float64
 28   origination_charges                       0 non-null      float64
 29   discount_points                           0 non-null      float64
 30   lender_credits                            0 non-null      float64
 31   loan_term                                 0 non-null      float64
 32   prepayment_penalty_term                   0 non-null      float64
 33   intro_rate_period                         1101 non-null   float64
 34   negative_amortization                     2165 non-null   int64
 35   interest_only_payment                     2165 non-null   int64
 36   balloon_payment                           2165 non-null   int64
 37   other_nonamortizing_features              2165 non-null   int64
 38   property_value                            2103 non-null   float64
 39   construction_method                       2165 non-null   int64
 40   occupancy_type                            2165 non-null   int64
 41   manufactured_home_secured_property_type   2165 non-null   int64
 42   manufactured_home_land_property_interest  2165 non-null   int64
 43   total_units                               2165 non-null   int64
 44   multifamily_affordable_units              0 non-null      float64
 45   income                                    2128 non-null   float64
 46   debt_to_income_ratio                      76 non-null     object
 47   applicant_credit_score_type               2165 non-null   int64
 48   co-applicant_credit_score_type            2165 non-null   int64
 49   applicant_ethnicity-1                     2165 non-null   float64
 50   applicant_ethnicity-2                     161 non-null    float64
 51   applicant_ethnicity-3                     1 non-null      float64
 52   applicant_ethnicity-4                     0 non-null      float64
 53   applicant_ethnicity-5                     0 non-null      float64
 54   co-applicant_ethnicity-1                  2165 non-null   float64
 55   co-applicant_ethnicity-2                  78 non-null     float64
 56   co-applicant_ethnicity-3                  0 non-null      float64
 57   co-applicant_ethnicity-4                  0 non-null      float64
 58   co-applicant_ethnicity-5                  0 non-null      float64
 59   applicant_ethnicity_observed              2165 non-null   int64
 60   co-applicant_ethnicity_observed           2165 non-null   int64
 61   applicant_race-1                          2165 non-null   float64
 62   applicant_race-2                          43 non-null     float64
 63   applicant_race-3                          4 non-null      float64
 64   applicant_race-4                          0 non-null      float64
 65   applicant_race-5                          0 non-null      float64
 66   co-applicant_race-1                       2165 non-null   float64
 67   co-applicant_race-2                       20 non-null     float64
 68   co-applicant_race-3                       2 non-null      float64
 69   co-applicant_race-4                       0 non-null      float64
 70   co-applicant_race-5                       0 non-null      float64
 71   applicant_race_observed                   2165 non-null   int64
 72   co-applicant_race_observed                2165 non-null   int64
 73   applicant_sex                             2165 non-null   int64
 74   co-applicant_sex                          2165 non-null   int64
 75   applicant_sex_observed                    2165 non-null   int64
 76   co-applicant_sex_observed                 2165 non-null   int64
 77   applicant_age                             2165 non-null   object
 78   co-applicant_age                          2165 non-null   object
 79   applicant_age_above_62                    2098 non-null   object
 80   co-applicant_age_above_62                 866 non-null    object
 81   submission_of_application                 2165 non-null   int64
 82   initially_payable_to_institution          2165 non-null   int64
 83   aus-1                                     2165 non-null   int64
 84   aus-2                                     0 non-null      float64
 85   aus-3                                     0 non-null      float64
 86   aus-4                                     0 non-null      float64
 87   aus-5                                     0 non-null      float64
 88   denial_reason-1                           2165 non-null   int64
 89   denial_reason-2                           0 non-null      float64
 90   denial_reason-3                           0 non-null      float64
 91   denial_reason-4                           0 non-null      float64
 92   tract_population                          2165 non-null   int64
 93   tract_minority_population_percent         2165 non-null   float64
 94   ffiec_msa_md_median_family_income         2165 non-null   int64
 95   tract_to_msa_income_percentage            2165 non-null   int64
 96   tract_owner_occupied_units                2165 non-null   int64
 97   tract_one_to_four_family_homes            2165 non-null   int64
 98   tract_median_age_of_housing_units         2165 non-null   int64
 99   tax_id                                    2164 non-null   object
 100  agency_code                               2164 non-null   float64
 101  respondent_name                           2164 non-null   object
 102  respondent_state                          2164 non-null   object
 103  respondent_city                           2164 non-null   object
 104  respondent_zip_code                       2164 non-null   object
dtypes: float64(44), int64(41), object(20)
memory usage: 1.8+ MB

In [18]:
# group by census_tract

riverside_census_counts = riverside_rm_originated.groupby(['census_tract']).count()

In [19]:
riverside_census_counts = riverside_census_counts[['lei']].copy()

In [20]:
riverside_census_counts = riverside_census_counts.reset_index()

In [21]:
riverside_census_counts = riverside_census_counts.sort_values(by=['lei'], ascending=False).copy()
riverside_census_counts.rename(columns={'lei': 'rm_no'}, inplace=True)

In [22]:
riverside_census_counts = riverside_census_counts.reset_index(drop=True)

In [23]:
riverside_census_counts

    census_tract  rm_no
0    06071009707     49
1    06071009118     28
2    06071009715     24
3    06071010411     21
4    06071010901     20
..           ...    ...
329  06071004403      1
330  06071009400      1
331  06071001309      1
332  06071004301      1
333  06071003603      1

[334 rows x 2 columns]

## merge with census data

In [24]:
census_riverside

,census_tract,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_population,62yr_pp_pct,median_age,hispanic_population,non_hispanic_population,non_hispanic_white_population,non_hispanic_black_population,non_hispanic_asian_population,other_races_population,hispanic_pp_pct,non_hispanic_pp_pct,non_hispanic_white_pp_pct,non_hispanic_black_pp_pct,non_hispanic_asian_pp_pct,other_races_pp_pct,Unnamed: 22,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Unnamed: 27,asian_1_population,black_1_population,Unnamed: 30,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!SEX AND AGE!!Total population!!Median age (years),Estimate!!SEX AND AGE!!Total population!!Under 18 years,Estimate!!SEX AND AGE!!Total population!!16 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over,Estimate!!SEX AND AGE!!Total population!!21 years and over,Estimate!!SEX AND AGE!!Total population!!62 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races.1,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,Percent!!SEX AND AGE!!Total population!!20 to 24 years,Percent!!SEX AND AGE!!Total population!!25 to 34 years,Percent!!SEX AND AGE!!Total population!!35 to 44 years,Percent!!SEX AND AGE!!Total population!!45 to 54 years,Percent!!SEX AND AGE!!Total population!!55 to 59 years,Percent!!SEX AND AGE!!Total population!!60 to 64 years,Percent!!SEX AND AGE!!Total population!!65 to 74 years,Percent!!SEX AND AGE!!Total population!!75 to 84 years,Percent!!SEX AND AGE!!Total population!!85 years and over,Percent!!SEX AND AGE!!Total population!!Median age (years),Percent!!SEX AND AGE!!Total population!!Under 18 years,Percent!!SEX AND AGE!!Total population!!16 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over,Percent!!SEX AND AGE!!Total population!!21 years and over,Percent!!SEX AND AGE!!Total population!!62 years and over,Percent!!SEX AND AGE!!Total population!!65 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over.1,Percent!!SEX AND AGE!!Total population!!18 years and over!!Male,Percent!!SEX AND AGE!!Total population!!18 years and over!!Female,Percent!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!65 years and over.1,Percent!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent!!SEX AND AGE!!Total population!!65 years and over!!Female,Percent!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent!!RACE!!Total population,Percent!!RACE!!Total population!!One race,Percent!!RACE!!Total population!!Two or more races,Percent!!RACE!!Total population!!One race.1,Percent!!RACE!!Total population!!One race!!White,Percent!!RACE!!Total population!!One race!!Black or African American,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Percent!!RACE!!Total population!!One race!!Asian,Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian,Percent!!RACE!!Total population!!One race!!Asian!!Chinese,Percent!!RACE!!Total population!!One race!!Asian!!Filipino,Percent!!RACE!!Total population!!One race!!Asian!!Japanese,Percent!!RACE!!Total population!!One race!!Asian!!Korean,Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese,Percent!!RACE!!Total population!!One race!!Asian!!Other Asian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Some other race,Percent!!RACE!!Total population!!Two or more races.1,Percent!!RACE!!Total population!!Two or more races!!White and Black or African American,Percent!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Percent!!RACE!!Total population!!Two or more races!!White and Asian,Percent!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population,Percent!!Race alone or in combination with one or more other races!!Total population!!White,Percent!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Percent!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population!!Asian,Percent!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Percent!!Race alone or in combination with one or more other races!!Total population!!Some other race,Percent!!HISPANIC OR LATINO AND RACE!!Total population,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
3508,06071000103,06071,San Bernardino County,CA,103,1.03,4438,609,13.7%,36.4,1322,3116,1153,167,1703,93,29.8%,70.2%,26.0%,3.8%,38.4%,2.1%,NaN,0,0,11,82,NaN,1716,167,NaN,2111,2327,90.7,145,219,348,384,257,734,669,576,338,312,339,93,24,36.4,948,3626,3490,3307,609,456,3490,1544,1946,79.3,456,198,258,76.7,4438,4273,165,4273,1898,167,0,0,0,0,0,1716,23,700,592,49,204,11,137,0,0,0,0,0,492,165,4,40,40,19,4438,1994,190,59,1806,0,554,4438,1322,1024,69,12,217,3116,1153,167,0,1703,0,11,82,0,82,1744,3135,1418,1717,4438,47.6,52.4,(X),3.3,4.9,7.8,8.7,5.8,16.5,15.1,13,7.6,7,7.6,2.1,0.5,(X),21.4,81.7,78.6,74.5,13.7,10.3,3490,44.2,55.8,(X),456,43.4,56.6,(X),4438,96.3,3.7,96.3,42.8,3.8,0,0,0,0,0,38.7,0.5,15.8,13.3,1.1,4.6,0.2,3.1,0,0,0,0,0,11.1,3.7,0.1,0.9,0.9,0.4,4438,44.9,4.3,1.3,40.7,0,12.5,4438,29.8,23.1,1.6,0.3,4.9,70.2,26,3.8,0,38.4,0,0.2,1.8,0,1.8,(X),3135,45.2,54.8
3509,06071000104,06071,San Bernardino County,CA,104,1.04,6928,1262,18.2%,37.7,1570,5358,1598,331,3351,78,22.7%,77.3%,23.1%,4.8%,48.4%,1.1%,NaN,0,0,0,78,NaN,3367,331,NaN,3291,3637,90.5,472,448,403,333,564,946,920,806,608,465,635,255,73,37.7,1473,5537,5455,5205,1262,963,5455,2658,2797,95,963,486,477,101.9,6928,6738,190,6738,2693,331,0,0,0,0,0,3367,216,1236,710,77,247,179,702,0,0,0,0,0,347,190,0,34,50,0,6928,2798,353,34,3502,0,431,6928,1570,1172,38,11,349,5358,1598,331,0,3351,0,0,78,12,66,2187,4664,2295,2369,6928,47.5,52.5,(X),6.8,6.5,5.8,4.8,8.1,13.7,13.3,11.6,8.8,6.7,9.2,3.7,1.1,(X),21.3,79.9,78.7,75.1,18.2,13.9,5455,48.7,51.3,(X),963,50.5,49.5,(X),6928,97.3,2.7,97.3,38.9,4.8,0,0,0,0,0,48.6,3.1,17.8,10.2,1.1,3.6,2.6,10.1,0,0,0,0,0,5,2.7,0,0.5,0.7,0,6928,40.4,5.1,0.5,50.5,0,6.2,6928,22.7,16.9,0.5,0.2,5,77.3,23.1,4.8,0,48.4,0,0,1.1,0.2,1,(X),4664,49.2,50.8
3510,06071000105,06071,San Bernardino County,CA,105,1.05,6392,988,15.5%,39.4,1609,4783,1711,343,2429,300,25.2%,74.8%,26.8%,5.4%,38.0%,4.7%,NaN,150,0,28,122,NaN,2463,355,NaN,3279,3113,105.3,137,354,599,453,499,819,681,1176,464,429,358,291,132,39.4,1470,5168,4922,4764,988,781,4922,2457,2465,99.7,781,384,397,96.7,6392,6200,192,6200,2841,355,189,0,0,39,12,2463,200,1046,391,57,559,5,205,0,0,0,0,0,352,192,22,67,74,0,6392,3004,387,256,2556,19,362,6392,1609,1316,26,12,255,4783,1711,343,150,2429,0,28,122,6,116,2073,4186,2092,2094,6392,51.3,48.7,(X),2.1,5.5,9.4,7.1,7.8,12.8,10.7,18.4,7.3,6.7,5.6,4.6,2.1,(X),23,80.9,77,74.5,15.5,12.2,4922,49.9,50.1,(X),781,49.2,50.8,(X),6392,97,3,97,44.4,5.6,3,0,0,0.6,0.2,38.5,3.1,16.4,6.1,0.9,8.7,0.1,3.2,0,0,0,0,0,5.5,3,0.3,1,1.2,0,6392,47,6.1,4,40,0.3,5.7,6392,25.2,20.6,0.4,0.2,4,74.8,26.8,5.4,2.3,38,0,0.4,1.9,0.1,1.8,(X),4186,50,50
3511,06071000107,06071,San Bernardino County,CA,107,1.07,3062,633,20.7%,41.8,1011,2051,1350,83,599,19,33.0%,67.0%,44.1%,2.7%,19.6%,0.6%,NaN,0,0,0,19,NaN,603,83,NaN,1515,1547,97.9,136,108,135,224,333,354,380,510,215,119,271,179,98,41.8,532,2635,2530,2420,633,548,2530,1278,1252,102.1,548,258,290,89,3062,2997,65,2997,2028,83,13,0,0,0,0,603,33,234,272,14,9,16,25,0,0,0,0,0,270,65,9,18,10,0,3062,2065,120,31,613,0,298,3062,1011,802,24,10,175,2051,1350,83,0,599,0,0,19,0,19,995,2452,1251,1201,3062,49.5,50.5,(X),4.4,3.5,4.4,7.3,10.9,11.6,12.4,16.7,7,3.9,8.9,5.8,3.2,(X),17.4,86.1,82.6,79,20.7,17.9,2530,50.5,49.5,(X),548,47.1,52.9,(X),3062,97.9,2.1,97.9,66.2,2.7,0.4,0,0,0,0,19.7,1.1,7.6,8.9,0.5,0.3,0.5,0.8,0,0,0,0,0,8.8,2.1,0.3,0.6,0.3,0,3062,67.4,3.9,1,20,0,9.7,3062,33,26.2,0.8,0.3,5.7,67,44.1,2.7,0,19.6,0,0,0.6,0,0.6,(X),2452,51,49
3512,06071000108,06071,San Bernardino County,CA,108,1.08,5923,673,11.4%,31.8,1846,4077,1902,261,1761,153,31.2%,68.8%,32.1%,4.4%,29.7%,2.6%,NaN,0,15,0,138,NaN,1761,261,NaN,3038,2885,105.3,334,479,509,431,571,815,876,621,430,394,393,41,29,31.8,1637,4435,4286,4093,673,463,4286,2173,2113,102.8,463,262,201,130.3,5923,5703,220,5703,3383,261,0,0,0,0,0,1761,89,864,358,58,152,66,174,15,0,0,15,0,283,220,0,27,131,0,5923,3553,273,44,1937,41,307,5923,1846,1478,34,12,322,4077,1902,261,0,1761,15,0,138,7,131,1931,3695,1876,1819,5923,51.3,48.7,(X),5.6,8.1,8.6,7.3,9.6,13.8,14.8,10.5,7.3,6.7,6.6,0.7,0.5,(X),27.6,74.9,72.4,69.1,11.4,7.8,4286,50.7,49.3,(X),463,56.6,43.4,(X),5923,96.3,3.7,96.3,57.1,4.4,0,0,0,0,0,29.7,1.5,14.6,6,1,2.6,1.1,2.9,0.3,0,0,0.3,0,4.8,3.7,0,0.5,2.2,0,5923,60,4.6,0.7,32.7,0.7,5.2,5923,31.2,25,0.6,0.2,5.4,68.8,32.1,4.4,0,29.7,0.3,0,2.3,0.1,2.2,(X),3695,50.8,49.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [25]:
riverside_census_rm = pd.merge(
    riverside_census_counts,
    census_riverside,
    on='census_tract',
    how='left',
    validate='1:1'
)

In [26]:
riverside_census_rm.sample(10)

,census_tract,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_population,62yr_pp_pct,median_age,hispanic_population,non_hispanic_population,non_hispanic_white_population,non_hispanic_black_population,non_hispanic_asian_population,other_races_population,hispanic_pp_pct,non_hispanic_pp_pct,non_hispanic_white_pp_pct,non_hispanic_black_pp_pct,non_hispanic_asian_pp_pct,other_races_pp_pct,Unnamed: 22,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Unnamed: 27,asian_1_population,black_1_population,Unnamed: 30,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!SEX AND AGE!!Total population!!Median age (years),Estimate!!SEX AND AGE!!Total population!!Under 18 years,Estimate!!SEX AND AGE!!Total population!!16 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over,Estimate!!SEX AND AGE!!Total population!!21 years and over,Estimate!!SEX AND AGE!!Total population!!62 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races.1,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races.1,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,Percent!!SEX AND AGE!!Total population!!20 to 24 years,Percent!!SEX AND AGE!!Total population!!25 to 34 years,Percent!!SEX AND AGE!!Total population!!35 to 44 years,Percent!!SEX AND AGE!!Total population!!45 to 54 years,Percent!!SEX AND AGE!!Total population!!55 to 59 years,Percent!!SEX AND AGE!!Total population!!60 to 64 years,Percent!!SEX AND AGE!!Total population!!65 to 74 years,Percent!!SEX AND AGE!!Total population!!75 to 84 years,Percent!!SEX AND AGE!!Total population!!85 years and over,Percent!!SEX AND AGE!!Total population!!Median age (years),Percent!!SEX AND AGE!!Total population!!Under 18 years,Percent!!SEX AND AGE!!Total population!!16 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over,Percent!!SEX AND AGE!!Total population!!21 years and over,Percent!!SEX AND AGE!!Total population!!62 years and over,Percent!!SEX AND AGE!!Total population!!65 years and over,Percent!!SEX AND AGE!!Total population!!18 years and over.1,Percent!!SEX AND AGE!!Total population!!18 years and over!!Male,Percent!!SEX AND AGE!!Total population!!18 years and over!!Female,Percent!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!65 years and over.1,Percent!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent!!SEX AND AGE!!Total population!!65 years and over!!Female,Percent!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent!!RACE!!Total population,Percent!!RACE!!Total population!!One race,Percent!!RACE!!Total population!!Two or more races,Percent!!RACE!!Total population!!One race.1,Percent!!RACE!!Total population!!One race!!White,Percent!!RACE!!Total population!!One race!!Black or African American,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Percent!!RACE!!Total population!!One race!!Asian,Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian,Percent!!RACE!!Total population!!One race!!Asian!!Chinese,Percent!!RACE!!Total population!!One race!!Asian!!Filipino,Percent!!RACE!!Total population!!One race!!Asian!!Japanese,Percent!!RACE!!Total population!!One race!!Asian!!Korean,Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese,Percent!!RACE!!Total population!!One race!!Asian!!Other Asian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Some other race,Percent!!RACE!!Total population!!Two or more races.1,Percent!!RACE!!Total population!!Two or more races!!White and Black or African American,Percent!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Percent!!RACE!!Total population!!Two or more races!!White and Asian,Percent!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population,Percent!!Race alone or in combination with one or more other races!!Total population!!White,Percent!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Percent!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Percent!!Race alone or in combination with one or more other races!!Total population!!Asian,Percent!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Percent!!Race alone or in combination with one or more other races!!Total population!!Some other race,Percent!!HISPANIC OR LATINO AND RACE!!Total population,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
19,06071011403,14,06071,San Bernardino County,CA,11403,114.03,3451,894,25.9%,43,876,2575,2446,95,8,26,25.4%,74.6%,70.9%,2.8%,0.2%,0.8%,NaN,26,0,0,0,NaN,8,95,NaN,1602,1849,86.6,323,150,142,154,163,461,417,370,252,262,500,189,68,43,723,2788,2728,2636,894,757,2728,1227,1501,81.7,757,376,381,98.7,3451,3451,0,3451,3297,95,26,0,0,0,0,8,0,0,0,8,0,0,0,0,0,0,0,0,25,0,0,0,0,0,3451,3297,95,26,8,0,25,3451,876,753,28,64,31,2575,2446,95,26,8,0,0,0,0,0,4381,2681,1197,1484,3451,46.4,53.6,(X),9.4,4.3,4.1,4.5,4.7,13.4,12.1,10.7,7.3,7.6,14.5,5.5,2,(X),21,80.8,79,76.4,25.9,21.9,2728,45,55,(X),757,49.7,50.3,(X),3451,100,0,100,95.5,2.8,0.8,0,0,0,0,0.2,0,0,0,0.2,0,0,0,0,0,0,0,0,0.7,0,0,0,0,0,3451,95.5,2.8,0.8,0.2,0,0.7,3451,25.4,21.8,0.8,1.9,0.9,74.6,70.9,2.8,0.8,0.2,0,0,0,0,0,(X),2681,44.6,55.4
106,06071008001,7,06071,San Bernardino County,CA,8001,80.01,7008,1416,20.2%,38.7,3319,3689,2177,80,1186,246,47.4%,52.6%,31.1%,1.1%,16.9%,3.5%,NaN,0,0,18,228,NaN,1200,80,NaN,3444,3564,96.6,411,436,395,414,392,1104,934,922,413,401,588,448,150,38.7,1457,5669,5551,5313,1416,1186,5551,2545,3006,84.7,1186,452,734,61.6,7008,6488,520,6488,4514,80,24,0,0,0,0,1200,36,93,634,0,43,179,215,0,0,0,0,0,670,520,81,98,90,0,7008,4962,161,170,1377,0,921,7008,3319,3088,22,35,174,3689,2177,80,0,1186,0,18,228,0,228,2215,4975,2289,2686,7008,49.1,50.9,(X),5.9,6.2,5.6,5.9,5.6,15.8,13.3,13.2,5.9,5.7,8.4,6.4,2.1,(X),20.8,80.9,79.2,75.8,20.2,16.9,5551,45.8,54.2,(X),1186,38.1,61.9,(X),7008,92.6,7.4,92.6,64.4,1.1,0.3,0,0,0,0,17.1,0.5,1.3,9,0,0.6,2.6,3.1,0,0,0,0,0,9.6,7.4,1.2,1.4,1.3,0,7008,70.8,2.3,2.4,19.6,0,13.1,7008,47.4,44.1,0.3,0.5,2.5,52.6,31.1,1.1,0,16.9,0,0.3,3.3,0,3.3,(X),4975,46,54
322,06071003611,1,06071,San Bernardino County,CA,3611,36.11,4874,485,10.0%,30.8,3326,1548,713,420,250,165,68.2%,31.8%,14.6%,8.6%,5.1%,3.4%,NaN,0,0,22,143,NaN,250,433,NaN,2642,2232,118.4,481,332,364,289,376,871,722,448,370,218,171,204,28,30.8,1378,3616,3496,3408,485,403,3496,1884,1612,116.9,403,161,242,66.5,4874,4636,238,4636,2882,433,0,0,0,0,0,250,0,26,134,0,32,0,58,0,0,0,0,0,1071,238,130,19,37,0,4874,3088,563,51,287,0,1123,4874,3326,2831,0,0,495,1548,713,420,0,250,0,22,143,0,143,1591,2803,1593,1210,4874,54.2,45.8,(X),9.9,6.8,7.5,5.9,7.7,17.9,14.8,9.2,7.6,4.5,3.5,4.2,0.6,(X),28.3,74.2,71.7,69.9,10,8.3,3496,53.9,46.1,(X),403,40,60,(X),4874,95.1,4.9,95.1,59.1,8.9,0,0,0,0,0,5.1,0,0.5,2.7,0,0.7,0,1.2,0,0,0,0,0,22,4.9,2.7,0.4,0.8,0,4874,63.4,11.6,1,5.9,0,23,4874,68.2,58.1,0,0,10.2,31.8,14.6,8.6,0,5.1,0,0.5,2.9,0,2.9,(X),2803,56.8,43.2
41,06071004604,12,06071,San Bernardino County,CA,4604,46.04,5621,577,10.3%,27.9,4255,1366,663,454,23,226,75.7%,24.3%,11.8%,8.1%,0.4%,4.0%,NaN,35,0,32,159,NaN,35,576,NaN,2658,2963,89.7,554,598,505,399,506,872,508,701,332,172,249,156,69,27.9,1941,3915,3680,3534,577,474,3680,1735,1945,89.2,474,207,267,77.5,5621,5347,274,5347,3475,576,40,23,0,0,0,35,0,10,25,0,0,0,0,0,0,0,0,0,1221,274,0,66,0,21,5621,3632,755,127,45,0,1408,5621,4255,4090,19,0,146,1366,663,454,35,23,0,32,159,0,159,1614,3080,1466,1614,5621,47.3,52.7,(X),9.9,10.6,9,7.1,9,15.5,9,12.5,5.9,3.1,4.4,2.8,1.2,(X),34.5,69.6,65.5,62.9,10.3,8.4,3680,47.1,52.9,(X),474,43.7,56.3,(X),5621,95.1,4.9,95.1,61.8,10.2,0.7,0.4,0,0,0,0.6,0,0.2,0.4,0,0,0,0,0,0,0,0,0,21.7,4.9,0,1.2,0,0.4,5621,64.6,13.4,2.3,0.8,0,25,5621,75.7,72.8,0.3,0,2.6,24.3,11.8,8.1,0.6,0.4,0,0.6,2.8,0,2.8,(X),3080,47.6,52.4
34,06071008703,12,06071,San Bernardino County,CA,8703,87.03,7573,2340,30.9%,49.6,1408,6165,5500,136,274,255,18.6%,81.4%,72.6%,1.8%,3.6%,3.4%,NaN,0,23,0,232,NaN,274,267,NaN,3705,3868,95.8,305,453,556,371,202,666,788,1058,452,759,1228,593,142,49.6,1600,6159,5973,5839,2340,1963,5973,2829,3144,90,1963,902,1061,85,7573,7228,345,7228,6438,267,0,0,0,0,0,274,61,56,138,13,0,0,6,23,0,0,23,0,226,345,59,93,113,0,7573,6756,353,93,395,23,298,7573,1408,1151,35,88,134,6165,5500,136,0,274,23,0,232,10,222,2778,5749,2773,2976,7573,48.9,51.1,(X),4,6,7.3,4.9,2.7,8.8,10.4,14,6,10,16.2,7.8,1.9,(X),21.1,81.3,78.9,77.1,30.9,25.9,5973,47.4,52.6,(X),1963,46,54,(X),7573,95.4,4.6,95.4,85,3.5,0,0,0,0,0,3.6,0.8,0.7,1.8,0.2,0,0,0.1,0.3,0,0,0.3,0,3,4.6,0.8,1.2,1.5,0,7573,89.2,4.7,1.2,5.2,0.3,3.9,7573,18.6,15.2,0.5,1.2,1.8,81.4,72.6,1.8,0,3.6,0.3,0,3.1,0.1,2.9,(X),5749,48.2,51.8
55,06071008401,11,06071,San Bernardino County,CA,8401,84.01,10335,1483,14.3%,32.6,3708,6627,4879,408,889,451,35.9%,64.1%,47.2%,3.9%,8.6%,4.4%,NaN,22,47,0,382,NaN,898,408,NaN,5156,5179,99.6,621,437,385,1464,1059,1522,1254,1212,566,576,858,209,172,32.6,1973,8758,8362,7148,1483,1239,8362,4134,4228,97.8,1239,620,619,100.2,10335,9556,779,9556,7615,408,27,0,0,0,0,898,238,131,289,80,61,47,52,47,0,0,7,40,561,779,26,39,104,47,10335,8247,856,227,1313,98,698,10335,3708,2621,178,31,878,6627,4879,408,22,889,47,0,382,0,382,3247,7901,3843,4058,10335,49.9,50.1,(X),6,4.2,3.7,14.2,10.2,14.7,12.1,11.7,5.5,5.6,8.3,2,1.7,(X),19.1,84.7,80.9,69.2,14.3,12,8362,49.4,50.6,(X),1239,50,50,(X),10335,92.5,7.5,92.5,73.7,3.9,0.3,0,0,0,0,8.7,2.3,1.3,2.8,0.8,0.6,0.5,0.5,0.5,0,0,0.1,0.4,5.4,7.5,0.3,0.4,1,0.5,10335,79.8,8.3,2.2,12.7,0.9,6.8,10335,35.9,25.4,1.7,0.3,8.5,64.1,47.2,3.9,0.2,8.6,0.5,0,3.7,0,3.7,(X),7901,48.6,51.4

In [27]:
riverside_census_rm.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 334 entries, 0 to 333
Data columns (total 209 columns):
 #    Column                                                                                                                                                            Dtype
---   ------                                                                                                                                                            -----
 0    census_tract                                                                                                                                                      object
 1    rm_no                                                                                                                                                             int64
 2    county_code                                                                                                                                                       object
 3    county                                                                                                                                                            object
 4    state_code                                                                                                                                                        object
 5    census_tract_np                                                                                                                                                   object
 6    census_tract_period                                                                                                                                               object
 7    total_population                                                                                                                                                  int64
 8    62yr_population                                                                                                                                                   int64
 9    62yr_pp_pct                                                                                                                                                       object
 10   median_age                                                                                                                                                        object
 11   hispanic_population                                                                                                                                               int64
 12   non_hispanic_population                                                                                                                                           int64
 13   non_hispanic_white_population                                                                                                                                     int64
 14   non_hispanic_black_population                                                                                                                                     int64
 15   non_hispanic_asian_population                                                                                                                                     int64
 16   other_races_population                                                                                                                                            int64
 17   hispanic_pp_pct                                                                                                                                                   object
 18   non_hispanic_pp_pct                                                                                                                                               object
 19   non_hispanic_white_pp_pct                                                                                                                                         object
 20   non_hispanic_black_pp_pct                                                                                                                                         object
 21   non_hispanic_asian_pp_pct                                                                                                                                         object
 22   other_races_pp_pct                                                                                                                                                object
 23   Unnamed: 22                                                                                                                                                       float64
 24   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone                                          int64
 25   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone                                 int64
 26   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone                                                            int64
 27   Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races                                                                int64
 28   Unnamed: 27                                                                                                                                                       float64
 29   asian_1_population                                                                                                                                                int64
 30   black_1_population                                                                                                                                                int64
 31   Unnamed: 30                                                                                                                                                       float64
 32   Estimate!!SEX AND AGE!!Total population!!Male                                                                                                                     int64
 33   Estimate!!SEX AND AGE!!Total population!!Female                                                                                                                   int64
 34   Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)                                                                                        object
 35   Estimate!!SEX AND AGE!!Total population!!Under 5 years                                                                                                            int64
 36   Estimate!!SEX AND AGE!!Total population!!5 to 9 years                                                                                                             int64
 37   Estimate!!SEX AND AGE!!Total population!!10 to 14 years                                                                                                           int64
 38   Estimate!!SEX AND AGE!!Total population!!15 to 19 years                                                                                                           int64
 39   Estimate!!SEX AND AGE!!Total population!!20 to 24 years                                                                                                           int64
 40   Estimate!!SEX AND AGE!!Total population!!25 to 34 years                                                                                                           int64
 41   Estimate!!SEX AND AGE!!Total population!!35 to 44 years                                                                                                           int64
 42   Estimate!!SEX AND AGE!!Total population!!45 to 54 years                                                                                                           int64
 43   Estimate!!SEX AND AGE!!Total population!!55 to 59 years                                                                                                           int64
 44   Estimate!!SEX AND AGE!!Total population!!60 to 64 years                                                                                                           int64
 45   Estimate!!SEX AND AGE!!Total population!!65 to 74 years                                                                                                           int64
 46   Estimate!!SEX AND AGE!!Total population!!75 to 84 years                                                                                                           int64
 47   Estimate!!SEX AND AGE!!Total population!!85 years and over                                                                                                        int64
 48   Estimate!!SEX AND AGE!!Total population!!Median age (years)                                                                                                       object
 49   Estimate!!SEX AND AGE!!Total population!!Under 18 years                                                                                                           int64
 50   Estimate!!SEX AND AGE!!Total population!!16 years and over                                                                                                        int64
 51   Estimate!!SEX AND AGE!!Total population!!18 years and over                                                                                                        int64
 52   Estimate!!SEX AND AGE!!Total population!!21 years and over                                                                                                        int64
 53   Estimate!!SEX AND AGE!!Total population!!62 years and over                                                                                                        int64
 54   Estimate!!SEX AND AGE!!Total population!!65 years and over                                                                                                        int64
 55   Estimate!!SEX AND AGE!!Total population!!18 years and over.1                                                                                                      int64
 56   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male                                                                                                  int64
 57   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female                                                                                                int64
 58   Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)                                                                     object
 59   Estimate!!SEX AND AGE!!Total population!!65 years and over.1                                                                                                      int64
 60   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male                                                                                                  int64
 61   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female                                                                                                int64
 62   Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)                                                                     object
 63   Estimate!!RACE!!Total population                                                                                                                                  int64
 64   Estimate!!RACE!!Total population!!One race                                                                                                                        int64
 65   Estimate!!RACE!!Total population!!Two or more races                                                                                                               int64
 66   Estimate!!RACE!!Total population!!One race.1                                                                                                                      int64
 67   Estimate!!RACE!!Total population!!One race!!White                                                                                                                 int64
 68   Estimate!!RACE!!Total population!!One race!!Black or African American                                                                                             int64
 69   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native                                                                                     int64
 70   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping                                                           int64
 71   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping                                                           int64
 72   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping                                                             int64
 73   Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping                                                              int64
 74   Estimate!!RACE!!Total population!!One race!!Asian                                                                                                                 int64
 75   Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian                                                                                                   int64
 76   Estimate!!RACE!!Total population!!One race!!Asian!!Chinese                                                                                                        int64
 77   Estimate!!RACE!!Total population!!One race!!Asian!!Filipino                                                                                                       int64
 78   Estimate!!RACE!!Total population!!One race!!Asian!!Japanese                                                                                                       int64
 79   Estimate!!RACE!!Total population!!One race!!Asian!!Korean                                                                                                         int64
 80   Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese                                                                                                     int64
 81   Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian                                                                                                    int64
 82   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander                                                                            int64
 83   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian                                                           int64
 84   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro                                                     int64
 85   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan                                                                    int64
 86   Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander                                                    int64
 87   Estimate!!RACE!!Total population!!One race!!Some other race                                                                                                       int64
 88   Estimate!!RACE!!Total population!!Two or more races.1                                                                                                             int64
 89   Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American                                                                          int64
 90   Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native                                                                  int64
 91   Estimate!!RACE!!Total population!!Two or more races!!White and Asian                                                                                              int64
 92   Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native                                              int64
 93   Estimate!!Race alone or in combination with one or more other races!!Total population                                                                             int64
 94   Estimate!!Race alone or in combination with one or more other races!!Total population!!White                                                                      int64
 95   Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American                                                  int64
 96   Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native                                          int64
 97   Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian                                                                      int64
 98   Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander                                 int64
 99   Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race                                                            int64
 100  Estimate!!HISPANIC OR LATINO AND RACE!!Total population                                                                                                           int64
 101  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)                                                                         int64
 102  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican                                                                int64
 103  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican                                                           int64
 104  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban                                                                  int64
 105  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino                                               int64
 106  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino                                                                                   int64
 107  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone                                                                      int64
 108  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone                                                  int64
 109  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone.1                                        int64
 110  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone                                                                      int64
 111  Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone.1                               int64

In [28]:
# subset to the columns that I need

riverside_census_rm = riverside_census_rm[['census_tract', 'rm_no', 'county_code', 'county', 'state_code', 'census_tract_np', 'census_tract_period', 'total_population', '62yr_pp_pct', 'median_age', 'hispanic_pp_pct', 'non_hispanic_black_pp_pct']].copy()

In [29]:
riverside_census_rm

,census_tract,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_pp_pct,median_age,hispanic_pp_pct,non_hispanic_black_pp_pct
0,06071009707,49,06071,San Bernardino County,CA,9707,97.07,6433,48.6%,60.9,23.3%,5.7%
1,06071009118,28,06071,San Bernardino County,CA,9118,91.18,21531,8.3%,32.8,51.7%,15.1%
2,06071009715,24,06071,San Bernardino County,CA,9715,97.15,8818,24.4%,37.5,38.5%,5.7%
3,06071010411,21,06071,San Bernardino County,CA,10411,104.11,6659,30.5%,45.9,18.5%,2.9%
4,06071010901,20,06071,San Bernardino County,CA,10901,109.01,4121,34.7%,48.5,14.9%,1.7%
...,...,...,...,...,...,...,...,...,...,...,...,...
329,06071004403,1,06071,San Bernardino County,CA,4403,44.03,5054,12.6%,32.8,84.8%,6.4%
330,06071009400,1,06071,San Bernardino County,CA,9400,94,3262,12.7%,29.4,44.5%,24.8%
331,06071001309,1,06071,San Bernardino County,CA,1309,13.09,4658,15.1%,34.4,74.7%,8.5%
332,06071004301,1,06071,San Bernardino County,CA,4301,43.01,4449,12.8%,33.1,71.2%,19.3%
333,06071003603,1,06071,San Bernardino County,CA,3603,36.03,3938,12.1%,32.5,74.8%,9.0%

In [30]:
# calculate rm per 1000 people

riverside_census_rm['_rm_per_1000'] = (
    riverside_census_rm['rm_no'] / riverside_census_rm['total_population'] * 1000
)

In [31]:
riverside_census_rm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 334 entries, 0 to 333
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   census_tract               334 non-null    object
 1   rm_no                      334 non-null    int64
 2   county_code                334 non-null    object
 3   county                     334 non-null    object
 4   state_code                 334 non-null    object
 5   census_tract_np            334 non-null    object
 6   census_tract_period        334 non-null    object
 7   total_population           334 non-null    int64
 8   62yr_pp_pct                334 non-null    object
 9   median_age                 334 non-null    object
 10  hispanic_pp_pct            334 non-null    object
 11  non_hispanic_black_pp_pct  334 non-null    object
 12  _rm_per_1000               334 non-null    float64
dtypes: float64(1), int64(2), object(10)
memory usage: 36.5+ KB

In [32]:
# get the column names

cols = list(riverside_census_rm.columns.values)
cols

['census_tract',
 'rm_no',
 'county_code',
 'county',
 'state_code',
 'census_tract_np',
 'census_tract_period',
 'total_population',
 '62yr_pp_pct',
 'median_age',
 'hispanic_pp_pct',
 'non_hispanic_black_pp_pct',
 '_rm_per_1000']

In [33]:
# reorder the columns

riverside_census_rm = riverside_census_rm[[
    'census_tract', 
    '_rm_per_1000',
    'rm_no',
    'county_code',
    'county',
    'state_code',
    'census_tract_np',
    'census_tract_period',
    'total_population',
    '62yr_pp_pct',
    'median_age',
    'hispanic_pp_pct',
    'non_hispanic_black_pp_pct',
 ]]

In [34]:
# sort by reverse mortgages originated per 1000 people

riverside_census_rm = riverside_census_rm.sort_values(by='_rm_per_1000', ascending=False)
riverside_census_rm

,census_tract,_rm_per_1000,rm_no,county_code,county,state_code,census_tract_np,census_tract_period,total_population,62yr_pp_pct,median_age,hispanic_pp_pct,non_hispanic_black_pp_pct
0,06071009707,7.616975,49,06071,San Bernardino County,CA,9707,97.07,6433,48.6%,60.9,23.3%,5.7%
12,06071010902,7.153076,15,06071,San Bernardino County,CA,10902,109.02,2097,26.9%,46.2,23.1%,0.3%
81,06071011002,6.324666,9,06071,San Bernardino County,CA,11002,110.02,1423,25.3%,49.1,28.7%,3.4%
133,06071011203,4.985755,7,06071,San Bernardino County,CA,11203,112.03,1404,33.0%,50.5,28.9%,0.3%
4,06071010901,4.853191,20,06071,San Bernardino County,CA,10901,109.01,4121,34.7%,48.5,14.9%,1.7%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,06071010421,0.166583,1,06071,San Bernardino County,CA,10421,104.21,6003,7.8%,23.4,32.5%,18.6%
303,06071004101,0.156152,1,06071,San Bernardino County,CA,4101,41.01,6404,6.9%,28.5,86.8%,4.4%
305,06071007409,0.143287,1,06071,San Bernardino County,CA,7409,74.09,6979,11.1%,30.3,66.6%,10.2%
310,06071000303,0.127600,1,06071,San Bernardino County,CA,303,3.03,7837,13.6%,29,86.3%,0.3%
306,06071002402,0.119560,1,06071,San Bernardino County,CA,2402,24.02,8364,7.3%,29.2,87.3%,1.4%

## export to csv

In [35]:
riverside_rm_name.to_csv('./reverse_mortgage_data/riverside_rm_with_name.csv', index=False)
riverside_census_rm.to_csv('./reverse_mortgage_data/riverside_census_rm.csv', index=False)